<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/modules\Servicepterodactyl\html_admin\mod_servicepterodactyl_settings.latte */
final class Template_f467636f3e extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'breadcrumbs' => 'blockBreadcrumbs', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('meta_title', get_defined_vars()) /* pos 24:1 */;
		echo "\n";
		$active_menu = 'system' /* pos 25:1 */;
		echo "\n";
		$this->renderBlock('breadcrumbs', get_defined_vars()) /* pos 27:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 35:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 23:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 24 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Module Settings')) /* pos 24:19 */;
	}


	/** {block breadcrumbs} on line 27 */
	public function blockBreadcrumbs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<ul>
    <li class="firstB"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('/'))) /* pos 29:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 29:47 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('system'))) /* pos 30:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 30:37 */;
		echo '</a></li>
    <li class="lastB">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Module Settings')) /* pos 31:23 */;
		echo '</li>
</ul>
';
	}


	/** {block content} on line 35 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="widget">
    <div class="head">
        <h5 class="iCog">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Module Settings')) /* pos 39:26 */;
		echo '</h5>
    </div>

';
		$params = $admin->extension_config_get(['ext' => 'mod_servicepterodactyl']) /* pos 42:3 */;
		echo '
  <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/extension/config_save'))) /* pos 44:33 */;
		echo ' class="mainForm api-form"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('Configuration updated')) /* pos 44:116 */;
		echo '>

      <div class="help">
          <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Module Settings')) /* pos 47:15 */;
		echo '</h3>
          <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('There are a couple of things you need to specify before you can sell servers')) /* pos 48:14 */;
		echo '</p>
      </div>

      <fieldset>
          <div class="rowElem noborder">
              <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('API Key')) /* pos 53:22 */;
		echo '</label>
              <div class="formRight">
                  <input type="text" name="api_key"';
		echo LR\HtmlHelpers::formatAttribute(' value', $params['api_key'] ?? '') /* pos 55:61 */;
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('API Key')) /* pos 55:103 */;
		echo '/>
              </div>
              <div class="fix"></div>
          </div>

          <div class="rowElem">
              <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('API Version')) /* pos 61:22 */;
		echo '</label>
              <div class="formRight">
                  <input type="text" name="api_version"';
		echo LR\HtmlHelpers::formatAttribute(' value', $params['api_version'] ?? 'v1') /* pos 63:65 */;
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('v1')) /* pos 63:113 */;
		echo '/>
              </div>
              <div class="fix"></div>
          </div>

          <div class="rowElem noborder">
              <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Panel Base URL')) /* pos 69:22 */;
		echo '</label>
              <div class="formRight">
                  <input type="text" name="panel_url"';
		echo LR\HtmlHelpers::formatAttribute(' value', $params['panel_url'] ?? '') /* pos 71:63 */;
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('https://panel.example.com')) /* pos 71:107 */;
		echo '/>
              </div>
              <div class="fix"></div>
          </div>

          <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Update')) /* pos 76:41 */;
		echo ' class="greyishBtn submitForm" />
          <input type="hidden" name="ext" value="mod_servicepterodactyl" />
      </fieldset>
  </form>
</div>
';
	}
}
