<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/modules\Addons\html_admin\mod_addons_settings.latte */
final class Template_edbf969235 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'breadcrumbs' => 'blockBreadcrumbs', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 25:1 */;
		echo '

';
		$active_menu = 'system' /* pos 27:1 */;
		echo "\n";
		$this->renderBlock('breadcrumbs', get_defined_vars()) /* pos 29:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 37:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 23:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 25 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('OHMS Addons')) /* pos 25:19 */;
	}


	/** {block breadcrumbs} on line 29 */
	public function blockBreadcrumbs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<ul>
    <li class="firstB"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('index'))) /* pos 31:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 31:51 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('system'))) /* pos 32:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 32:37 */;
		echo '</a></li>
    <li class="lastB">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('OHMS Addons')) /* pos 33:23 */;
		echo '</li>
</ul>
';
	}


	/** {block content} on line 37 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget">
    <div class="head">
        <h5>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('OHMS Addons')) /* pos 40:13 */;
		echo '</h5>
    </div>
    <div class="body">
        <div class="admin-addon-grid">
            <section class="admin-addon-card">
                <div class="admin-addon-card-head">
                    <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Module Extensions')) /* pos 46:25 */;
		echo '</h3>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Addon modules are system extensions. They are separate from sellable product add-ons.')) /* pos 47:24 */;
		echo '</p>
                </div>

                <div class="nNote">
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create addon modules in the filesystem, then install or activate them from Extensions. OHMS Addons are admin/system extensions used to extend functionality.')) /* pos 51:24 */;
		echo '</p>
                </div>

                <pre class="admin-addon-code">modules/
  Myaddon/
    manifest.json
    Controller/
      Admin.php
    html_admin/
      mod_myaddon_settings.latte</pre>

                <pre class="admin-addon-code">{
  "id": "myaddon",
  "type": "mod",
  "name": "My Addon",
  "description": "Custom admin addon example",
  "version": "1.0.0"
}</pre>

                <div class="nNote">
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('A settings card appears automatically when the module has mod_myaddon_settings.latte in html_admin and the module is active or core.')) /* pos 71:24 */;
		echo '</p>
                </div>

                <div class="admin-addon-actions">
                    <a class="greyishBtn"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('extension'))) /* pos 75:51 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Open extensions')) /* pos 75:71 */;
		echo '</a>
                    <a class="greyishBtn"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('system'))) /* pos 76:51 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Back to settings')) /* pos 76:68 */;
		echo '</a>
                </div>
            </section>
        </div>
    </div>
</div>
';
	}
}
