<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html\mod_extension_index.latte */
final class Template_c2ccfe3ee2 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 26:1 */;
		echo '

';
		$active_menu = 'extensions' /* pos 28:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 30:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 202:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['ext' => '57', 'hook' => '118'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 24:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 26 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Extensions')) /* pos 26:19 */;
	}


	/** {block content} on line 30 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget simpleTabs">
    <ul class="tabs">
        <li><a href="#tab-index">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Extensions')) /* pos 33:34 */;
		echo '</a></li>
        <li><a href="#tab-core">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Update OHMS')) /* pos 34:33 */;
		echo '</a></li>
        <li><a href="#tab-about">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Learn more about extensions')) /* pos 35:34 */;
		echo '</a></li>
        <li><a href="#tab-hooks">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Hooks')) /* pos 36:34 */;
		echo '</a></li>
    </ul>

    <div class="tabs_container">
        <div class="fix"></div>
        <div class="tab_content nopadding" id="tab-index">
            <div class="help">
                <h5>OHMS extensions</h5>
                <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Activate or deactivate extensions')) /* pos 44:20 */;
		echo '</p>
            </div>
            <table class="tableStatic wide">
                <thead>
                    <tr>
                        <td width="3%">&nbsp;</td>
                        <td width="20%">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Extension')) /* pos 50:41 */;
		echo '</td>
                        <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Description')) /* pos 51:29 */;
		echo '</td>
                        <td style="width: 21%;">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Actions')) /* pos 52:49 */;
		echo '</td>
                    </tr>
                </thead>

                <tbody>
';
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($admin->extension_get_list, $ʟ_it ?? null) as $ext) /* pos 57:17 */ {
			echo '                <tr>
                    <td><img';
			echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($ext->icon_url ?? 'images/icons/middlenav/cog.png')) /* pos 59:36 */;
			echo LR\HtmlHelpers::formatAttribute(' alt', $ext->name) /* pos 59:95 */;
			echo ' style="width: 32px; height: 32px;"/></td>
                    <td><strong>';
			echo LR\HtmlHelpers::escapeText($ext->name) /* pos 60:33 */;
			echo '</strong> ';
			echo LR\HtmlHelpers::escapeText($ext->version) /* pos 60:55 */;
			echo '<br />by <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($ext->author_url)) /* pos 60:89 */;
			echo ' target="_blank">';
			echo LR\HtmlHelpers::escapeText($ext->author) /* pos 60:124 */;
			echo '</a></td>
                    <td>
                        ';
			echo LR\HtmlHelpers::escapeText(($this->filters->bbmd)($ext->description)) /* pos 62:25 */;
			echo '
                        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($ext->project_url)) /* pos 63:35 */;
			echo ' target="_blank" title="Project details">Learn more</a>
                    </td>
                    <td>
';
			if ($ext->type == 'mod') /* pos 66:25 */ {
				if ($ext->status == 'installed') /* pos 67:29 */ {
					echo '                            <a class="api-link bb-button btn14"';
					echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/extension/deactivate', ['type' => $ext->type, 'id' => $ext->id]))) /* pos 68:73 */;
					echo ' data-api-confirm="Are you sure?" data-api-reload="Module was deactivated"';
					echo LR\HtmlHelpers::formatAttribute(' title', ($this->filters->trans)('Deactivate')) /* pos 68:233 */;
					echo '>
                                <img src="';
					echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 69:43 */;
					echo 'images/icons/dark/close.png" alt="" class="icon">
                            </a>
';
				} else /* pos 71:29 */ {
					echo '                            <a class="btnIconLeft mr10 api-link"';
					echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/extension/activate', ['type' => $ext->type, 'id' => $ext->id]))) /* pos 72:74 */;
					echo ' data-api-confirm="Are you sure?" data-api-jsonp="onAfterModuleActivated">
                                <img src="';
					echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 73:43 */;
					echo 'images/icons/dark/cog.png" alt="" class="icon"><span>Activate</span>
                            </a>
';
				}
			} else /* pos 76:25 */ {
				echo '                        &nbsp;
';
			}
			echo "\n";
			if ($ext->has_settings) /* pos 80:25 */ {
				echo '                            <a class="bb-button btn14" href="';
				echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('extension/settings')) /* pos 81:62 */;
				echo '/';
				echo LR\HtmlHelpers::escapeAttr($ext->id) /* pos 81:92 */;
				echo '">
                                <img src="';
				echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 82:43 */;
				echo 'images/icons/dark/pencil.png" alt="" class="icon"';
				echo LR\HtmlHelpers::formatAttribute(' title', ($this->filters->trans)('Module settings')) /* pos 82:115 */;
				echo '>
                            </a>
';
			}
			echo '                    </td>
                </tr>
';
		}
		if ($iterator->isEmpty()) /* pos 87:17 */ {
			echo '                    <tr>
                        <td colspan="4">
                            ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('The list is empty')) /* pos 90:29 */;
			echo '
                        </td>
                    </tr>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4"></td>
                    </tr>
                </tfoot>
            </table>

            <div class="help">
                <h5>OHMS modules on extension site</h5>
            </div>
';
		$this->createTemplate('partial_extensions.latte', $this->params, 'include')->renderToContentType('html') /* pos 105:13 */;
		echo '        </div>

        <div class="tab_content nopadding" id="tab-hooks">
            <table class="tableStatic wide">
                <thead>
                    <tr>
                        <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Extension')) /* pos 112:29 */;
		echo '</td>
                        <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Hook')) /* pos 113:29 */;
		echo '</td>
                    </tr>
                </thead>

                <tbody>
';
		foreach ($admin->hook_get_list(['per_page' => 90])->list as $hook) /* pos 118:17 */ {
			echo '                <tr>
                    <td>
                        ';
			echo LR\HtmlHelpers::escapeText(($this->filters->capitalize)($hook->rel_id)) /* pos 121:25 */;
			echo '
                    </td>
                    <td>
                        ';
			echo LR\HtmlHelpers::escapeText($hook->event) /* pos 124:25 */;
			echo '
                    </td>
                </tr>
';

		}

		echo '                </tbody>
            </table>
        </div>
            
        <div class="tab_content nopadding" id="tab-core">
            <div class="help">
                <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Automatic update')) /* pos 134:21 */;
		echo '</h3>
                <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Automatic updater is a tool to update OHMS to latest version in one click. Works on these hosting environments where PHP has permissions to overwrite files uploaded via FTP.')) /* pos 135:20 */;
		echo '</p>
            </div>

            <div class="body">
                ';
		echo LR\HtmlHelpers::escapeText(($this->filters->bbmd)($admin->system_release_notes)) /* pos 139:17 */;
		echo '
                <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/extension/update_core'))) /* pos 140:28 */;
		echo ' title="" class="btnIconLeft mr10 mt5 api-link" data-api-confirm="Make sure that you have made database and files backups before proceeding with automatic update. Click OK when you are ready to continue." data-api-msg="Update complete"><img src="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 140:314 */;
		echo 'images/icons/dark/cog.png" alt="" class="icon"><span>Update OHMS</span></a>
            </div>

            <div class="help">
                <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manual update')) /* pos 144:21 */;
		echo '</h3>
                <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manual update is a solution when auto updater can not work on current installation environment')) /* pos 145:20 */;
		echo '</p>
            </div>

            <div class="body list arrowGreen">
                <ul>
                    <li>Download the latest release from <a href="https://github.com/OHMS/OHMS/releases" target="_blank">GitHub</a></li>
                    <li>Extract the files into your computer</li>
                    <li>Upload (overwrite) extracted files via FTP to <strong>';
		echo LR\HtmlHelpers::escapeText(constant('PS_PATH_ROOT')) /* pos 152:79 */;
		echo '</strong></li>
                    <li>When the uploading is done, execute <a href="';
		echo LR\HtmlHelpers::escapeAttr(constant('PS_URL')) /* pos 153:70 */;
		echo 'update.php" target="_blank">';
		echo LR\HtmlHelpers::escapeText(constant('PS_URL')) /* pos 153:118 */;
		echo 'update.php</a> in your browser</li>
                    <li>Your OHMS is now updated to latest version.</li>
                </ul>
            </div>
        </div>
        
        <div class="tab_content nopadding" id="tab-about">
            <div class="help">
                <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Extending OHMS')) /* pos 161:21 */;
		echo '</h3>
                <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('OHMS gives developers all the capabilities to customize, integrate & extend the core system into your own website & applications.')) /* pos 162:20 */;
		echo '</p>
            </div>
            <div class="body">
                <h2 class="pt20">More extensions</h2>
                <p>If you can not find extensions you are looking for in this admin area, please visit extensions site at <a href="http://extensions.OHMS.org" target="_blank">http://extensions.OHMS.org</a></p>

                <h2 class="pt20">How to create new extension</h2>
                <div class="pt20 list arrowGrey">
                    <ul>
                        <li>Create free account at <a href="https://github.com/signup/free" target="_blank">Github</a></li>
                        <li>Create new public repository dedicated for extension only</li>
                        <li>Repository must have plugin json file. <a href="http://extensions.OHMS.org/article/getting-started" target="_blank">More information</a></li>
                        <li>Login to <a href="http://extensions.OHMS.org/" target="_blank">OHMS extensions site</a> with github account.</li>
                        <li>If your repository contains valid json file, it can be registered in extensions site.</li>
                        <li>Registered extensions can be visible in every OHMS admin area.</li>
                    </ul>
                </div>

                <h2 class="pt20">Supported extension types</h2>
                <div class="pt20 list arrowGrey">
                    <ul>
                        <li>Payment gateways</li>
                        <li>Server managers</li>
                        <li>Domain registrars</li>
                        <li>Client area themes</li>
                        <li>Admin area themes</li>
                        <li>Translations for client and admin areas</li>
                        <li>Event hooks - Hooks can be injected into the process, change its behaviour, stop executing actions</li>
                        <li>API module - External program which uses OHMS API</li>
                    </ul>
                </div>

                <h2 class="pt20">Extension support</h2>
                <p>Contact extensions developers directly for support. You can find issue tracker on extension site.</p>
            </div>
        </div>
    </div>
</div>
';
	}


	/** {block js} on line 202 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script type="text/javascript">
    var extensionAdminBaseUrl = ';
		echo LR\HtmlHelpers::convertJSToRawText(json_encode(($this->filters->alink)('') . '/')) /* pos 204:33 */;
		echo ';
    var extensionSettingsBaseUrl = ';
		echo LR\HtmlHelpers::convertJSToRawText(json_encode(($this->filters->alink)('extension/settings') . '/')) /* pos 205:36 */;
		echo ';

    function onAfterUpdate(result) {
    
    }

    function onAfterModuleActivated(result) {
        if(result.redirect && result.type == \'mod\') {
            bb.redirect(extensionAdminBaseUrl + result.id);
        } else if(result.has_settings) {
            bb.redirect(extensionSettingsBaseUrl + result.id);
        } else {
            bb.reload();
        }
    }
</script>
';
	}
}
