<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html\mod_product_category.latte */
final class Template_4e6bc54173 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'breadcrumbs' => 'blockBreadcrumbs', 'content' => 'blockContent', 'head' => 'blockHead', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 28:1 */;
		echo '

';
		$this->renderBlock('breadcrumbs', get_defined_vars()) /* pos 30:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 39:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 81:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 83:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 24:1 */;
		$active_menu = 'products' /* pos 26:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 28 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText($category['title']) /* pos 28:19 */;
	}


	/** {block breadcrumbs} on line 30 */
	public function blockBreadcrumbs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<ul>
    <li class="firstB"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('/'))) /* pos 32:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 32:47 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('product'))) /* pos 33:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products')) /* pos 33:36 */;
		echo '</a></li>
    <li><a href="';
		echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('product')) /* pos 34:18 */;
		echo '#tab-categories">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Categories')) /* pos 34:51 */;
		echo '</a></li>
    <li class="lastB">';
		echo LR\HtmlHelpers::escapeText($category['title']) /* pos 35:23 */;
		echo '</li>
</ul>
';
	}


	/** {block content} on line 39 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget">
    <div class="head">
        <h5>';
		echo LR\HtmlHelpers::escapeText($category['title']) /* pos 42:13 */;
		echo '</h5>
    </div>
    
    <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/category_update'))) /* pos 45:35 */;
		echo ' class="mainForm save api-form"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('Category updated')) /* pos 45:125 */;
		echo '>
        <fieldset>
            <div class="rowElem noborder">
                <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Title')) /* pos 48:24 */;
		echo ':</label>
                <div class="formRight">
                    <input type="text" name="title"';
		echo LR\HtmlHelpers::formatAttribute(' value', $category['title']) /* pos 50:61 */;
		echo ' required="required"/>
                </div>
                <div class="fix"></div>
            </div>
            
            <div class="rowElem">
                <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Icon')) /* pos 56:24 */;
		echo ':</label>
                <div class="formRight">
                    <input type="text" name="icon_url" id="bb-icon"';
		echo LR\HtmlHelpers::formatAttribute(' value', $category['icon_url']) /* pos 58:77 */;
		echo ' style="width: 80%"/>
                    <input type="button"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Browse')) /* pos 59:51 */;
		echo ' class="bHtml blueBtn button"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-browser-url', ($this->filters->alink)('filemanager/icons')) /* pos 59:115 */;
		echo LR\HtmlHelpers::formatDataAttribute(' data-browser-title', ($this->filters->trans)('Select icon and click OK')) /* pos 59:165 */;
		echo ' />
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Orderform')) /* pos 65:24 */;
		echo ':</label>
                <div class="formRight">
';
		$this->renderBlock('selectbox', ['orderform_code', $admin->theme_orderform_get_pairs, $category['orderform_code'], 0, 'Use theme default'] + [], 'html') /* pos 67:21 */;
		echo '                </div>
                <div class="fix"></div>
            </div>

            <textarea name="description" cols="5" rows="20" class="bb-textarea">';
		echo LR\HtmlHelpers::escapeText($category['description']) /* pos 72:81 */;
		echo '</textarea>

            <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Update')) /* pos 74:43 */;
		echo ' class="greyishBtn submitForm" />
            <input type="hidden" name="id"';
		echo LR\HtmlHelpers::formatAttribute(' value', $category['id']) /* pos 75:52 */;
		echo '/>
        </fieldset>
    </form>
</div>
';
	}


	/** {block head} on line 81 */
	public function blockHead(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('bb_editor', ['.bb-textarea'] + [], 'html') /* pos 81:13 */;
	}


	/** {block js} on line 83 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script type="text/javascript">
    $(function() {
        $(".bHtml").click( function() {
            jAlert(bb.load($(this).data(\'browser-url\'), { rel: "bb-icon" }), $(this).data(\'browser-title\'));
        });
    });
</script>
';
	}
}
