<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html\mod_system_index.latte */
final class Template_07cac7ef0c extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 25:1 */;
		echo '

';
		$active_menu = 'system' /* pos 27:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 29:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['extension' => '141'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 23:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 25 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 25:19 */;
	}


	/** {block content} on line 29 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$request_data = $request->get() /* pos 30:1 */;
		$extensions = (array) $admin->extension_get_list(array_merge(['active' => 1, 'has_settings' => 1], $request_data)) /* pos 31:1 */;
		$extension_ids = array_column($extensions, 'id') /* pos 32:1 */;
		$has_product_addons_access = $admin->system_is_allowed(['mod' => 'product']) /* pos 33:1 */;
		$extra_settings_count = (!in_array('ipban', $extension_ids, true) ? 1 : 0) + (!in_array('frauddetector', $extension_ids, true) ? 1 : 0) /* pos 34:1 */;
		$settings_count = ($this->filters->length)($extensions) + ($has_product_addons_access ? 1 : 0) + $extra_settings_count /* pos 35:1 */;
		echo '<div class="widget">
    <div class="body">
        <div class="admin-settings-hub">
            <aside class="admin-settings-sidebar">
                <div class="admin-settings-sidebar-card admin-settings-search">
                    <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Search settings')) /* pos 41:27 */;
		echo '</span>
                    <input type="search"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->search) /* pos 42:50 */;
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Search modules, integrations, or tools')) /* pos 42:84 */;
		echo ' data-settings-search />
                </div>

                <div class="admin-settings-sidebar-card">
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Filter groups')) /* pos 46:25 */;
		echo '</h4>
                    <div class="admin-settings-filter-list">
                        <button type="button" class="admin-settings-filter is-active" data-settings-filter="all">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('All settings')) /* pos 48:114 */;
		echo '</button>
                        <button type="button" class="admin-settings-filter" data-settings-filter="applications">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Applications')) /* pos 49:113 */;
		echo '</button>
                        <button type="button" class="admin-settings-filter" data-settings-filter="commerce">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Commerce')) /* pos 50:109 */;
		echo '</button>
                        <button type="button" class="admin-settings-filter" data-settings-filter="addons">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Addons')) /* pos 51:107 */;
		echo '</button>
                        <button type="button" class="admin-settings-filter" data-settings-filter="appearance">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Appearance')) /* pos 52:111 */;
		echo '</button>
                        <button type="button" class="admin-settings-filter" data-settings-filter="other">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Other')) /* pos 53:106 */;
		echo '</button>
                    </div>
                </div>

                <div class="admin-settings-sidebar-card">
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Environment')) /* pos 58:25 */;
		echo '</h4>
                    <dl class="admin-settings-summary">
                        <div>
                            <dt>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Admin theme')) /* pos 61:33 */;
		echo '</dt>
                            <dd>';
		echo LR\HtmlHelpers::escapeText($theme['code'] ?? 'admin_default') /* pos 62:33 */;
		echo '</dd>
                        </div>
                        <div>
                            <dt>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Configurable areas')) /* pos 65:33 */;
		echo '</dt>
                            <dd>';
		echo LR\HtmlHelpers::escapeText($settings_count) /* pos 66:33 */;
		echo '</dd>
                        </div>
                        <div>
                            <dt>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Language')) /* pos 69:33 */;
		echo '</dt>
                            <dd>';
		echo LR\HtmlHelpers::escapeText($lang) /* pos 70:33 */;
		echo '</dd>
                        </div>
                    </dl>
                </div>
            </aside>

            <div class="admin-settings-main">
                <div class="admin-settings-toolbar">
                    <div>
                        <span class="admin-section-kicker">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Administration settings')) /* pos 79:60 */;
		echo '</span>
                        <h2>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Dense control panel for system configuration')) /* pos 80:29 */;
		echo '</h2>
                        <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every settings page, extension entry point, and existing route remains intact. Use search or the category filters to narrow the list.')) /* pos 81:28 */;
		echo '</p>
                    </div>
                    <span class="admin-settings-count" data-settings-count>';
		echo LR\HtmlHelpers::escapeText($settings_count) /* pos 83:76 */;
		echo ' areas</span>
                </div>

                <div class="admin-settings-grid" data-settings-grid>
';
		if ($has_product_addons_access) /* pos 87:21 */ {
			echo '                    <a';
			echo LR\HtmlHelpers::formatAttribute('
                        href', ($this->filters->checkUrl)(($this->filters->alink)('product/addons'))) /* pos 89:33 */;
			echo '
                        class="admin-settings-card"
                        data-settings-card
                        data-settings-group="commerce"
                        data-settings-search="product addons upsells order options pricing commerce products sellable addons"
                    >
                        <span class="admin-settings-card-icon">
                            <strong>PA</strong>
                        </span>
                        <span class="admin-settings-card-tag">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Commerce')) /* pos 98:63 */;
			echo '</span>
                        <strong class="admin-settings-card-title">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Product addons')) /* pos 99:67 */;
			echo '</strong>
                        <span class="admin-settings-card-description">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manage sellable product add-ons and jump directly into addon creation. This is separate from addon modules.')) /* pos 100:71 */;
			echo '</span>
                        <span class="admin-settings-card-meta">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Commerce workspace')) /* pos 101:64 */;
			echo '</span>
                    </a>
';
		}
		echo "\n";
		if (!in_array('ipban', $extension_ids, true)) /* pos 105:21 */ {
			echo '                    <a';
			echo LR\HtmlHelpers::formatAttribute('
                        href', ($this->filters->checkUrl)(($this->filters->alink)('extension/settings/ipban'))) /* pos 107:33 */;
			echo '
                        class="admin-settings-card"
                        data-settings-card
                        data-settings-group="other"
                        data-settings-search="ip ban security blocked ips wildcard cidr abuse access control"
                    >
                        <span class="admin-settings-card-icon">
                            <strong>IP</strong>
                        </span>
                        <span class="admin-settings-card-tag">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Other')) /* pos 116:63 */;
			echo '</span>
                        <strong class="admin-settings-card-title">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('IP ban')) /* pos 117:67 */;
			echo '</strong>
                        <span class="admin-settings-card-description">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Block exact IPs, wildcard ranges, and CIDR ranges before login, signup, checkout, and public ticket creation.')) /* pos 118:71 */;
			echo '</span>
                        <span class="admin-settings-card-meta">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Security control')) /* pos 119:64 */;
			echo '</span>
                    </a>
';
		}
		echo "\n";
		if (!in_array('frauddetector', $extension_ids, true)) /* pos 123:21 */ {
			echo '                    <a';
			echo LR\HtmlHelpers::formatAttribute('
                        href', ($this->filters->checkUrl)(($this->filters->alink)('extension/settings/frauddetector'))) /* pos 125:33 */;
			echo '
                        class="admin-settings-card"
                        data-settings-card
                        data-settings-group="other"
                        data-settings-search="fraud detector security signup checkout ticket screening risk scoring abuse"
                    >
                        <span class="admin-settings-card-icon">
                            <strong>FD</strong>
                        </span>
                        <span class="admin-settings-card-tag">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Other')) /* pos 134:63 */;
			echo '</span>
                        <strong class="admin-settings-card-title">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Fraud detector')) /* pos 135:67 */;
			echo '</strong>
                        <span class="admin-settings-card-description">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Apply email-domain rules and rate limits to signups, public tickets, and checkout attempts, then review the decision log.')) /* pos 136:71 */;
			echo '</span>
                        <span class="admin-settings-card-meta">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Security control')) /* pos 137:64 */;
			echo '</span>
                    </a>
';
		}
		echo "\n";
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($extensions, $ʟ_it ?? null) as $extension) /* pos 141:21 */ {
			$ext_type = (string) ($extension['type'] ?? 'mod') /* pos 142:25 */;
			$settings_group = 'other' /* pos 143:25 */;
			$card_title = (string) ($extension['name'] ?? '') /* pos 144:25 */;
			$card_description = (string) ($extension['description'] ?? 'Settings for ' . ($extension['name'] ?? 'module')) /* pos 145:25 */;
			$card_meta = str_replace('-', ' ', $ext_type) /* pos 146:25 */;
			if (($extension['id'] ?? '') == 'addons') /* pos 147:25 */ {
				$settings_group = 'addons' /* pos 148:29 */;
				$card_title = 'Addon modules' /* pos 149:29 */;
				$card_description = 'Manage addon modules and module setup docs. This is separate from sellable product add-ons.' /* pos 150:29 */;
				$card_meta = 'Module workspace' /* pos 151:29 */;
			} elseif ($ext_type == 'mod') /* pos 152:25 */ {
				$settings_group = 'applications' /* pos 153:29 */;
			} elseif (str_contains($ext_type, 'gateway') || str_contains($ext_type, 'registrar') || str_contains($ext_type, 'currency')) /* pos 154:25 */ {
				$settings_group = 'commerce' /* pos 155:29 */;
			} elseif (str_contains($ext_type, 'theme')) /* pos 156:25 */ {
				$settings_group = 'appearance' /* pos 157:29 */;
			}



			$search_text = ($extension['name'] ?? '') . ' ' . ($extension['description'] ?? '') . ' ' . $ext_type . (($extension['id'] ?? '') == 'addons' ? ' addon modules extensions developer custom modules' : '') /* pos 159:25 */;
			echo '                        <a
                            href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('extension/settings')) /* pos 161:35 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($extension['id']) /* pos 161:65 */;
			echo '"
                            class="admin-settings-card"
                            data-settings-card';
			echo LR\HtmlHelpers::formatDataAttribute('
                            data-settings-group', $settings_group) /* pos 164:51 */;
			echo LR\HtmlHelpers::formatDataAttribute('
                            data-settings-search', $search_text) /* pos 165:52 */;
			echo '
                        >
                            <span class="admin-settings-card-icon">
';
			if ($extension['icon_url'] ?? false) /* pos 168:33 */ {
				echo '                                    <img';
				echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($extension['icon_url'])) /* pos 169:48 */;
				echo LR\HtmlHelpers::formatAttribute(' alt', $extension['name'] ?? $extension['id']) /* pos 169:79 */;
				echo ' />
';
			} else /* pos 170:33 */ {
				echo '                                    <strong>';
				echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($extension['name'], 1, false, '')) /* pos 171:45 */;
				echo '</strong>
';
			}
			echo '                            </span>
                            <span class="admin-settings-card-tag">';
			echo LR\HtmlHelpers::escapeText(($this->filters->capitalize)($settings_group)) /* pos 174:67 */;
			echo '</span>
                            <strong class="admin-settings-card-title">';
			echo LR\HtmlHelpers::escapeText($card_title) /* pos 175:71 */;
			echo '</strong>
                            <span class="admin-settings-card-description">';
			echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($card_description, 120)) /* pos 176:75 */;
			echo '</span>
                            <span class="admin-settings-card-meta">';
			echo LR\HtmlHelpers::escapeText($card_meta) /* pos 177:68 */;
			echo '</span>
                        </a>
';
		}
		if ($iterator->isEmpty()) /* pos 179:21 */ {
			echo '                        <div class="admin-settings-empty is-visible">
                            <strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No configurable extensions available.')) /* pos 181:37 */;
			echo '</strong>
                            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Activate modules with settings pages to see them here.')) /* pos 182:35 */;
			echo '</span>
                        </div>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '                </div>

                <div class="admin-settings-empty" data-settings-empty>
                    <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No settings matched the current filters.')) /* pos 188:29 */;
		echo '</strong>
                    <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Adjust the search or switch to another category.')) /* pos 189:27 */;
		echo '</span>
                </div>
            </div>
        </div>
    </div>
</div>
';
	}
}
