<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html\mod_product_index.latte */
final class Template_89e89ed6c3 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 28:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 30:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 186:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['product_row' => '59', 'cat_id' => '166', 'cat_title' => '166'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 24:1 */;
		$active_menu = 'product' /* pos 26:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 28 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products')) /* pos 28:19 */;
	}


	/** {block content} on line 30 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget simpleTabs">
    <ul class="tabs">
        <li><a href="#tab-index">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products')) /* pos 33:34 */;
		echo '</a></li>
        <li><a href="#tab-new">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('New product')) /* pos 34:32 */;
		echo '</a></li>
        <li><a href="#tab-new-category">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('New category')) /* pos 35:41 */;
		echo '</a></li>
        <li><a href="#tab-categories">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manage categories')) /* pos 36:39 */;
		echo '</a></li>
        <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('product/options'))) /* pos 37:24 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Configurable options')) /* pos 37:50 */;
		echo '</a></li>
    </ul>

    <div class="tabs_container">
        <div class="fix"></div>
        <div class="tab_content nopadding" id="tab-index">
';
		$this->renderBlock('table_search', [], 'html') /* pos 43:13 */;
		echo '            <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/update_priority'))) /* pos 44:43 */;
		echo ' class="mainForm api-form" data-api-reload="1">
                <fieldset>
                    <table class="tableStatic wide">
                        <thead>
                            <tr>
                                <td width="50%">Title</td>
                                <td>Status</td>
                                <td>Category</td>
                                <td width="10%">Type</td>
                                <td style="width: 5%">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Priority')) /* pos 53:55 */;
		echo '</td>
                                <td width="13%">&nbsp;</td>
                            </tr>
                        </thead>
                        <tbody>
';
		$products = $admin->product_get_list(array_merge(['per_page' => 30, 'page' => $request->page], $request->get())) /* pos 58:29 */;
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($products->list, $ʟ_it ?? null) as $product_row) /* pos 59:29 */ {
			echo '                            <tr>
                                <td><a href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('product/manage')) /* pos 61:46 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($product_row['id']) /* pos 61:72 */;
			echo '">';
			echo LR\HtmlHelpers::escapeText($product_row['title']) /* pos 61:94 */;
			echo '</a></td>
                                <td>';
			$this->renderBlock('status_name', [$product_row['status']] + [], 'html') /* pos 62:37 */;
			echo '</td>
                                <td><a href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('/product/category')) /* pos 63:46 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($product_row['category']['id']) /* pos 63:75 */;
			echo '">';
			echo LR\HtmlHelpers::escapeText($product_row['category']['title']) /* pos 63:109 */;
			echo '</a></td>
                                <td>';
			$this->renderBlock('status_name', [$product_row['type']] + [], 'html') /* pos 64:37 */;
			echo '</td>
                                <td><input type="text" name="priority[';
			echo LR\HtmlHelpers::escapeAttr($product_row['id']) /* pos 65:71 */;
			echo ']"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product_row['priority']) /* pos 65:102 */;
			echo ' style="width:30px;"></td>
                                <td class="actions">
                                    <a class="bb-button btn14" href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('product/manage')) /* pos 67:70 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($product_row['id']) /* pos 67:96 */;
			echo '"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 67:128 */;
			echo 'images/icons/dark/pencil.png" alt=""></a>
                                    <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="Are you sure?"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/delete', ['id' => $product_row['id']]))) /* pos 68:123 */;
			echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->alink)('product')) /* pos 68:207 */;
			echo '><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 68:235 */;
			echo 'images/icons/dark/trash.png" alt=""></a>
                                </td>
                            </tr>
';
		}
		if ($iterator->isEmpty()) /* pos 71:29 */ {
			echo '                            <tr>
                                <td colspan="6">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('The list is empty')) /* pos 73:49 */;
			echo '</td>
                            </tr>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '                        </tbody>
                    </table>
                
';
		$this->createTemplate('partial_pagination.latte', ['list' => $products, 'url' => 'product'] + $this->params, 'include')->renderToContentType('html') /* pos 79:21 */;
		echo '            
                    <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Update priority')) /* pos 81:51 */;
		echo ' class="greyishBtn submitForm" />
                </fieldset>
            </form>
        </div>

        <div class="tab_content nopadding" id="tab-new">
            <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/prepare'))) /* pos 87:43 */;
		echo ' class="mainForm" id="prepare-product" data-product-manage-url="';
		echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('product/manage')) /* pos 87:141 */;
		echo '/">
                <fieldset>
                    <div class="rowElem noborder">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Type')) /* pos 90:32 */;
		echo ':</label>
                        <div class="formRight">
';
		$this->renderBlock('selectbox', ['type', $admin->product_get_types, $request->type, 1] + [], 'html') /* pos 92:29 */;
		echo '                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Category')) /* pos 97:32 */;
		echo ':</label>
                        <div class="formRight">
';
		$this->renderBlock('selectbox', ['product_category_id', $admin->product_category_get_pairs, $request->product_category_id, 1] + [], 'html') /* pos 99:29 */;
		echo '                        </div>
                        <div class="fix"></div>
                    </div>
                    <div class="rowElem">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Title')) /* pos 104:32 */;
		echo ':</label>
                        <div class="formRight">
                            <input type="text" name="title"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->title) /* pos 106:69 */;
		echo ' required="required" placeholder=""/>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Create')) /* pos 111:51 */;
		echo ' class="greyishBtn submitForm" />
                </fieldset>
            </form>

            <div class="fix"></div>
        </div>

        <div class="tab_content nopadding" id="tab-new-category">

            <div class="help">
                <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create product category')) /* pos 121:21 */;
		echo '</h3>
                <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Title, image URL, and description are all supported here.')) /* pos 122:20 */;
		echo '</p>
            </div>
            <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/category_create'))) /* pos 124:43 */;
		echo ' class="mainForm save api-form"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->alink)('product')) /* pos 124:138 */;
		echo '>
                <fieldset>
                    <div class="rowElem noborder">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Title')) /* pos 127:32 */;
		echo ':</label>
                        <div class="formRight">
                            <input type="text" name="title"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->cat_title) /* pos 129:69 */;
		echo ' required="required"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Shared hosting')) /* pos 129:126 */;
		echo '/>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <div class="rowElem">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Icon URL')) /* pos 135:32 */;
		echo ':</label>
                        <div class="formRight">
                            <input type="text" name="icon_url"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->icon_url) /* pos 137:72 */;
		echo ' placeholder="https://example.com/icon.png"/>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <div class="rowElem">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Description')) /* pos 143:32 */;
		echo ':</label>
                        <div class="formRight">
                            <textarea name="description" cols="5" rows="4"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Short category description shown on order pages')) /* pos 145:91 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText($request->cat_description) /* pos 145:149 */;
		echo '</textarea>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <div class="rowElem">
                        <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Orderform')) /* pos 151:32 */;
		echo ':</label>
                        <div class="formRight">
';
		$this->renderBlock('selectbox', ['orderform_code', $admin->theme_orderform_get_pairs, $request->orderform_code, 0, 'Use theme default'] + [], 'html') /* pos 153:29 */;
		echo '                        </div>
                        <div class="fix"></div>
                    </div>

                    <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Create')) /* pos 158:51 */;
		echo ' class="greyishBtn submitForm" />
                </fieldset>
            </form>
        </div>

        <div class="tab_content nopadding" id="tab-categories">
            <table class="tableStatic wide">
                <tbody>
';
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($admin->product_category_get_pairs, $ʟ_it ?? null) as $cat_id => $cat_title) /* pos 166:21 */ {
			echo '                    <tr ';
			if ($iterator->first) /* pos 167:25 */ {
				echo 'class="noborder"';
			}
			echo '>
                        <td>';
			echo LR\HtmlHelpers::escapeText($cat_title) /* pos 168:29 */;
			echo '</td>
                        <td class="actions" style="width:13%">
                            <a class="bb-button btn14" href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('/product/category')) /* pos 170:62 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($cat_id) /* pos 170:91 */;
			echo '"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 170:112 */;
			echo 'images/icons/dark/pencil.png" alt=""></a>
                            <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="Are you sure?"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/category_delete', ['id' => $cat_id]))) /* pos 171:115 */;
			echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->alink)('product')) /* pos 171:197 */;
			echo '><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 171:225 */;
			echo 'images/icons/dark/trash.png" alt=""></a>
                        </td>
                    </tr>
';
		}
		if ($iterator->isEmpty()) /* pos 174:21 */ {
			echo '                    <tr>
                        <td colspan="3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('The list is empty')) /* pos 176:41 */;
			echo '</td>
                    </tr>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '                </tbody>
            </table>
        </div>
    </div>
</div>
';
	}


	/** {block js} on line 186 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script>
    $(function() {
        $(\'#prepare-product\').bind(\'submit\', function(){
            var form = $(this);

            bb.post(
                form.attr(\'action\'),
                form.serialize(),
                function(result) {
                    bb.redirect(form.data(\'product-manage-url\') + result);
                }
            );
            
            return false;
        });
    });
</script>
';
	}
}
