<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/macro_functions.latte */
final class Template_8dd360ef7a extends Latte\Runtime\Template
{
	public const Blocks = [
		['q' => 'blockQ', 'selectbox' => 'blockSelectbox', 'selectboxtld' => 'blockSelectboxtld', 'table_search' => 'blockTable_search', 'build_form' => 'blockBuild_form', 'currency_format' => 'blockCurrency_format', 'currency' => 'blockCurrency', 'status_name' => 'blockStatus_name', 'period_name' => 'blockPeriod_name', 'markdown_quote' => 'blockMarkdown_quote', 'bb_editor' => 'blockBb_editor'],
	];


	public function main(array $ʟ_args): void
	{
		echo '











';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['val' => '33', 'label' => '33', 'data' => '41', 'name' => '61', 'element' => '61', 'k' => '70, 79', 'v' => '70, 79', 'line' => '150'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {define q, $bool} on line 22 */
	public function blockQ(array $ʟ_args): void
	{
		extract($this->params);
		$bool = $ʟ_args[0] ?? $ʟ_args['bool'] ?? null;
		unset($ʟ_args);

		if ($bool) /* pos 23:1 */ {
			echo '    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Yes')) /* pos 24:5 */;
			echo "\n";
		} else /* pos 25:1 */ {
			echo '    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No')) /* pos 26:5 */;
			echo "\n";
		}
	}


	/** {define selectbox, $name, $options, $selected, $required, $nullOption} on line 30 */
	public function blockSelectbox(array $ʟ_args): void
	{
		extract($this->params);
		$name = $ʟ_args[0] ?? $ʟ_args['name'] ?? null;
		$options = $ʟ_args[1] ?? $ʟ_args['options'] ?? null;
		$selected = $ʟ_args[2] ?? $ʟ_args['selected'] ?? null;
		$required = $ʟ_args[3] ?? $ʟ_args['required'] ?? null;
		$nullOption = $ʟ_args[4] ?? $ʟ_args['nullOption'] ?? null;
		unset($ʟ_args);

		echo '    <select';
		echo LR\HtmlHelpers::formatAttribute(' name', $name) /* pos 31:20 */;
		echo LR\HtmlHelpers::formatAttribute(' id', $name) /* pos 31:33 */;
		echo ' ';
		if ($required) /* pos 31:41 */ {
			echo 'required="required"';
		}
		echo '>
';
		if ($nullOption) /* pos 32:9 */ {
			echo '        <option value="">-- ';
			echo LR\HtmlHelpers::escapeText($nullOption) /* pos 32:45 */;
			echo ' --</option>';
		}
		echo "\n";
		foreach ($options ?? [] as $val => $label) /* pos 33:9 */ {
			echo '        <option';
			echo LR\HtmlHelpers::formatAttribute(' value', $val) /* pos 34:25 */;
			echo LR\HtmlHelpers::formatAttribute(' label', $label) /* pos 34:40 */;
			echo ' ';
			if ($selected == $val) /* pos 34:49 */ {
				echo 'selected="selected"';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText($label) /* pos 34:98 */;
			echo '</option>
';

		}

		echo '    </select>
';
	}


	/** {define selectboxtld, $name, $options, $selected, $required} on line 39 */
	public function blockSelectboxtld(array $ʟ_args): void
	{
		extract($this->params);
		$name = $ʟ_args[0] ?? $ʟ_args['name'] ?? null;
		$options = $ʟ_args[1] ?? $ʟ_args['options'] ?? null;
		$selected = $ʟ_args[2] ?? $ʟ_args['selected'] ?? null;
		$required = $ʟ_args[3] ?? $ʟ_args['required'] ?? null;
		unset($ʟ_args);

		echo '    <select';
		echo LR\HtmlHelpers::formatAttribute(' name', $name) /* pos 40:20 */;
		echo ' ';
		if ($required) /* pos 40:28 */ {
			echo 'required="required"';
		}
		echo ' style="width:80px;">
';
		foreach ($options ?? [] as $data) /* pos 41:9 */ {
			echo '        <option';
			echo LR\HtmlHelpers::formatAttribute(' value', $data->tld) /* pos 42:25 */;
			echo LR\HtmlHelpers::formatAttribute(' label', $data->tld) /* pos 42:46 */;
			echo ' ';
			if ($selected == $data->tld) /* pos 42:59 */ {
				echo 'selected="selected"';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText($data->tld) /* pos 42:114 */;
			echo '</option>
';

		}

		echo '    </select>
';
	}


	/** {define table_search} on line 47 */
	public function blockTable_search(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div style="position: relative;">
    <div class="dataTables_filter">
        <form method="get" action="">
            <input type="hidden" name="_url"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->_url) /* pos 51:54 */;
		echo '/>
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Search:')) /* pos 52:20 */;
		echo ' <input type="text" name="search"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Enter search text..')) /* pos 52:87 */;
		echo LR\HtmlHelpers::formatAttribute(' value', $request->search) /* pos 52:125 */;
		echo '>
                <div class="srch"></div>
            </label>
        </form>
    </div>
</div>
';
	}


	/** {define build_form, $elements, $values} on line 60 */
	public function blockBuild_form(array $ʟ_args): void
	{
		extract($this->params);
		$elements = $ʟ_args[0] ?? $ʟ_args['elements'] ?? null;
		$values = $ʟ_args[1] ?? $ʟ_args['values'] ?? null;
		unset($ʟ_args);

		foreach ($elements as $name => $element) /* pos 61:5 */ {
			$element_meta = $element[1] ?? null /* pos 62:5 */;
			$element_label = is_object($element_meta) ? $element_meta->label ?? '' : $element_meta['label'] ?? '' /* pos 63:5 */;
			$element_desc = is_object($element_meta) ? $element_meta->description ?? null : $element_meta['description'] ?? null /* pos 64:5 */;
			echo '    <div class="rowElem">
';
			if ($element[0] == 'select') /* pos 66:13 */ {
				echo '            <label class="topLabel">';
				echo LR\HtmlHelpers::escapeText($element_label) /* pos 67:37 */;
				if ($element_desc) /* pos 67:53 */ {
					echo ' - ';
					echo LR\HtmlHelpers::escapeText($element_desc) /* pos 67:74 */;
				}
				echo '</label>
            <div class="formBottom">
                <select name="config[';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 69:38 */;
				echo ']">
';
				foreach ($element[1]->multiOptions as $k => $v) /* pos 70:17 */ {
					echo '                    <option';
					echo LR\HtmlHelpers::formatAttribute(' value', $k) /* pos 71:37 */;
					echo ' ';
					if ($k == $values->{$name}) /* pos 71:42 */ {
						echo 'selected="selected"';
					}
					echo '></option><label>';
					echo LR\HtmlHelpers::escapeText($v) /* pos 71:104 */;
					echo '</label>
';

				}

				echo '                </select>
            </div>
            <div class="fix"></div>
';
			} elseif ($element[0] == 'radio') /* pos 76:13 */ {
				echo '            <label>';
				echo LR\HtmlHelpers::escapeText($element_label) /* pos 77:20 */;
				if ($element_desc) /* pos 77:36 */ {
					echo ' - ';
					echo LR\HtmlHelpers::escapeText($element_desc) /* pos 77:57 */;
				}
				echo '</label>
            <div class="formRight">
';
				foreach ($element[1]->multiOptions as $k => $v) /* pos 79:17 */ {
					echo '                    <input id="el-';
					echo LR\HtmlHelpers::escapeAttr($name) /* pos 80:35 */;
					echo '" type="radio" name="config[';
					echo LR\HtmlHelpers::escapeAttr($name) /* pos 80:70 */;
					echo ']"';
					echo LR\HtmlHelpers::formatAttribute(' value', $k) /* pos 80:88 */;
					echo ' ';
					if ($k == $values->{$name}) /* pos 80:93 */ {
						echo 'checked="checked"';
					}
					echo '/><label>';
					echo LR\HtmlHelpers::escapeText($v) /* pos 80:153 */;
					echo '</label>
';

				}

				echo '            </div>
            <div class="fix"></div>
';
			} elseif ($element[0] == 'textarea') /* pos 84:13 */ {
				echo '            <label class="topLabel" for="el-';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 85:45 */;
				echo '">';
				echo LR\HtmlHelpers::escapeText($element_label) /* pos 85:54 */;
				if ($element_desc) /* pos 85:70 */ {
					echo ' - ';
					echo LR\HtmlHelpers::escapeText($element_desc) /* pos 85:91 */;
				}
				echo '</label>
            <div class="formBottom">
                <textarea id="el-';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 87:34 */;
				echo '" name="config[';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 87:56 */;
				echo ']" cols="5" rows="20" required="required">';
				echo LR\HtmlHelpers::escapeText($values->{$name}) /* pos 87:105 */;
				echo '</textarea>
            </div>
            <div class="fix"></div>
';
			} else /* pos 90:13 */ {
				echo '            <label class="topLabel" for="el-';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 91:45 */;
				echo '">';
				echo LR\HtmlHelpers::escapeText($element_label) /* pos 91:54 */;
				if ($element_desc) /* pos 91:70 */ {
					echo ' - ';
					echo LR\HtmlHelpers::escapeText($element_desc) /* pos 91:91 */;
				}
				echo '</label>
            <div class="formBottom">
                <input id="el-';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 93:31 */;
				echo '"';
				echo LR\HtmlHelpers::formatAttribute(' type', $element[0]) /* pos 93:47 */;
				echo ' name="config[';
				echo LR\HtmlHelpers::escapeAttr($name) /* pos 93:74 */;
				echo ']"';
				echo LR\HtmlHelpers::formatAttribute(' value', $values->{$name}) /* pos 93:92 */;
				echo ' ';
				if (!isset($element[1]->required) && !$element[1]->required == false) /* pos 93:111 */ {
					echo 'required="required"';
				}
				echo '/>
            </div>
            <div class="fix"></div>
';
			}


			echo '    </div>
';

		}
	}


	/** {define currency_format, $price, $currency} on line 101 */
	public function blockCurrency_format(array $ʟ_args): void
	{
		extract($this->params);
		$price = $ʟ_args[0] ?? $ʟ_args['price'] ?? null;
		$currency = $ʟ_args[1] ?? $ʟ_args['currency'] ?? null;
		unset($ʟ_args);

		$c = $guest->currency_get(['code' => $currency]) /* pos 102:5 */;
		$p = ($this->filters->number)($price) /* pos 103:5 */;
		if ($c->price_format == 1) /* pos 104:5 */ {
			$p = ($this->filters->number)($p, 2, '.', '') /* pos 105:9 */;
		} elseif ($c->price_format == 2) /* pos 106:5 */ {
			$p = ($this->filters->number)($p, 2, '.', ',') /* pos 107:9 */;
		} elseif ($c->price_format == 3) /* pos 108:5 */ {
			$p = ($this->filters->number)($p, 2, ',', '.') /* pos 109:9 */;
		} elseif ($c->price_format == 4) /* pos 110:5 */ {
			$p = ($this->filters->number)($p, 0, '', ',') /* pos 111:9 */;
		} elseif ($c->price_format == 5) /* pos 112:5 */ {
			$p = ($this->filters->number)($p, 0, '', '') /* pos 113:9 */;
		}




		echo '    ';
		echo LR\HtmlHelpers::escapeText(($this->filters->replace)($c->format, ['{{price}}' => $p])) /* pos 115:5 */;
		echo "\n";
	}


	/** {define currency, $price, $currency} on line 118 */
	public function blockCurrency(array $ʟ_args): void
	{
		extract($this->params);
		$price = $ʟ_args[0] ?? $ʟ_args['price'] ?? null;
		$currency = $ʟ_args[1] ?? $ʟ_args['currency'] ?? null;
		unset($ʟ_args);

		if ($currency == null) /* pos 119:5 */ {
			$c = $guest->cart_get_currency() /* pos 120:9 */;
		} else /* pos 121:5 */ {
			$c = $guest->currency_get(['code' => $currency]) /* pos 122:9 */;
		}
		echo "\n";
		$p = $price * $c->conversion_rate /* pos 125:5 */;
		echo '    
';
		if ($c->price_format == 1) /* pos 127:5 */ {
			$p = ($this->filters->number)($p, 2, '.', '') /* pos 128:9 */;
		} elseif ($c->price_format == 2) /* pos 129:5 */ {
			$p = ($this->filters->number)($p, 2, '.', ',') /* pos 130:9 */;
		} elseif ($c->price_format == 3) /* pos 131:5 */ {
			$p = ($this->filters->number)($p, 2, ',', '.') /* pos 132:9 */;
		} elseif ($c->price_format == 4) /* pos 133:5 */ {
			$p = ($this->filters->number)($p, 0, '', ',') /* pos 134:9 */;
		} elseif ($c->price_format == 5) /* pos 135:5 */ {
			$p = ($this->filters->number)($p, 0, '', '') /* pos 136:9 */;
		}




		echo '    
    ';
		echo LR\HtmlHelpers::escapeText(($this->filters->replace)($c->format, ['{{price}}' => $p])) /* pos 139:5 */;
		echo "\n";
	}


	/** {define status_name, $status} on line 142 */
	public function blockStatus_name(array $ʟ_args): void
	{
		extract($this->params);
		$status = $ʟ_args[0] ?? $ʟ_args['status'] ?? null;
		unset($ʟ_args);

		if ($status) /* pos 142:30 */ {
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)(($this->filters->capitalize)(($this->filters->replace)($status, ['_' => ' '])))) /* pos 142:42 */;
		} else /* pos 142:89 */ {
			echo '-';
		}
	}


	/** {define period_name, $period} on line 144 */
	public function blockPeriod_name(array $ʟ_args): void
	{
		extract($this->params);
		$period = $ʟ_args[0] ?? $ʟ_args['period'] ?? null;
		unset($ʟ_args);

		echo '    ';
		echo LR\HtmlHelpers::escapeText($guest->system_period_title(['code' => $period])) /* pos 145:5 */;
		echo "\n";
	}


	/** {define markdown_quote, $text} on line 148 */
	public function blockMarkdown_quote(array $ʟ_args): void
	{
		extract($this->params);
		$text = $ʟ_args[0] ?? $ʟ_args['text'] ?? null;
		unset($ʟ_args);

		echo "\n";
		foreach (($this->filters->split)($text ?? '', '
') as $line) /* pos 150:1 */ {
			echo '> ';
			echo LR\HtmlHelpers::escapeText($line) /* pos 151:3 */;
			echo "\n";

		}
	}


	/** {define bb_editor, $selector} on line 155 */
	public function blockBb_editor(array $ʟ_args): void
	{
		extract($this->params);
		$selector = $ʟ_args[0] ?? $ʟ_args['selector'] ?? null;
		unset($ʟ_args);

		if ($guest->extension_is_on(['mod' => 'wysiwyg'])) /* pos 156:1 */ {
			$this->createTemplate('mod_wysiwyg_js.latte', ['class' => ($this->filters->trim)($selector ?? '', '.#')] + $this->params, 'include')->renderToContentType('html') /* pos 157:1 */;
		} else /* pos 158:1 */ {
			echo '<!-- No WYSIWYG, no fancy stuff. Enable the WYSIWYG extension for a better management experience. -->
';
		}
	}
}
