<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html\mod_product_addons.latte */
final class Template_16eedd8ab2 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'breadcrumbs' => 'blockBreadcrumbs', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('meta_title', get_defined_vars()) /* pos 24:1 */;
		echo '

';
		$this->renderBlock('breadcrumbs', get_defined_vars()) /* pos 26:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 34:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 122:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['addon_id' => '48', 'addon_title' => '48'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout_default.latte';
		$active_menu = 'products' /* pos 23:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 24 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Addons')) /* pos 24:19 */;
	}


	/** {block breadcrumbs} on line 26 */
	public function blockBreadcrumbs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<ul>
    <li class="firstB"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('/'))) /* pos 28:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 28:47 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('product'))) /* pos 29:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products')) /* pos 29:36 */;
		echo '</a></li>
    <li class="lastB">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Addons')) /* pos 30:23 */;
		echo '</li>
</ul>
';
	}


	/** {block content} on line 34 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget simpleTabs">
    <ul class="tabs">
        <li><a href="#tab-index">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Addons')) /* pos 37:34 */;
		echo '</a></li>
        <li><a href="#tab-new">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('New Addon')) /* pos 38:32 */;
		echo '</a></li>
    </ul>

    <div class="tabs_container">

        <div class="fix"></div>
        <div class="tab_content nopadding" id="tab-index">

            <table class="tableStatic wide">
                <tbody>
';
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($admin->product_addon_get_pairs, $ʟ_it ?? null) as $addon_id => $addon_title) /* pos 48:21 */ {
			echo '                    <tr ';
			if ($iterator->first) /* pos 49:25 */ {
				echo 'class="noborder"';
			}
			echo '>
                        <td><label for="addon_';
			echo LR\HtmlHelpers::escapeAttr($addon_id) /* pos 50:47 */;
			echo '">';
			echo LR\HtmlHelpers::escapeText($addon_title) /* pos 50:60 */;
			echo '</label></td>
                        <td class="actions" style="width:13%">
                            <a class="bb-button btn14" href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('/product/addon')) /* pos 52:62 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($addon_id) /* pos 52:88 */;
			echo '"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 52:111 */;
			echo 'images/icons/dark/pencil.png" alt=""></a>
                            <a class="bb-button btn14 bb-rm-tr api-link" data-api-confirm="Are you sure?"';
			echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->alink)('product/addons')) /* pos 53:128 */;
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/delete', ['id' => $addon_id]))) /* pos 53:161 */;
			echo '><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 53:223 */;
			echo 'images/icons/dark/trash.png" alt=""></a>
                        </td>
                    </tr>
';
		}
		if ($iterator->isEmpty()) /* pos 56:21 */ {
			echo '                    <tr>
                        <td colspan="2">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('The list is empty')) /* pos 58:41 */;
			echo '</td>
                    </tr>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '                </tbody>
            </table>
            <div class="fix"></div>
        </div>
        
        <div class="fix"></div>

        <div class="tab_content nopadding" id="tab-new">
            
            <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/addon_create'))) /* pos 70:43 */;
		echo ' class="mainForm api-form save" data-api-jsonp="onAfterAddonCreate">
            <fieldset>
                <div class="rowElem">
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Status')) /* pos 73:28 */;
		echo ':</label>
                    <div class="formRight">
                        <input type="radio" name="status" value="enabled"/><label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Enabled')) /* pos 75:83 */;
		echo '</label>
                        <input type="radio" name="status" value="disabled" checked="checked"/><label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Disabled')) /* pos 76:102 */;
		echo '</label>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Activation')) /* pos 81:28 */;
		echo ':</label>
                    <div class="formRight">
                        <input type="radio" name="setup" value="after_order"/><label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('After order is placed')) /* pos 83:86 */;
		echo '</label>
                        <input type="radio" name="setup" value="after_payment" checked="checked"/><label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('After payment is received')) /* pos 84:106 */;
		echo '</label>
                        <input type="radio" name="setup" value="manual"/><label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manual activation')) /* pos 85:81 */;
		echo '</label>
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Icon')) /* pos 91:28 */;
		echo ':</label>
                    <div class="formRight">
                        <input type="text" name="icon_url"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['icon_url']) /* pos 93:68 */;
		echo ' placeholder=""/>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Title')) /* pos 98:28 */;
		echo ':</label>
                    <div class="formRight">
                        <input type="text" name="title"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['title']) /* pos 100:65 */;
		echo ' required="required" placeholder=""/>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Description')) /* pos 105:28 */;
		echo ':</label>
                    <div class="formRight">
                        <textarea name="description" cols="5" rows="5">';
		echo LR\HtmlHelpers::escapeText($product['description']) /* pos 107:72 */;
		echo '</textarea>
                    </div>
                    <div class="fix"></div>
                </div>

                <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Create')) /* pos 112:47 */;
		echo ' class="greyishBtn submitForm" />
            </fieldset>
            </form>

        </div>

    </div>
</div>
';
	}


	/** {block js} on line 122 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script type="text/javascript">
    function onAfterAddonCreate(result)
    {
        bb.redirect(';
		echo LR\Helpers::escapeJs(json_encode(($this->filters->alink)('product/addon') . '/')) /* pos 126:21 */;
		echo ' + result);
    }    
</script>
';
	}
}
