<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/mod_servicepterodactyl_config.latte */
final class Template_4cdf2e060e extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="help">
    <h5>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Service configuration')) /* pos 23:9 */;
		echo '</h5>
</div>

<form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/product/update_config'))) /* pos 26:31 */;
		echo ' class="mainForm save api-form" data-api-reload="1">
    <fieldset>
        <legend>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Settings')) /* pos 28:17 */;
		echo '</legend>
        
        <div class="rowElem noborder">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Nest')) /* pos 31:20 */;
		echo ':</label>
            <div class="formRight">
                <select name="config[nest_id]" id="nest_id" required="required">
                    <option value="">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Select Nest')) /* pos 34:38 */;
		echo '</option>
                    <option';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['nest_id'] ?? '') /* pos 35:37 */;
		echo ' selected="selected">';
		echo LR\HtmlHelpers::escapeText($product['config']['nest_id'] ?? 'Loading...') /* pos 35:95 */;
		echo '</option>
                </select>
                <div class="mt-2">
                    <input type="checkbox" name="config[selectable_nest]" value="1" ';
		if ($product['config']['selectable_nest'] ?? false) /* pos 38:85 */ {
			echo 'checked="checked"';
		}
		echo '>
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('User can select Nest in order')) /* pos 39:28 */;
		echo '</label>
                </div>
            </div>
            <div class="fix"></div>
        </div>

        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Egg')) /* pos 46:20 */;
		echo ':</label>
            <div class="formRight">
                <select name="config[egg_id]" id="egg_id" required="required">
                    <option value="">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Select Egg')) /* pos 49:38 */;
		echo '</option>
                    <option';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['egg_id'] ?? '') /* pos 50:37 */;
		echo ' selected="selected">';
		echo LR\HtmlHelpers::escapeText($product['config']['egg_id'] ?? 'Loading...') /* pos 50:94 */;
		echo '</option>
                </select>
                <div class="mt-2">
                    <input type="checkbox" name="config[selectable_egg]" value="1" ';
		if ($product['config']['selectable_egg'] ?? false) /* pos 53:84 */ {
			echo 'checked="checked"';
		}
		echo '>
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('User can select Egg in order')) /* pos 54:28 */;
		echo '</label>
                </div>
            </div>
            <div class="fix"></div>
        </div>

        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Location')) /* pos 61:20 */;
		echo ':</label>
            <div class="formRight">
                <select name="config[location_id]" id="location_id" required="required">
                    <option value="">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Select Location')) /* pos 64:38 */;
		echo '</option>
                    <option';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['location_id'] ?? '') /* pos 65:37 */;
		echo ' selected="selected">';
		echo LR\HtmlHelpers::escapeText($product['config']['location_id'] ?? 'Loading...') /* pos 65:99 */;
		echo '</option>
                </select>
                <div class="mt-2">
                    <input type="checkbox" name="config[selectable_location]" value="1" ';
		if ($product['config']['selectable_location'] ?? false) /* pos 68:89 */ {
			echo 'checked="checked"';
		}
		echo '>
                    <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('User can select Location in order')) /* pos 69:28 */;
		echo '</label>
                </div>
            </div>
            <div class="fix"></div>
        </div>

        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Startup Command')) /* pos 76:20 */;
		echo ':</label>
            <div class="formRight">
                <textarea name="config[startup]" rows="2">';
		echo LR\HtmlHelpers::escapeText($product['config']['startup'] ?? '') /* pos 78:59 */;
		echo '</textarea>
            </div>
            <div class="fix"></div>
        </div>

        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Docker Image')) /* pos 84:20 */;
		echo ':</label>
            <div class="formRight">
                <select name="config[image]" id="docker_image">
                    <option value="">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Select Image')) /* pos 87:38 */;
		echo '</option>
                    <option';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['image'] ?? '') /* pos 88:37 */;
		echo ' selected="selected">';
		echo LR\HtmlHelpers::escapeText($product['config']['image'] ?? 'None') /* pos 88:93 */;
		echo '</option>
                </select>
                <div class="mt-2">
                    <input type="text" id="custom_docker_image"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Or enter custom image')) /* pos 91:80 */;
		echo ' style="width: 100%; margin-top: 5px;">
                </div>
            </div>
            <div class="fix"></div>
        </div>
    </fieldset>

    <fieldset>
        <legend>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Resources')) /* pos 99:17 */;
		echo '</legend>
        <div class="rowElem noborder" title="0 for unlimited">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Memory (MB)')) /* pos 101:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[memory]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['memory'] ?? '1024') /* pos 103:66 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem" title="0 for unlimited">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Disk (MB)')) /* pos 108:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[disk]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['disk'] ?? '5120') /* pos 110:64 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem" title="0 for unlimited">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('CPU (%)')) /* pos 115:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[cpu]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['cpu'] ?? '100') /* pos 117:63 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem" title="-1 for unlimited">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Swap (MB)')) /* pos 122:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[swap]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['swap'] ?? '0') /* pos 124:64 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('IO')) /* pos 129:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[io]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['io'] ?? '500') /* pos 131:62 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
    </fieldset>

    <fieldset>
        <legend>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Feature Limits')) /* pos 138:17 */;
		echo '</legend>
        <div class="rowElem noborder">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Databases')) /* pos 140:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[databases]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['databases'] ?? '0') /* pos 142:69 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Allocations')) /* pos 147:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[allocations]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['allocations'] ?? '0') /* pos 149:71 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
        <div class="rowElem">
            <label>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Backups')) /* pos 154:20 */;
		echo ':</label>
            <div class="formRight">
                <input type="text" name="config[backups]"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['config']['backups'] ?? '0') /* pos 156:67 */;
		echo '>
            </div>
            <div class="fix"></div>
        </div>
    </fieldset>

    <fieldset>
        <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Update configuration')) /* pos 163:39 */;
		echo ' class="greyishBtn submitForm" />
        <input type="hidden" name="id"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['id']) /* pos 164:48 */;
		echo '/>
    </fieldset>
</form>

<script type="text/javascript">
$(function() {
    var eggs_cache = {};

    function fetchNests() {
        bb.post(\'admin/servicepterodactyl/get_nests\', {}, function(result) {
            var selected = $(\'#nest_id\').val();
            $(\'#nest_id\').empty().append(\'<option value="">Select Nest</option>\');
            $.each(result, function(i, nest) {
                var attr = nest.attributes;
                $(\'#nest_id\').append($(\'<option>\', {
                    value: attr.id,
                    text: attr.name,
                    selected: (attr.id == selected)
                }));
            });
            if (selected) {
                 fetchEggs(selected);
            }
        });
    }

    function fetchLocations() {
        bb.post(\'admin/servicepterodactyl/get_locations\', {}, function(result) {
            var selected = $(\'#location_id\').val();
            $(\'#location_id\').empty().append(\'<option value="">Select Location</option>\');
            $.each(result, function(i, loc) {
                var attr = loc.attributes;
                $(\'#location_id\').append($(\'<option>\', {
                    value: attr.id,
                    text: attr.short + \' (\' + attr.long + \')\',
                    selected: (attr.id == selected)
                }));
            });
        });
    }

    function fetchEggs(nestId) {
        if (!nestId) return;
        bb.post(\'admin/servicepterodactyl/get_eggs\', { nest_id: nestId }, function(result) {
            eggs_cache = {};
            var selected = $(\'#egg_id\').val();
            $(\'#egg_id\').empty().append(\'<option value="">Select Egg</option>\');
            $.each(result, function(i, egg) {
                var attr = egg.attributes;
                eggs_cache[attr.id] = attr;
                $(\'#egg_id\').append($(\'<option>\', {
                    value: attr.id,
                    text: attr.name,
                    selected: (attr.id == selected)
                }));
            });
            if (selected && eggs_cache[selected]) {
                updateDockerImages(eggs_cache[selected]);
            }
        });
    }

    function updateDockerImages(egg) {
        var selected = $(\'#docker_image\').val();
        $(\'#docker_image\').empty().append(\'<option value="">Select Image</option>\');
        
        // Pterodactyl egg attributes contain docker_images which is an array or object
        var images = egg.docker_images;
        if (typeof images === \'object\') {
            $.each(images, function(key, val) {
                // handle both array of strings and key-value mapping
                var name = (typeof val === \'string\') ? val : key;
                var value = val;
                $(\'#docker_image\').append($(\'<option>\', {
                    value: value,
                    text: name,
                    selected: (value == selected)
                }));
            });
        }
    }

    $(\'#nest_id\').on(\'change\', function() {
        fetchEggs($(this).val());
    });

    $(\'#egg_id\').on(\'change\', function() {
        var eggId = $(this).val();
        if (eggs_cache[eggId]) {
            updateDockerImages(eggs_cache[eggId]);
            // Also update startup command if empty
            var startup = $(\'textarea[name="config[startup]"]\').val();
            if(!startup || startup == "") {
                $(\'textarea[name="config[startup]"]\').val(eggs_cache[eggId].startup);
            }
        }
    });

    $(\'#docker_image\').on(\'change\', function() {
        if($(this).val()) {
            $(\'#custom_docker_image\').val(\'\');
        }
    });

    $(\'#custom_docker_image\').on(\'input\', function() {
        if($(this).val()) {
            $(\'#docker_image\').val(\'\');
        }
    });

    // Initial fetch
    fetchNests();
    fetchLocations();
});
</script>
';
	}
}
