<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/partial_extensions.latte */
final class Template_524d0b9926 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		if ($header) /* pos 25:1 */ {
			echo '    <div class="help">
        <h5>';
			echo LR\HtmlHelpers::escapeText($header) /* pos 27:13 */;
			echo '</h5>
    </div>
';
		}
		echo '
<table class="tableStatic wide">
    <thead>
        <tr>
            <td>&nbsp;</td>
            <td style="width: 30%">Extension</td>
            <td>Description</td>
            <td width="18%">&nbsp;</td>
        </tr>
    </thead>
    <tbody>
';
		$extensions = $admin->extension_get_latest(['type' => $type]) /* pos 41:9 */;
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($extensions, $ʟ_it ?? null) as $extension) /* pos 42:9 */ {
			echo '        <tr>
            <td><img';
			echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($extension->icon_url)) /* pos 44:28 */;
			echo LR\HtmlHelpers::formatAttribute(' alt', $extension->name) /* pos 44:57 */;
			echo ' style="width: 32px; height: 32px;"/></td>
            <td>
                <a class="bb-button"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($extension->project_url)) /* pos 46:45 */;
			echo ' target="_blank" title="View extension details">';
			echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($extension->name, 40)) /* pos 46:118 */;
			echo ' ';
			echo LR\HtmlHelpers::escapeText($extension->version) /* pos 46:149 */;
			echo '</a>
                <br/>by <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($extension->author_url)) /* pos 47:35 */;
			echo ' target="_blank">';
			echo LR\HtmlHelpers::escapeText($extension->author) /* pos 47:76 */;
			echo '</a>
            </td>
            <td>';
			echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($extension->description, 150)) /* pos 49:17 */;
			echo '</td>
            <td class="actions">
                <a class="bb-button btn14 api-link" data-api-confirm="By installing \'';
			echo LR\HtmlHelpers::escapeAttr($extension->name) /* pos 51:86 */;
			echo '\' you agree with terms and conditions. Install only extensions you trust. Continue?" data-api-reload="1"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/extension/install', ['type' => $extension->type, 'id' => $extension->id]))) /* pos 51:217 */;
			echo ' title="Install extension"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 51:343 */;
			echo 'images/icons/dark/cog.png" alt=""></a>
                <a class="bb-button btn14"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($extension->project_url)) /* pos 52:51 */;
			echo ' target="_blank" title="Details"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 52:119 */;
			echo 'images/icons/dark/globe.png" alt=""></a>
                <a class="bb-button btn14"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($extension->download_url)) /* pos 53:51 */;
			echo ' title="Download ';
			echo LR\HtmlHelpers::escapeAttr($extension->name) /* pos 53:94 */;
			echo '"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 53:124 */;
			echo 'images/icons/dark/download.png" alt=""></a>
            </td>
        </tr>
';
		}
		if ($iterator->isEmpty()) /* pos 56:9 */ {
			echo '        <tr>
            <td colspan="4" class="aligncenter"><a href="http://extensions.OHMS.org/" target="_blank">Explore OHMS extensions</a></td>
        </tr>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '    </tbody>
    <tfoot>
        <tr>
            <td colspan="4"></td>
        </tr>
    </tfoot>
</table>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['extension' => '42'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$header = $header ?? null /* pos 22:1 */;
		$type = $type ?? null /* pos 23:1 */;
		return get_defined_vars();
	}
}
