<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/layout_login.latte */
final class Template_cb9428a8e6 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>';
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 25:12 */;
		echo '</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    
';
		$this->createTemplate('partial_bb_meta.latte', $this->params, 'include')->renderToContentType('html') /* pos 29:5 */;
		echo '
    <link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 31:34 */;
		echo 'css/min.css?v=';
		echo LR\HtmlHelpers::escapeAttr($version) /* pos 31:61 */;
		echo '" type="text/css" media="screen" />
    <link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 32:34 */;
		echo 'css/setup-login.css?v=';
		echo LR\HtmlHelpers::escapeAttr($version) /* pos 32:69 */;
		echo '" type="text/css" media="screen" />
    <link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 35:41 */;
		echo 'js/ohms.min.js?v=';
		echo LR\HtmlHelpers::escapeAttr($version) /* pos 35:71 */;
		echo '"></script>
    <script type="text/javascript" src="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 36:41 */;
		echo 'js/admin.js?v=';
		echo LR\HtmlHelpers::escapeAttr($version) /* pos 36:68 */;
		echo '"></script>
</head>

<body class="setup-admin-page">
    <div class="setup-admin-shell">
';
		$this->renderBlock('content', get_defined_vars()) /* pos 41:9 */;
		echo '    </div>
';
		$this->renderBlock('js', get_defined_vars()) /* pos 43:1 */;
		echo '</body>
</html>
';
	}


	/** {block meta_title} on line 25 */
	public function blockMeta_title(array $ʟ_args): void
	{
	}


	/** {block content} on line 41 */
	public function blockContent(array $ʟ_args): void
	{
	}


	/** {block js} on line 43 */
	public function blockJs(array $ʟ_args): void
	{
	}
}
