<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/partial_pricing.latte */
final class Template_f7af8b5768 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($product['type'] != 'domain') /* pos 22:1 */ {
			echo '<div class="rowElem">
    <label>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Payment type')) /* pos 24:12 */;
			echo ':</label>
    <div class="formRight pp_type">
        <input type="radio" name="pricing[type]" value="free"';
			if ($product['pricing']['type'] == 'free') /* pos 26:62 */ {
				echo ' checked="checked"';
			}
			echo ' id="pricing-free"/><label for="pricing-free">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Free')) /* pos 26:173 */;
			echo '</label>
        <input type="radio" name="pricing[type]" value="once"';
			if ($product['pricing']['type'] == 'once') /* pos 27:62 */ {
				echo ' checked="checked"';
			}
			echo ' id="pricing-once"/><label for="pricing-once">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('One time')) /* pos 27:173 */;
			echo '</label>
        <input type="radio" name="pricing[type]" value="recurrent"';
			if ($product['pricing']['type'] == 'recurrent') /* pos 28:67 */ {
				echo ' checked="checked"';
			}
			echo ' id="pricing-recurrent"/><label for="pricing-recurrent">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Recurrent')) /* pos 28:193 */;
			echo '</label>
    </div>
    <div class="fix"></div>
</div>

<table class="pp wide">
    <tbody class="once" ';
			if ($product['pricing']['type'] != 'once') /* pos 34:25 */ {
				echo 'style="display:none;"';
			}
			echo '>
        <tr>
            <th>&nbsp;</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Setup price')) /* pos 37:17 */;
			echo ' (';
			echo LR\HtmlHelpers::escapeText($admin->currency_get_default->code) /* pos 37:41 */;
			echo ')</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Price')) /* pos 38:17 */;
			echo ' (';
			echo LR\HtmlHelpers::escapeText($admin->currency_get_default->code) /* pos 38:33 */;
			echo ')</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Total')) /* pos 39:17 */;
			echo '</th>
            <th>&nbsp;</th>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('One time')) /* pos 43:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[once][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['once']['setup']) /* pos 44:98 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[once][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['once']['price']) /* pos 45:97 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td>&nbsp;</td>
        </tr>
    </tbody>

    <tbody class="recurrent" ';
			if ($product['pricing']['type'] != 'recurrent') /* pos 51:30 */ {
				echo 'style="display:none;"';
			}
			echo '>
        <tr>
            <th style="width: 5%;">&nbsp;</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Setup price')) /* pos 54:17 */;
			echo ' (';
			echo LR\HtmlHelpers::escapeText($admin->currency_get_default->code) /* pos 54:41 */;
			echo ')</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Price for period')) /* pos 55:17 */;
			echo ' (';
			echo LR\HtmlHelpers::escapeText($admin->currency_get_default->code) /* pos 55:46 */;
			echo ')</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('First payment sum')) /* pos 56:17 */;
			echo '</th>
            <th>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('On')) /* pos 57:17 */;
			echo '</th>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Weekly')) /* pos 60:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][1W][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['1W']['setup']) /* pos 61:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][1W][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['1W']['price']) /* pos 62:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][1W][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][1W][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['1W']['enabled']) /* pos 64:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Monthly')) /* pos 67:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][1M][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['1M']['setup']) /* pos 68:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][1M][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['1M']['price']) /* pos 69:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][1M][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][1M][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['1M']['enabled']) /* pos 71:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every 3 months')) /* pos 74:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][3M][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['3M']['setup']) /* pos 75:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][3M][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['3M']['price']) /* pos 76:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][3M][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][3M][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['3M']['enabled']) /* pos 78:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every 6 months')) /* pos 81:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][6M][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['6M']['setup']) /* pos 82:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][6M][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['6M']['price']) /* pos 83:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][6M][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][6M][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['6M']['enabled']) /* pos 85:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every year')) /* pos 88:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][1Y][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['1Y']['setup']) /* pos 89:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][1Y][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['1Y']['price']) /* pos 90:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][1Y][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][1Y][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['1Y']['enabled']) /* pos 92:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every 2 years')) /* pos 95:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][2Y][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['2Y']['setup']) /* pos 96:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][2Y][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['2Y']['price']) /* pos 97:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][2Y][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][2Y][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['2Y']['enabled']) /* pos 99:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
        <tr>
            <td><label for="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every 3 years')) /* pos 102:31 */;
			echo '</label></td>
            <td><input type="text" class="price setup_price" name="pricing[recurrent][3Y][setup]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['3Y']['setup']) /* pos 103:107 */;
			echo '></td>
            <td><input type="text" class="price bill_price" name="pricing[recurrent][3Y][price]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $product['pricing']['recurrent']['3Y']['price']) /* pos 104:106 */;
			echo '></td>
            <td><input type="text" class="total price" readonly="readonly" disabled="disabled"/></td>
            <td><input type="hidden" name="pricing[recurrent][3Y][enabled]" value="0" /><input type="checkbox" name="pricing[recurrent][3Y][enabled]" value="1" ';
			if ($product['pricing']['recurrent']['3Y']['enabled']) /* pos 106:161 */ {
				echo 'checked="checked"';
			}
			echo '/></td>
        </tr>
    </tbody>
</table>

<script>
    $(function() {
        $(\'input.price:not(:disabled)\').keyup(function() {
            var row = $(this).parents(\'tr:first\');
            var s = row.find(\'input.setup_price\').val();
            var p = row.find(\'input.bill_price\').val();
            var total = countTotal(p, s);
            var elem = row.find(\'input.total\');

            elem.val(total);
        }).trigger(\'keyup\');

        $(\'.pp_type input\').click(function() {
            $(\'table.pp tbody\').hide();
            $(\'table.pp tbody.\' + $(this).val()).show();
        });
    });

    function countTotal(p, s)
    {
        p = parseFloat(p);
        s = parseFloat(s);
        
        var num = new Number(p + s);
        
        if (!isNaN(num))
            return num.toFixed(2);

        return (0).toFixed(2);
    }
</script>
';
		}
		echo "\n";
	}
}
