<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/partial_footer.latte */
final class Template_0eec84303c extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="admin-footer">
    <span>&copy; ';
		echo LR\HtmlHelpers::escapeText(($this->filters->date)($now, 'Y')) /* pos 23:18 */;
		echo ' OHMS. ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Version')) /* pos 23:40 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($guest->system_version()) /* pos 23:59 */;
		echo '.</span>
    <div class="admin-footer-links">
        <a href="http://docs.OHMS.org/" target="_blank">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Documentation')) /* pos 25:57 */;
		echo '</a>
        <a href="https://github.com/OHMS/OHMS/issues" target="_blank">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Report bug')) /* pos 26:71 */;
		echo '</a>
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/'))) /* pos 27:20 */;
		echo ' target="_blank">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Visit site')) /* pos 27:47 */;
		echo '</a>
    </div>
</div>
';
	}
}
