<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/admin/template\admin_default\html/partial_pagination.latte */
final class Template_d236723685 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($list->pages > 1) /* pos 22:1 */ {
			$currentPage = $request->page ?? 1 /* pos 23:1 */;
			$paginator = $guest->system_paginator(['total' => $list->total, 'page' => $currentPage, 'per_page' => $list->per_page]) /* pos 24:1 */;
			echo '
<div class="pagination">
    <ul class="pages">
';
			if ($paginator->currentpage != 1) /* pos 28:9 */ {
				echo '        <li class="prev"><a';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)($url, array_merge(($this->filters->slice)(array_merge([], $request), 1, ($this->filters->length)($request)), ['page' => $currentPage - 1])))) /* pos 29:36 */;
				echo '><</a></li>
';
			}
			if ($paginator->range[0] != 1) /* pos 31:9 */ {
				echo '            <li><a';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)($url, ['page' => 1]))) /* pos 32:27 */;
				echo ' >1</a></li>
';
			}
			foreach (range($paginator->start, $paginator->end) as $i) /* pos 34:9 */ {
				echo "\n";
				if ($paginator->range[0] > 2 && $i == $paginator->range[0]) /* pos 36:13 */ {
					echo '                ...
';
				}
				echo "\n";
				if ($i == $paginator->currentpage) /* pos 40:13 */ {
					echo '                <li><a class="active" href="#" onclick="return false;">';
					echo LR\HtmlHelpers::escapeText($i) /* pos 41:72 */;
					echo '</a></li>
';
				} else /* pos 42:13 */ {
					echo '                <li><a';
					echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)($url, array_merge(($this->filters->slice)(array_merge([], $request), 1, ($this->filters->length)($request)), ['page' => $i])))) /* pos 43:31 */;
					echo '> ';
					echo LR\HtmlHelpers::escapeText($i) /* pos 43:127 */;
					echo '</a></li>
';
				}

			}

			echo "\n";
			if ($paginator->range->{$paginator->midrange - 1}
			< $paginator->numpages - 1 && $paginator->end == $paginator->range->{$paginator->midrange - 1}) /* pos 47:9 */ {
				echo '            ...
            <li><a';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)($url, array_merge(($this->filters->slice)(array_merge([], $request), 1, ($this->filters->length)($request)), ['page' => $paginator->numpages])))) /* pos 49:27 */;
				echo '> ';
				echo LR\HtmlHelpers::escapeText($paginator->numpages) /* pos 49:141 */;
				echo '</a></li>
';
			}
			echo "\n";
			if ($paginator->currentpage != $paginator->numpages) /* pos 52:9 */ {
				echo '        <li class="next"><a';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)($url, array_merge(($this->filters->slice)(array_merge([], $request), 1, ($this->filters->length)($request)), ['page' => $currentPage + 1])))) /* pos 53:36 */;
				echo '>></a></li>
';
			}
			echo '    </ul>
</div>
';
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['i' => '34'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
