<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: client/_sidebar_client.latte */
final class Template_f3355e6c9c extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="client-sidebar" id="clientSidebar">
    <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/'))) /* pos 8:16 */;
		echo ' class="client-brand">
        <i class="fa fa-th"></i> ';
		echo LR\HtmlHelpers::escapeText($settings->company_name ?? 'Company Name') /* pos 9:34 */;
		echo '
    </a>
    
    <div class="client-nav">
        <!-- Section: Navigation -->
        <div class="nav-section-title">Navigation</div>
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/client'))) /* pos 15:20 */;
		echo ' class="client-nav-link ';
		if ($active_path == '/client') /* pos 15:60 */ {
			echo 'active';
		}
		echo '">
            <i class="fa fa-home"></i> ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Dashboard')) /* pos 16:40 */;
		echo '
        </a>
        
';
		if ($settings->side_menu_services ?? true) /* pos 19:9 */ {
			echo '        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('order/service'))) /* pos 20:20 */;
			echo ' class="client-nav-link ';
			if (str_starts_with($active_path, '/order/service')) /* pos 20:66 */ {
				echo 'active';
			}
			echo '">
            <i class="fa fa-server"></i> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Servers')) /* pos 21:42 */;
			echo '
        </a>
';
		}
		echo '        
';
		if ($settings->side_menu_invoices ?? true) /* pos 25:9 */ {
			echo '        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('invoice'))) /* pos 26:20 */;
			echo ' class="client-nav-link ';
			if (str_starts_with($active_path, '/invoice')) /* pos 26:58 */ {
				echo 'active';
			}
			echo '">
            <i class="fa fa-file-invoice"></i> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Orders')) /* pos 27:48 */;
			echo '
        </a>
';
		}
		echo '
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/client/affiliates'))) /* pos 31:20 */;
		echo ' class="client-nav-link ';
		if (str_starts_with($active_path, '/client/affiliates')) /* pos 31:71 */ {
			echo 'active';
		}
		echo '">
            <i class="fa fa-users"></i> ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Affiliate')) /* pos 32:41 */;
		echo '
        </a>

        <!-- Section: Support -->
        <div class="nav-section-title mt-3">Help & Support</div>
';
		if ($settings->side_menu_support ?? true) /* pos 37:9 */ {
			echo '        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('support'))) /* pos 38:20 */;
			echo ' class="client-nav-link ';
			if (str_starts_with($active_path, '/support')) /* pos 38:58 */ {
				echo 'active';
			}
			echo '">
            <i class="fa fa-life-ring"></i> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Tickets')) /* pos 39:45 */;
			echo '
        </a>
';
		}
		echo '        
';
		if ($settings->side_menu_kb ?? true) /* pos 43:9 */ {
			echo '        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('kb'))) /* pos 44:20 */;
			echo ' class="client-nav-link ';
			if (str_starts_with($active_path, '/kb')) /* pos 44:53 */ {
				echo 'active';
			}
			echo '">
            <i class="fa fa-graduation-cap"></i> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Knowledge Base')) /* pos 45:50 */;
			echo '
        </a>
';
		}
		echo '
        <!-- Section: Account -->
        <div class="nav-section-title mt-3">Account</div>
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('client/profile'))) /* pos 51:20 */;
		echo ' class="client-nav-link ';
		if (str_starts_with($active_path, '/client/profile')) /* pos 51:67 */ {
			echo 'active';
		}
		echo '">
            <i class="fa fa-user-cog"></i> ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 52:44 */;
		echo '
        </a>
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('client/logout'))) /* pos 54:20 */;
		echo ' class="client-nav-link text-danger-hover">
            <i class="fa fa-sign-out-alt"></i> ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Logout')) /* pos 55:48 */;
		echo '
        </a>
    </div>

    <div class="client-sidebar-footer">
        <div class="mb-2 text-uppercase" style="font-size: 0.65rem; letter-spacing: 1px; color: var(--text-secondary);">Follow us on</div>
        <div class="social-icons-mini">
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-youtube"></i></a>
            <a href="#"><i class="fab fa-discord"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
        </div>
        <div class="mt-3">
            <div style="font-size: 0.65rem; color: var(--text-secondary); margin-bottom: 4px;">Rate Us on Trustpilot</div>
            <div class="trustpilot-stars"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
        </div>
    </div>
</div>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		$req_path = $request->_url ?? '' /* pos 1:1 */;
		$request_path = ltrim($req_path, '/') /* pos 2:1 */;
		$srv_uri = $request->getServer('REQUEST_URI') ?? '' /* pos 3:1 */;
		$request_uri = ltrim($srv_uri, '/') /* pos 4:1 */;
		$active_path = str_starts_with($request_path, 'client') || str_starts_with($request_uri, 'client') ? '/client' : '/' . $request_path /* pos 5:1 */;
		return get_defined_vars();
	}
}
