<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default/shared/_placeholder.latte */
final class Template_e4184e46f1 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="wh-card">
    <div class="wh-placeholder">
        <h2>';
		echo LR\HtmlHelpers::escapeText($title) /* pos 3:13 */;
		echo '</h2>
        <p class="text-secondary mb-3">';
		echo LR\HtmlHelpers::escapeText($description) /* pos 4:40 */;
		echo '</p>
';
		if (isset($note)) /* pos 5:9 */ {
			echo '            <p class="small text-secondary mb-0">';
			echo LR\HtmlHelpers::escapeText($note) /* pos 6:50 */;
			echo '</p>
';
		}
		echo '    </div>
</div>
';
	}
}
