<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/modules\Formbuilder\html_admin\mod_formbuilder_settings.latte */
final class Template_d99aa887c9 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'head' => 'blockHead', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 28:1 */;
		echo '

';
		$active_menu = 'system' /* pos 30:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 32:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 76:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 216:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['form' => '96', 'i' => '200', 'field' => '200'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 26:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 28 */
	public function blockMeta_title(array $ʟ_args): void
	{
		echo 'Custom form builder';
	}


	/** {block head} on line 32 */
	public function blockHead(array $ʟ_args): void
	{
		echo '<style type="text/css">
#background_overlay {
    display: none;
    position: fixed;
    top: 0%;
    left: 0%;
    width: 100%;
    height: 100%;
    background-color: #000;
    z-index:1001;
    -moz-opacity: 0.7;
    opacity:.70;
    filter: alpha(opacity=70);
}
.update-field {
    display: none;
    position: absolute;
    top: 20%;
    left: 20%;
    margin-left: 0px;
    margin-top: 0px;
    padding: 10px;
    background: url(images/alertOpacityOverlay.png) repeat;
    border-radius: 10px;
    --webkit-border-radius: 10px;
    z-index:1002;
    overflow:visible;
}
#background-loader {
    display: none;
    position: absolute;
    left: 50%;
    top: 50%;
    margin-left: -110px;
    margin-top: -10px;
}
.manage {
    position: relative;
    background: #ffffff;
}
</style>
';
	}


	/** {block content} on line 76 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget simpleTabs">
    <ul class="tabs">
        <li><a href="#tab-index" id="open-index-tab">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Custom forms')) /* pos 79:54 */;
		echo '</a></li>
    </ul>

    <div class="tabs_container">
        <div class="fix"></div>

        <div class="tab_content nopadding" id="tab-index">
            <table class="tableStatic wide">
                <thead>
                    <tr>
                        <th>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Form')) /* pos 89:29 */;
		echo '</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Orders using this form')) /* pos 90:29 */;
		echo '</th>
                        <th>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products using this form')) /* pos 91:29 */;
		echo '</th>
                        <td width="23%">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Actions')) /* pos 92:41 */;
		echo '</td>
                    </tr>
                </thead>
                <tbody>
';
		foreach ($admin->formbuilder_get_forms as $form) /* pos 96:21 */ {
			echo '                    <tr>
                        <td>';
			echo LR\HtmlHelpers::escapeText($form->name) /* pos 98:29 */;
			echo '</td>
                        <td>';
			echo LR\HtmlHelpers::escapeText($form->order_count) /* pos 99:29 */;
			echo '</td>
                        <td>';
			echo LR\HtmlHelpers::escapeText($form->product_count) /* pos 100:29 */;
			echo '</td>
                        <td class="actions">
                            <a class="bb-button btn14"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('extension/settings/formbuilder', ['id' => $form->id]))) /* pos 102:64 */;
			echo '><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 102:133 */;
			echo 'images/icons/dark/pencil.png" alt=""></a>
                            <a class="bb-button btn14 copy_form" href="#" data-api-reload="1"  title="Copy"';
			echo LR\HtmlHelpers::formatDataAttribute(' data-form-id', $form->id) /* pos 103:124 */;
			echo '><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 103:146 */;
			echo 'images/icons/dark/baloons.png" alt=""></a>
                            <a class="btn14 bb-rm-tr api-link"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/delete_form', ['id' => $form->id]))) /* pos 104:72 */;
			echo ' data-api-confirm="Are you sure?" ><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 104:177 */;
			echo 'images/icons/dark/trash.png" alt=""></a>
                        </td>
                    </tr>
';

		}

		echo '                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4">
                            <input type="button"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Create new form')) /* pos 112:59 */;
		echo ' class="greyishBtn" id="new-form" style="width: 150px; float: right;"/>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="tab_content" id="tab-import">
            <form method="post"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/import'))) /* pos 120:43 */;
		echo ' class="mainForm api-form save" data-api-reload="1">
                <fieldset>
                    <div class="formBottom">
                        <textarea name="form" cols="5" rows="5" placeholder="Paste new form configuration text."></textarea>
                    </div>
                    <div class="fix"></div>
                    <input type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Import')) /* pos 126:51 */;
		echo ' class="greyishBtn submitForm" style="margin: 0"/>
                </fieldset>
            </form>
        </div>
    </div>
</div>

';
		if ($request->id) /* pos 133:1 */ {
			$form = $admin->formbuilder_get_form(['id' => $request->id]) /* pos 134:5 */;
			echo '
<div class="widget" id="form-options-';
			echo LR\HtmlHelpers::escapeAttr($form->id) /* pos 136:38 */;
			echo '">
    <div class="head">
        <h5 class="iCog">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Form options')) /* pos 138:26 */;
			echo '</h5>
    </div>

    <div class="mainForm">
        <form  id="update-form-options">
            <div class="rowElem">
                <label>
                    <strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('New form name and options')) /* pos 145:29 */;
			echo '</strong>
                </label>
                <div class="formRight">
                    <input type="text" name="form_name"  id="form_name"';
			echo LR\HtmlHelpers::formatAttribute(' value', $form->name) /* pos 148:81 */;
			echo ' style="width:300px;"/>
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <div class="formRight">
                    <select name="type" id="form_type" style="width:300px;">
                        <option value="default" ';
			if ($form->style->type == 'default') /* pos 155:49 */ {
				echo ' selected ';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Labels on top')) /* pos 155:103 */;
			echo '</option>
                        <option value="horizontal" ';
			if ($form->style->type == 'horizontal') /* pos 156:52 */ {
				echo ' selected ';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Labels on the left')) /* pos 156:109 */;
			echo '</option>
                    </select>
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <div class="formRight">
                    <select name="show_title" id="show_title" style="width:300px;">
                        <option value="1" ';
			if ($form->style->show_title == 1) /* pos 164:43 */ {
				echo ' selected ';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Show form title')) /* pos 164:95 */;
			echo '</option>
                        <option value="0" ';
			if ($form->style->show_title == 0) /* pos 165:43 */ {
				echo ' selected ';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Do not show form title')) /* pos 165:95 */;
			echo '</option>
                    </select>
                </div>
                <div class="fix"></div>
            </div>

            <input type="hidden" name="form_id"';
			echo LR\HtmlHelpers::formatAttribute(' value', $form->id) /* pos 171:57 */;
			echo '>

            <div class="rowElem">
                <div class="formRight">
                    <button type="submit" href="#" class="button blueBtn">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Update')) /* pos 175:75 */;
			echo '</button>
                </div>
                <div class="fix"></div>
            </div>
        </form>
        <div class="fix"></div>
    </div>
</div>

<div class="widget" id="form-';
			echo LR\HtmlHelpers::escapeAttr($form->id) /* pos 184:30 */;
			echo '">
<div class="head">
    <h5 class="iCog">';
			echo LR\HtmlHelpers::escapeText($form->name) /* pos 186:22 */;
			echo '</h5>
</div>

<div class="mainForm">

<div class="body" id="fields">
    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/add_field', ['form_id' => $form->id, 'type' => 'text']))) /* pos 192:16 */;
			echo ' title="" class="btnIconLeft mr10 api-link" data-api-reload="1" ><img src="images/icons/dark/add.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Text')) /* pos 192:223 */;
			echo '</span></a>
    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/add_field', ['form_id' => $form->id, 'type' => 'select']))) /* pos 193:16 */;
			echo ' title="" class="btnIconLeft mr10 api-link" data-api-reload="1"><img src="images/icons/dark/add.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Dropdown')) /* pos 193:224 */;
			echo '</span></a>
    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/add_field', ['form_id' => $form->id, 'type' => 'radio']))) /* pos 194:16 */;
			echo ' title="" class="btnIconLeft mr10 api-link" data-api-reload="1"><img src="images/icons/dark/add.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Radio')) /* pos 194:223 */;
			echo '</span></a>
    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/add_field', ['form_id' => $form->id, 'type' => 'checkbox']))) /* pos 195:16 */;
			echo ' title="" class="btnIconLeft mr10 api-link" data-api-reload="1"><img src="images/icons/dark/add.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('checkbox')) /* pos 195:226 */;
			echo '</span></a>
    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/formbuilder/add_field', ['form_id' => $form->id, 'type' => 'textarea']))) /* pos 196:16 */;
			echo ' title="" class="btnIconLeft mr10 api-link" data-api-reload="1"><img src="images/icons/dark/add.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Textarea')) /* pos 196:226 */;
			echo '</span></a>
</div>

<fieldset>
';
			foreach ($form->fields as $i => $field) /* pos 200:1 */ {
				echo '    <div class="wrap-field">
';
				$this->createTemplate('mod_formbuilder_field.latte', [...$field] + $this->params, 'include')->renderToContentType('html') /* pos 202:5 */;
				$this->createTemplate('mod_formbuilder_preview.latte', [...$field] + $this->params, 'include')->renderToContentType('html') /* pos 203:5 */;
				echo '    </div>
';

			}

			echo '</fieldset>

</div>
<div class="fix"></div>
</div>';
		}
		echo '
<div id="background_overlay">
    <img src="images/loaders/loader7.gif" alt="" id="background-loader">
</div>
';
	}


	/** {block js} on line 216 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script type="text/javascript">
    $(function () {
        $("form").submit( function () {
            $(\':checkbox:not(:checked)\').removeAttr(\'checked\');
        });

        $(\'.new-field\').click(function () {
            var p = $(this).closest(\'.rowElem\').prev();

            p.clone().insertAfter(p);
            p.next().find(\'input\').val("");

            return false;
        });

        $(\'#textarea-width, #textarea-height\').change(function () {
            var p = $(this).closest(\'.rowElem\');
            var width = $(\'#textarea-width\').val();
            var height = $(\'#textarea-height\').val();

            p.next().find(\'textarea\').css({"width":width, "height":height});

            return false;
        });

        $(\'#prefix_text, #suffix_text\').change(function () {
            var prefix = $(\'#prefix_text\').val();
            var suffix = $(\'#suffix_text\').val();
            
            $(\'#prepended_text\').text(prefix);
            $(\'#appended_text\').text(suffix);

           return false;
        });


        $(\'.rm\').click(function () {
            var fid = $(this).attr(\'data-field-id\');
            var rm = $(this);

            jConfirm(\'Are you sure?\', \'Confirm\', function(r) {
                if(r) {
                    bb.post(\'admin/formbuilder/delete_field\', { id: fid }, function () {
                        $(rm).parents(\'.wrap-field\').slideUp("normal", function () {
                            $(rm).remove();
                        });
                    });
                }
            });
            return false;
        });

        $(\'.ed\').click(function () {
            var edit_button = $(this);

            var center = function(edit_button){
                var leftPosition = ($(window).width() / 2) - ((  $(edit_button).parents(\'.wrap-field\').find(\'.update-field\').width() / 2) + 10);
                var topPosition = ($(document).height() / 2) - ((  $(edit_button).parents(\'.wrap-field\').find(\'.update-field\').height() / 2) + 50);

                $(edit_button).parents(\'.wrap-field\').find(\'.update-field\').css({
                    \'top\': topPosition,
                    \'left\': leftPosition
                });
            };

            center(edit_button);

            $(\'#background_overlay\').fadeIn(function(){
                $(window).resize(function() {
                    center(edit_button);
                });

                $(edit_button).parents(\'.wrap-field\').find(\'.update-field\').fadeIn(function() {
                    $(\'html, body\').animate({
                        scrollTop: $(this).offset().top
                    }, 500);
                });

                $(\'#background_overlay\').click(function() {
                    hide_edit_form();
                });

                $(\'body\').delegate(\'.close-field-form\',\'click\', function() {
                    hide_edit_form();
                    
                    return false;
                });

                $(document).keyup(function(e) {
                    if (e.keyCode == 27) {
                       hide_edit_form();
                    }
                });

                var hide_edit_form  = function () {
                    $(\'#background_overlay\').fadeOut();
                    $(edit_button).parents(\'.wrap-field\').find(\'.update-field\').fadeOut();
                };
            });

            return false;
        });

        $(\'.pr\').click(function () {
            $(this).hide().siblings(\'.ed\').show();
            $(this).parents(\'.wrap-field\').find(\'.preview\').show();
            $(this).parents(\'.wrap-field\').find(\'.manage\').hide();
            
            return false;
        });

        $(\'#update-form-options\').bind(\'submit\',function (event) {
            bb.post(\'admin/formbuilder/update_form_settings\', $(this).serialize(), function() {
                bb.msg(';
		echo LR\Helpers::escapeJs(json_encode(($this->filters->trans)('Form options were updated'))) /* pos 330:24 */;
		echo ')
            })
            
            return false;
        });

        $(\'.update-field\').bind(\'submit\',function (event) {
            var field_form = $(this);
            
            bb.post(\'admin/formbuilder/update_field\', $(this).serialize(), function() {
                $(field_form).fadeOut();
                $(\'#background-loader\').show();
                bb.reload();
            })
            
            return false;
        });

       $(\'#new-form\').click(function () {
            jPrompt(\'Give your new form a title\', \'My new form\', \'Form title\', function (title) {
                if (title) {
                    bb.post(\'admin/formbuilder/create_form\', { name: title }, function (id) {
                        bb.redirect(';
		echo LR\Helpers::escapeJs(json_encode(($this->filters->alink)('extension/settings/formbuilder', ['id' => '']))) /* pos 352:37 */;
		echo ' + id);
                    });
                }
            });

            return false;
        });

        $(\'.copy_form\').click(function () {
            var fid = $(this).attr(\'data-form-id\');

            jPrompt(\'Give your new form a title\', \'My new form\', \'Form title\', function (title) {
                if (title) {
                    bb.post(\'admin/formbuilder/copy_form\', { name: title, form_id: fid }, function (id) {
                        bb.redirect(';
		echo LR\Helpers::escapeJs(json_encode(($this->filters->alink)('extension/settings/formbuilder', ['id' => '']))) /* pos 366:37 */;
		echo ' + id);
                    });
                }
            });

            return false;
        });
    });
</script>
';
	}
}
