<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/Index/_landing.latte */
final class Template_310e58c483 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="gm-landing" id="home">
    <section class="gm-hero">
        <div class="gm-hero-review">
            <div class="gm-review-card">
                <div class="gm-review-title">Google Reviews</div>
                <div class="gm-review-stars">★★★★★</div>
                <div class="gm-review-score">4.8/5 from 500+ reviews</div>
            </div>
        </div>
        <h1>No-Lag. No Excuses.</h1>
        <h2>Game Server Hosting</h2>
        <h3>That Delivers</h3>
        <p class="gm-hero-text">
            ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Every second of downtime costs your players and damages your reputation.')) /* pos 14:13 */;
		echo '
            ';
		echo LR\HtmlHelpers::escapeText($settings->company_name ?: $company->name ?? 'Our Company') /* pos 15:13 */;
		echo '
            ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('delivers ultra-fast performance, protection that actually works, and 24/7 support.')) /* pos 16:13 */;
		echo '
        </p>
        <div class="gm-hero-actions">
            <a class="gm-btn gm-btn-primary"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/order'))) /* pos 19:54 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Find Game Servers')) /* pos 19:70 */;
		echo '</a>
            <a class="gm-btn gm-btn-ghost"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/support/contact-us'))) /* pos 20:52 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Talk To Us')) /* pos 20:81 */;
		echo '</a>
        </div>
    </section>

    <section class="gm-trust" id="trust">
        <div class="gm-glass-panel">
            <h2>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Trusted By The Best')) /* pos 26:17 */;
		echo '</h2>
            <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Powering gaming communities worldwide')) /* pos 27:16 */;
		echo '</p>
            <div class="gm-logo-row">
                <span>Google Reviews</span>
                <span>Reddit</span>
                <span>Gamers</span>
                <span>Partners</span>
                <span>Communities</span>
            </div>
            <div class="gm-stats">
                <div>
                    <strong>5,000+</strong>
                    <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Active Servers')) /* pos 38:27 */;
		echo '</span>
                </div>
                <div>
                    <strong>100K+</strong>
                    <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Players Online')) /* pos 42:27 */;
		echo '</span>
                </div>
                <div>
                    <strong>99.9%</strong>
                    <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Uptime')) /* pos 46:27 */;
		echo '</span>
                </div>
                <div>
                    <strong>24/7</strong>
                    <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Support')) /* pos 50:27 */;
		echo '</span>
                </div>
            </div>
        </div>
    </section>

';
		$this->createTemplate('Index/_games-grid.latte', $this->params, 'include')->renderToContentType('html') /* pos 56:5 */;
		echo '
    <section class="gm-features" id="features">
        <div class="gm-glass-panel gm-glass-panel--wide">
            <h2>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Why Choose')) /* pos 60:17 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($settings->company_name ?: $company->name ?? 'Our Company') /* pos 60:39 */;
		echo '?</h2>
            <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Game Server Hosting Made Simple')) /* pos 61:17 */;
		echo '</h3>
            <div class="gm-feature-grid">
                <div class="gm-feature-card">
                    <i class="fa fa-bolt"></i>
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Lag-Free Performance')) /* pos 65:25 */;
		echo '</h4>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('High-frequency CPUs and ultra-fast networking ensure smooth gameplay.')) /* pos 66:24 */;
		echo '</p>
                </div>
                <div class="gm-feature-card">
                    <i class="fa fa-rocket"></i>
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Instant Deployment')) /* pos 70:25 */;
		echo '</h4>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Go live in under 60 seconds with automated setup.')) /* pos 71:24 */;
		echo '</p>
                </div>
                <div class="gm-feature-card">
                    <i class="fa fa-gamepad"></i>
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Supports 50+ Games')) /* pos 75:25 */;
		echo '</h4>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Survival, FPS, sandbox, and MMO titles with mod support.')) /* pos 76:24 */;
		echo '</p>
                </div>
                <div class="gm-feature-card">
                    <i class="fa fa-cogs"></i>
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Full Control Panel')) /* pos 80:25 */;
		echo '</h4>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manage configs, backups, and files with zero coding required.')) /* pos 81:24 */;
		echo '</p>
                </div>
                <div class="gm-feature-card">
                    <i class="fa fa-shield-alt"></i>
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Advanced DDoS Protection')) /* pos 85:25 */;
		echo '</h4>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Enterprise-grade protection keeps your community online.')) /* pos 86:24 */;
		echo '</p>
                </div>
                <div class="gm-feature-card">
                    <i class="fa fa-globe"></i>
                    <h4>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Worldwide Coverage')) /* pos 90:25 */;
		echo '</h4>
                    <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Low ping globally with data centers in key regions.')) /* pos 91:24 */;
		echo '</p>
                </div>
            </div>
        </div>
    </section>

    <section class="gm-faq" id="faq">
        <div class="gm-section-title">
            <span class="gm-section-kicker">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Game Server Hosting FAQ')) /* pos 99:45 */;
		echo '</span>
            <h2>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Game Server Hosting FAQ')) /* pos 100:17 */;
		echo '</h2>
            <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Find quick answers to common questions.')) /* pos 101:16 */;
		echo '</p>
        </div>
        <div class="gm-faq-grid">
            <div class="gm-faq-item">
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('How fast is server setup?')) /* pos 105:23 */;
		echo '</span>
                <i class="fa fa-plus"></i>
            </div>
            <div class="gm-faq-item">
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Can I change my server location?')) /* pos 109:23 */;
		echo '</span>
                <i class="fa fa-plus"></i>
            </div>
            <div class="gm-faq-item">
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Is my server DDoS protected?')) /* pos 113:23 */;
		echo '</span>
                <i class="fa fa-plus"></i>
            </div>
            <div class="gm-faq-item">
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Do you offer automated backups?')) /* pos 117:23 */;
		echo '</span>
                <i class="fa fa-plus"></i>
            </div>
            <div class="gm-faq-item">
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Can I install mods and custom maps?')) /* pos 121:23 */;
		echo '</span>
                <i class="fa fa-plus"></i>
            </div>
            <div class="gm-faq-item">
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('What control panel is used?')) /* pos 125:23 */;
		echo '</span>
                <i class="fa fa-plus"></i>
            </div>
        </div>
    </section>
</div>
';
	}
}
