<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/Modal/_add-ticket.latte */
final class Template_04ee819737 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="modal fade"';
		echo LR\HtmlHelpers::formatAttribute(' id', $id) /* pos 7:30 */;
		echo ' tabindex="-1" role="dialog"';
		echo LR\HtmlHelpers::formatAriaAttribute(' aria-labelledby', ($this->filters->trans)('Open new ticket')) /* pos 7:83 */;
		echo '>
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" class="api-form" data-api-url="client/support/ticket_create"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-tocreated', ($this->filters->link)('support/ticket')) /* pos 10:116 */;
		echo '>
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Open new ticket')) /* pos 12:63 */;
		echo '</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label" for="selectTicket';
		echo LR\HtmlHelpers::escapeAttr($id) /* pos 17:68 */;
		echo 'Helpdesk">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Help desk')) /* pos 17:83 */;
		echo ':</label>
';
		$this->renderBlock('selectbox', ['support_helpdesk_id', $client->support_helpdesk_get_pairs, $request->support_helpdesk_id, 1, null, 'selectTicket' . $id . 'Helpdesk'] + [], 'html') /* pos 18:25 */;
		echo '                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="inputTicket';
		echo LR\HtmlHelpers::escapeAttr($id) /* pos 21:67 */;
		echo 'Subject">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Subject')) /* pos 21:81 */;
		echo ':</label>
                        <input type="text" class="form-control" id="inputTicket';
		echo LR\HtmlHelpers::escapeAttr($id) /* pos 22:80 */;
		echo 'Subject" name="subject"';
		echo LR\HtmlHelpers::formatAttribute(' value', $subject) /* pos 22:117 */;
		echo ' required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="textareaTicket';
		echo LR\HtmlHelpers::escapeAttr($id) /* pos 25:70 */;
		echo 'Message">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reason')) /* pos 25:84 */;
		echo ':</label>
                        <textarea class="form-control" id="textareaTicket';
		echo LR\HtmlHelpers::escapeAttr($id) /* pos 26:74 */;
		echo 'Message" name="content" rows="10" maxlength="999" style="resize:none" required>';
		echo LR\HtmlHelpers::escapeText($message) /* pos 26:158 */;
		echo '</textarea>
                    </div>
';
		if ($order) /* pos 28:21 */ {
			echo '                        <input type="hidden" name="rel_type" value="order">
                        <input type="hidden" name="rel_id"';
			echo LR\HtmlHelpers::formatAttribute(' value', $order['id']) /* pos 30:68 */;
			echo '>
';
		}
		if ($cancelation) /* pos 32:21 */ {
			echo '                        <input type="hidden" name="rel_task" value="cancel">
';
		}
		echo '                </div>
                <div class="modal-footer d-block">
                    <div class="d-grid">
                        <button class="btn btn-primary" type="submit">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Submit')) /* pos 38:71 */;
		echo '</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

';
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 1:1 */;
		$subject = $subject ?? '' /* pos 2:1 */;
		$message = $message ?? '' /* pos 3:1 */;
		$order = $order ?? null /* pos 4:1 */;
		$cancelation = $cancelation ?? null /* pos 5:1 */;
		return get_defined_vars();
	}
}
