<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/client/mod_dashboard_index.latte */
final class Template_ff52aa8c1d extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'page_header' => 'blockPage_header', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 3:1 */;
		echo "\n";
		$this->renderBlock('page_header', get_defined_vars()) /* pos 4:1 */;
		echo '

';
		$this->createTemplate('../macro_functions.latte', $this->params, "import")->render() /* pos 6:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 8:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['i' => '68, 96', 'order' => '68', 'email' => '96'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		return get_defined_vars();
	}


	/** {block meta_title} on line 3 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Client Area')) /* pos 3:19 */;
	}


	/** {block page_header} on line 4 */
	public function blockPage_header(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Dashboard')) /* pos 4:20 */;
	}


	/** {block content} on line 8 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if ($settings['showcase_enabled']) /* pos 9:1 */ {
			$this->createTemplate('../Index/_showcase.latte', $this->params, 'include')->renderToContentType('html') /* pos 10:5 */;
		}
		echo "\n";
		if ($settings['stats_enabled']) /* pos 13:1 */ {
			$this->createTemplate('../Index/_statistics.latte', $this->params, 'include')->renderToContentType('html') /* pos 14:5 */;
		}
		echo '
<div class="widget-grid">
    <!-- Servers Widget -->
';
		if ($settings['dash_services'] ?? true) /* pos 19:5 */ {
			$servicesTotal = $client->order_get_list(['hide_addons' => 1, 'status' => 'active'])['total'] ?? 0 /* pos 20:5 */;
			echo '    <div class="widget-box">
        <div class="widget-title">
            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Servers')) /* pos 23:19 */;
			echo '</span>
            <i class="fa fa-server"></i>
        </div>
        <div class="widget-value">';
			echo LR\HtmlHelpers::escapeText($servicesTotal) /* pos 26:35 */;
			echo '</div>
        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('order/service/manage'))) /* pos 27:20 */;
			echo ' class="widget-btn">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Order a New Server')) /* pos 27:69 */;
			echo '</a>
    </div>
';
		}
		echo '
    <!-- Tickets Widget -->
';
		if ($settings['dash_support'] ?? true) /* pos 32:5 */ {
			$ticketsTotal = $client->support_ticket_get_list(['status' => 'open'])['total'] ?? 0 /* pos 33:5 */;
			echo '    <div class="widget-box">
        <div class="widget-title">
            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Active Tickets')) /* pos 36:19 */;
			echo '</span>
            <i class="fa fa-ticket"></i>
        </div>
        <div class="widget-value">';
			echo LR\HtmlHelpers::escapeText($ticketsTotal) /* pos 39:35 */;
			echo '</div>
    </div>
';
		}
		echo '
    <!-- Invoices Widget -->
';
		if ($settings['dash_invoices'] ?? true) /* pos 44:5 */ {
			$invoicesTotal = $client->invoice_get_list(['status' => 'unpaid'])['total'] ?? 0 /* pos 45:5 */;
			echo '    <div class="widget-box">
        <div class="widget-title">
            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Unpaid Invoices')) /* pos 48:19 */;
			echo '</span>
            <i class="fa fa-file-invoice-dollar"></i>
        </div>
        <div class="widget-value">';
			echo LR\HtmlHelpers::escapeText($invoicesTotal) /* pos 51:35 */;
			echo '</div>
    </div>
';
		}
		echo '</div>

<!-- Extra Glass Cards for Lists -->
<div class="row g-4 mt-2">
    <!-- Recent Orders -->
';
		if ($settings['dash_orders'] ?? true) /* pos 59:5 */ {
			echo '    <div class="col-md-6">
        <div class="glass-card h-100">
            <h5 class="mb-4 d-flex justify-content-between align-items-center" style="font-size: 1rem; color: var(--text-secondary);">
                <span><i class="fa fa-shopping-cart me-2"></i> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Recent orders')) /* pos 63:64 */;
			echo '</span>
            </h5>
            <div class="table-responsive">
                <table class="table table-borderless table-glass m-0">
                    <tbody>
';
			foreach ($client->order_get_list(['per_page' => 5, 'page' => $request->page, 'hide_addons' => 1])['list'] ?? [] as $i => $order) /* pos 68:25 */ {
				echo '                        <tr>
                            <td>
                                <a href="';
				echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('order/service/manage')) /* pos 71:42 */;
				echo '/';
				echo LR\HtmlHelpers::escapeAttr($order->id) /* pos 71:73 */;
				echo '" class="text-decoration-none text-white fw-bold">';
				echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($order->title, 30)) /* pos 71:135 */;
				echo '</a>
                            </td>
                            <td class="text-end">
                                <span class="status-badge ';
				if ($order->status == 'active') /* pos 74:59 */ {
					echo 'status-active';
				} elseif ($order->status == 'pending_setup') /* pos 74:105 */ {
					echo 'status-pending';
				} else /* pos 74:163 */ {
					echo 'status-unpaid';
				}

				echo '">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)(($this->filters->capitalize)(($this->filters->replace)((string) $order->status, ['_' => ' '])))) /* pos 74:189 */;
				echo '</span>
                            </td>
                        </tr>
';

			}

			if (count($client->order_get_list(['per_page' => 5, 'page' => $request->page, 'hide_addons' => 1])['list'] ?? []) == 0) /* pos 78:25 */ {
				echo '                        <tr><td colspan="2" class="text-center text-secondary py-4">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No recent orders')) /* pos 79:85 */;
				echo '</td></tr>
';
			}
			echo '                    </tbody>
                </table>
            </div>
        </div>
    </div>
';
		}
		echo '
    <!-- Recent Emails -->
';
		if ($settings['dash_messages'] ?? true) /* pos 89:5 */ {
			echo '    <div class="col-md-6">
        <div class="glass-card h-100">
            <h5 class="mb-4 d-flex justify-content-between align-items-center" style="font-size: 1rem; color: var(--text-secondary);">
                <span><i class="fa fa-envelope me-2"></i> ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Recent emails')) /* pos 93:59 */;
			echo '</span>
            </h5>
            <div class="list-group list-group-flush bg-transparent">
';
			foreach ($client->email_get_list(['per_page' => 5])['list'] ?? [] as $i => $email) /* pos 96:17 */ {
				echo '                <a href="';
				echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('email')) /* pos 97:26 */;
				echo '/';
				echo LR\HtmlHelpers::escapeAttr($email->id) /* pos 97:40 */;
				echo '" class="list-group-item bg-transparent text-white border-bottom" style="border-color: rgba(255,255,255,0.05) !important;">
                    <div class="d-flex w-100 justify-content-between">
                        <span class="mb-1 text-truncate" style="max-width: 70%;">';
				echo LR\HtmlHelpers::escapeText($email->subject) /* pos 99:82 */;
				echo '</span>
                        <small class="text-secondary" style="font-size: 0.75rem;">';
				echo LR\HtmlHelpers::escapeText(($this->filters->timeago)($email->created_at)) /* pos 100:83 */;
				echo ' ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('ago')) /* pos 100:112 */;
				echo '</small>
                    </div>
                </a>
';

			}

			if (count($client->email_get_list(['per_page' => 5])['list'] ?? []) == 0) /* pos 104:17 */ {
				echo '                <div class="text-center text-secondary py-4">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No recent emails')) /* pos 105:62 */;
				echo '</div>
';
			}
			echo '            </div>
        </div>
    </div>
';
		}
		echo '</div>

';
	}
}
