<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/client/_topbar_client.latte */
final class Template_dbd3c7ce13 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="client-topbar sticky-top">
    <div class="d-flex align-items-center">
        <a class="mobile-menu-toggle d-lg-none me-3" onclick="document.getElementById(\'clientSidebar\').classList.toggle(\'show\')">
            <i class="fa fa-bars"></i>
        </a>
        <h1 class="topbar-title">
';
		if (str_starts_with($active_path, '/client')) /* pos 13:13 */ {
			echo '                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Dashboard')) /* pos 14:17 */;
			echo "\n";
		} elseif (str_starts_with($active_path, '/order/service')) /* pos 15:13 */ {
			echo '                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Servers')) /* pos 16:17 */;
			echo "\n";
		} elseif (str_starts_with($active_path, '/invoice')) /* pos 17:13 */ {
			echo '                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Orders')) /* pos 18:17 */;
			echo "\n";
		} elseif (str_starts_with($active_path, '/support')) /* pos 19:13 */ {
			echo '                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Help & Support')) /* pos 20:17 */;
			echo "\n";
		} else /* pos 21:13 */ {
			echo '                ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Client Area')) /* pos 22:17 */;
			echo "\n";
		}



		echo '        </h1>
    </div>

    <div class="topbar-actions">
        <!-- Credits -->
        <span class="credits-display d-none d-md-inline">
            Your Credits: <span class="credits-amount">';
		echo LR\HtmlHelpers::escapeText($profile->currency ?? '$') /* pos 30:56 */;
		echo LR\HtmlHelpers::escapeText($profile->balance ?? '0.00') /* pos 30:83 */;
		echo '</span>
        </span>
        
        <!-- Help -->
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('support'))) /* pos 34:20 */;
		echo ' class="action-icon">
            <i class="fa-regular fa-circle-question"></i>
        </a>
        
        <!-- Notifications -->
        <a href="#" class="action-icon position-relative">
            <i class="fa-regular fa-bell"></i>
        </a>
        
        <!-- User Dropdown -->
        <div class="dropdown">
            <div class="user-avatar" data-bs-toggle="dropdown" aria-expanded="false" title="';
		echo LR\HtmlHelpers::escapeAttr($profile->first_name) /* pos 45:93 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeAttr($profile->last_name) /* pos 45:116 */;
		echo '">
                ';
		echo LR\HtmlHelpers::escapeText(($this->filters->upper)(($this->filters->first)($profile->first_name ?? 'U'))) /* pos 46:17 */;
		echo LR\HtmlHelpers::escapeText(($this->filters->upper)(($this->filters->first)($profile->last_name ?? 'ser'))) /* pos 46:60 */;
		echo '
            </div>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark" style="background-color: var(--nav-bg); border-color: var(--glass-border);">
                <li><a class="dropdown-item text-white"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('client/profile'))) /* pos 49:65 */;
		echo '><i class="fa fa-user me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Profile')) /* pos 49:120 */;
		echo '</a></li>
                <li><hr class="dropdown-divider" style="border-color: var(--glass-border);"></li>
                <li><a class="dropdown-item text-danger"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('client/logout'))) /* pos 51:66 */;
		echo '><i class="fa fa-sign-out-alt me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Logout')) /* pos 51:128 */;
		echo '</a></li>
            </ul>
        </div>
    </div>
</div>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		$req_path = $request->_url ?? '' /* pos 1:1 */;
		$request_path = ltrim($req_path, '/') /* pos 2:1 */;
		$srv_uri = $request->getServer('REQUEST_URI') ?? '' /* pos 3:1 */;
		$request_uri = ltrim($srv_uri, '/') /* pos 4:1 */;
		$active_path = str_starts_with($request_path, 'client') || str_starts_with($request_uri, 'client') ? '/client' : '/' . $request_path /* pos 5:1 */;
		return get_defined_vars();
	}
}
