<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: Index/_games-grid.latte */
final class Template_47b95cc3e8 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<section class="gm-games" id="games">
    <div class="gm-section-title">
        <span class="gm-section-kicker">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Game Server Hosting')) /* pos 3:41 */;
		echo '</span>
        <h2>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Supported Games')) /* pos 4:13 */;
		echo '</h2>
        <p>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Choose from our popular game server hosting options with instant setup.')) /* pos 5:12 */;
		echo '</p>
    </div>

    <div class="gm-games-grid">
        <!-- 7 Days to Die -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_7d2d = 'images/games/7-days-to-die.png' /* pos 12:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_7d2d)) /* pos 12:104 */;
		echo '" alt="7-days-to-die" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('7 Days to Die')) /* pos 13:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Survival nights with stable performance and backups.')) /* pos 15:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/7-days-to-die'))) /* pos 16:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 16:83 */;
		echo '</a>
        </div>
        <!-- American Truck Simulator Dedicated Server -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_ats = 'images/games/american-truck-simulator.png' /* pos 21:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_ats)) /* pos 21:114 */;
		echo '" alt="american-truck-simulator" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('American Truck Simulator Dedicated Server')) /* pos 22:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Dedicated trucking servers with stable sync.')) /* pos 24:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/american-truck-simulator'))) /* pos 25:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 25:94 */;
		echo '</a>
        </div>
        <!-- Arma 3 -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_a3 = 'images/games/arma-3.svg' /* pos 30:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_a3)) /* pos 30:95 */;
		echo '" alt="arma-3" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Arma 3')) /* pos 31:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Mil-sim performance with modpack delivery.')) /* pos 33:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/arma-3'))) /* pos 34:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 34:76 */;
		echo '</a>
        </div>
        <!-- BeamMP -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_bmp = 'images/games/beammp.png' /* pos 39:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_bmp)) /* pos 39:96 */;
		echo '" alt="beammp" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('BeamMP')) /* pos 40:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Low-latency BeamMP hosting for massive sessions.')) /* pos 42:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/beammp'))) /* pos 43:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 43:76 */;
		echo '</a>
        </div>
        <!-- Counter-Strike 2 -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_cs2 = 'images/games/counter-strike-2-pin.jpg' /* pos 48:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_cs2)) /* pos 48:110 */;
		echo '" alt="counter-strike-2" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Counter-Strike 2')) /* pos 49:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Competitive-ready tick servers with anti-DDoS protection.')) /* pos 51:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/counter-strike-2'))) /* pos 52:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 52:86 */;
		echo '</a>
        </div>
        <!-- Euro Truck Simulator 2 Dedicated Server -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_ets2 = 'images/games/euro-truck-simulator-2.png' /* pos 57:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_ets2)) /* pos 57:113 */;
		echo '" alt="euro-truck-simulator-2" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Euro Truck Simulator 2 Dedicated Server')) /* pos 58:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('ETS2 hosting tuned for convoy events.')) /* pos 60:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/euro-truck-simulator-2'))) /* pos 61:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 61:92 */;
		echo '</a>
        </div>
        <!-- Garrys Mod -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_gm = 'images/games/garrys-mod.svg' /* pos 66:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_gm)) /* pos 66:99 */;
		echo '" alt="garrys-mod" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Garrys Mod')) /* pos 67:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Workshop-ready GMod servers with fast load times.')) /* pos 69:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/garrys-mod'))) /* pos 70:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 70:80 */;
		echo '</a>
        </div>
        <!-- GTA 5M -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_gta = 'images/games/gta-5m.png' /* pos 75:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_gta)) /* pos 75:96 */;
		echo '" alt="gta-5m" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('GTA 5M')) /* pos 76:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('FiveM optimized hosting for smooth RP sessions.')) /* pos 78:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/gta-5m'))) /* pos 79:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 79:76 */;
		echo '</a>
        </div>
        <!-- Insurgency -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_ins = 'images/games/insurgency.png' /* pos 84:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_ins)) /* pos 84:100 */;
		echo '" alt="insurgency" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Insurgency')) /* pos 85:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Tactical FPS hosting with low jitter.')) /* pos 87:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/insurgency'))) /* pos 88:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 88:80 */;
		echo '</a>
        </div>
        <!-- Killing Floor 2 -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_kf2 = 'images/games/killing-floor-2.png' /* pos 93:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_kf2)) /* pos 93:105 */;
		echo '" alt="killing-floor-2" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Killing Floor 2')) /* pos 94:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Wave-ready KF2 servers with low ping.')) /* pos 96:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/killing-floor-2'))) /* pos 97:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 97:85 */;
		echo '</a>
        </div>
        <!-- Minecraft -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_mc = 'images/games/minecraft-pin.jpg' /* pos 102:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_mc)) /* pos 102:102 */;
		echo '" alt="minecraft" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Minecraft')) /* pos 103:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No lag. No downtime. No DDoS attacks. Launch a Minecraft server in under 60 seconds with full modpack support.')) /* pos 105:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/minecraft'))) /* pos 106:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 106:79 */;
		echo '</a>
        </div>
        <!-- Palworld -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_pw = 'images/games/palworld.jpg' /* pos 111:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_pw)) /* pos 111:97 */;
		echo '" alt="palworld" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Palworld')) /* pos 112:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Co-op Palworld hosting with mod support.')) /* pos 114:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/palworld'))) /* pos 115:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 115:78 */;
		echo '</a>
        </div>
        <!-- Rust -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_rust = 'images/games/rust.svg' /* pos 120:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_rust)) /* pos 120:95 */;
		echo '" alt="rust" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Rust')) /* pos 121:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('High-frequency CPUs built for Rust wipes and raids.')) /* pos 123:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/rust'))) /* pos 124:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 124:74 */;
		echo '</a>
        </div>
        <!-- Satisfactory -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_sf = 'images/games/satisfactory.png' /* pos 129:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_sf)) /* pos 129:101 */;
		echo '" alt="satisfactory" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Satisfactory')) /* pos 130:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Persistent factories with autosave protection.')) /* pos 132:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/satisfactory'))) /* pos 133:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 133:82 */;
		echo '</a>
        </div>
        <!-- SCP: Secret Laboratory -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_scp = 'images/games/scp-secret-laboratory.png' /* pos 138:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_scp)) /* pos 138:111 */;
		echo '" alt="scp-secret-laboratory" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('SCP: Secret Laboratory')) /* pos 139:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Secure SCP hosting with smooth tick rates.')) /* pos 141:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/scp-secret-laboratory'))) /* pos 142:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 142:91 */;
		echo '</a>
        </div>
        <!-- TF2 -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_tf2 = 'images/games/tf2.svg' /* pos 147:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_tf2)) /* pos 147:93 */;
		echo '" alt="tf2" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('TF2')) /* pos 148:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Classic TF2 hosting with instant deployment.')) /* pos 150:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/tf2'))) /* pos 151:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 151:73 */;
		echo '</a>
        </div>
        <!-- Unturned -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_unt = 'images/games/unturned.svg' /* pos 156:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_unt)) /* pos 156:98 */;
		echo '" alt="unturned" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Unturned')) /* pos 157:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Lightweight hosting with easy workshop installs.')) /* pos 159:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/unturned'))) /* pos 160:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 160:78 */;
		echo '</a>
        </div>
        <!-- V Rising -->
        <div class="gm-game-card">
            <div class="gm-game-card__head">
                <span class="gm-game-icon"><img src="';
		$img_vr = 'images/games/v-rising.png' /* pos 165:54 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_vr)) /* pos 165:97 */;
		echo '" alt="v-rising" style="width: 24px;"></span>
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('V Rising')) /* pos 166:25 */;
		echo '</strong>
            </div>
            <div class="gm-game-card__desc text-secondary mb-3 px-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Castle-ready V Rising hosting with automated restarts.')) /* pos 168:70 */;
		echo '</div>
            <a class="gm-btn gm-btn-game mt-auto"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/v-rising'))) /* pos 169:59 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Plans')) /* pos 169:78 */;
		echo '</a>
        </div>
    </div>
</section>';
	}
}
