<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: macro_functions.latte */
final class Template_c3996e2bfb extends Latte\Runtime\Template
{
	public const Blocks = [
		['selectbox' => 'blockSelectbox', 'selectboxtld' => 'blockSelectboxtld', 'currency_format' => 'blockCurrency_format', 'currency' => 'blockCurrency', 'status_name' => 'blockStatus_name', 'period_name' => 'blockPeriod_name', 'markdown_quote' => 'blockMarkdown_quote', 'recaptcha' => 'blockRecaptcha'],
	];


	public function main(array $ʟ_args): void
	{
		echo '







';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['val' => '4', 'label' => '4', 'data' => '12', 'line' => '38'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}


	/** {define selectbox, $name, $options, $selected, $required, $nullOption, $id} on line 1 */
	public function blockSelectbox(array $ʟ_args): void
	{
		extract($this->params);
		$name = $ʟ_args[0] ?? $ʟ_args['name'] ?? null;
		$options = $ʟ_args[1] ?? $ʟ_args['options'] ?? null;
		$selected = $ʟ_args[2] ?? $ʟ_args['selected'] ?? null;
		$required = $ʟ_args[3] ?? $ʟ_args['required'] ?? null;
		$nullOption = $ʟ_args[4] ?? $ʟ_args['nullOption'] ?? null;
		$id = $ʟ_args[5] ?? $ʟ_args['id'] ?? null;
		unset($ʟ_args);

		echo '    <select class="form-select"';
		echo LR\HtmlHelpers::formatAttribute(' id', $id) /* pos 2:38 */;
		echo LR\HtmlHelpers::formatAttribute(' name', $name) /* pos 2:51 */;
		echo ' ';
		if ($required) /* pos 2:59 */ {
			echo ' required';
		}
		echo '>
';
		if ($nullOption) /* pos 3:9 */ {
			echo '        <option value="">-- ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)($nullOption)) /* pos 3:45 */;
			echo ' --</option>';
		}
		echo "\n";
		foreach ($options ?? [] as $val => $label) /* pos 4:9 */ {
			echo '            <option';
			echo LR\HtmlHelpers::formatAttribute(' value', $val) /* pos 5:29 */;
			if ($selected == $val) /* pos 5:35 */ {
				echo ' selected';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)($label)) /* pos 5:74 */;
			echo '</option>
';

		}

		echo '    </select>
';
	}


	/** {define selectboxtld, $name, $options, $selected, $required} on line 10 */
	public function blockSelectboxtld(array $ʟ_args): void
	{
		extract($this->params);
		$name = $ʟ_args[0] ?? $ʟ_args['name'] ?? null;
		$options = $ʟ_args[1] ?? $ʟ_args['options'] ?? null;
		$selected = $ʟ_args[2] ?? $ʟ_args['selected'] ?? null;
		$required = $ʟ_args[3] ?? $ʟ_args['required'] ?? null;
		unset($ʟ_args);

		echo '    <select';
		echo LR\HtmlHelpers::formatAttribute(' name', $name) /* pos 11:20 */;
		echo ' ';
		if ($required) /* pos 11:28 */ {
			echo 'required';
		}
		echo ' class="form-select">
';
		foreach ($options ?? [] as $data) /* pos 12:9 */ {
			echo '            <option';
			echo LR\HtmlHelpers::formatAttribute(' value', $data->tld) /* pos 13:29 */;
			echo LR\HtmlHelpers::formatAttribute(' label', $data->tld) /* pos 13:50 */;
			echo ' ';
			if ($selected == $data->tld) /* pos 13:63 */ {
				echo 'selected';
			}
			echo '>';
			echo LR\HtmlHelpers::escapeText($data->tld) /* pos 13:107 */;
			echo '</option>
';

		}

		echo '    </select>
';
	}


	/** {define currency_format, $price, $currency} on line 19 */
	public function blockCurrency_format(array $ʟ_args): void
	{
		extract($this->params);
		$price = $ʟ_args[0] ?? $ʟ_args['price'] ?? null;
		$currency = $ʟ_args[1] ?? $ʟ_args['currency'] ?? null;
		unset($ʟ_args);

		echo '    ';
		echo LR\HtmlHelpers::escapeText(($this->filters->money)($price, $currency)) /* pos 20:5 */;
		echo "\n";
	}


	/** {define currency, $price, $currency} on line 24 */
	public function blockCurrency(array $ʟ_args): void
	{
		extract($this->params);
		$price = $ʟ_args[0] ?? $ʟ_args['price'] ?? null;
		$currency = $ʟ_args[1] ?? $ʟ_args['currency'] ?? null;
		unset($ʟ_args);

		echo '    ';
		echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($price, $currency)) /* pos 25:5 */;
		echo "\n";
	}


	/** {define status_name, $status} on line 28 */
	public function blockStatus_name(array $ʟ_args): void
	{
		extract($this->params);
		$status = $ʟ_args[0] ?? $ʟ_args['status'] ?? null;
		unset($ʟ_args);

		echo '    ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)(($this->filters->capitalize)(($this->filters->replace)((string) $status, ['_' => ' '])))) /* pos 29:5 */;
		echo "\n";
	}


	/** {define period_name, $period} on line 33 */
	public function blockPeriod_name(array $ʟ_args): void
	{
		extract($this->params);
		$period = $ʟ_args[0] ?? $ʟ_args['period'] ?? null;
		unset($ʟ_args);

		echo '    ';
		echo LR\HtmlHelpers::escapeText(($this->filters->period_title)($period)) /* pos 34:5 */;
		echo "\n";
	}


	/** {define markdown_quote, $text} on line 37 */
	public function blockMarkdown_quote(array $ʟ_args): void
	{
		extract($this->params);
		$text = $ʟ_args[0] ?? $ʟ_args['text'] ?? null;
		unset($ʟ_args);

		foreach (($this->filters->split)($text, '
') as $line) /* pos 38:1 */ {
			echo '> ';
			echo LR\HtmlHelpers::escapeText($line) /* pos 39:3 */;
			echo "\n";

		}
	}


	/** {define recaptcha} on line 43 */
	public function blockRecaptcha(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if ($guest->extension_is_on(['mod' => 'spamchecker'])) /* pos 44:5 */ {
			$rc = $guest->spamchecker_recaptcha /* pos 45:9 */;
			echo "\n";
			if ($rc->enabled) /* pos 47:9 */ {
				if ($rc->version == 2) /* pos 48:13 */ {
					echo '                <script src=\'https://www.google.com/recaptcha/api.js\' async defer></script>
                <div class="g-recaptcha"';
					echo LR\HtmlHelpers::formatDataAttribute(' data-sitekey', $rc->publickey) /* pos 50:57 */;
					echo '></div>
';
				}
			}
		}
	}
}
