<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default/sidebar-categories-selector.latte */
final class Template_0662a9d831 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="wh-catalog-mobile-nav d-lg-none">
';
		foreach ($categories as $category) /* pos 3:5 */ {
			if (count($category['products'] ?? []) > 0) /* pos 4:9 */ {
				$isDefaultCategory = strtolower($category['title'] ?? '') === 'default' /* pos 5:13 */;
				echo '            <a class="wh-mobile-chip" href="';
				echo LR\HtmlHelpers::escapeQuotes(json_encode('#category-' . $category['id'])) /* pos 6:45 */;
				echo '" onclick="window.location.hash=\'category-';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($category['id'])) /* pos 6:142 */;
				echo '\'; return false;">
                ';
				if ($isDefaultCategory) /* pos 7:17 */ {
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products')) /* pos 7:40 */;
				} else /* pos 7:59 */ {
					echo LR\HtmlHelpers::escapeText($category['title']) /* pos 7:65 */;
				}
				echo '
            </a>
';
			}

		}

		echo '</div>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['category' => '3'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$categories = $categories ?? $guest->product_category_get_list(['per_page' => 100])['list'] ?? [] /* pos 1:1 */;
		return get_defined_vars();
	}
}
