<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default\configureproductdomain.latte */
final class Template_63b81987ec extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'head' => 'blockHead', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 4:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 5:1 */;
		echo "\n";
		$this->renderBlock('content_before', get_defined_vars()) /* pos 7:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 15:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 87:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_public.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 2:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 4 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText($product['title']) /* pos 4:19 */;
	}


	/** {block head} on line 5 */
	public function blockHead(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('shared/_styles.latte', $this->params, 'include')->renderToContentType('html') /* pos 5:13 */;
	}


	/** {block content_before} on line 7 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="wh-page-header">
        <h1 class="wh-page-title">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register or Transfer a Domain')) /* pos 9:35 */;
		echo '</h1>
        <p class="wh-page-subtitle">';
		echo LR\HtmlHelpers::escapeText(($this->filters->truncate)(($this->filters->stripHtml)($product['description']), 220)) /* pos 10:37 */;
		echo '</p>
    </div>
';
		$this->createTemplate('_order-steps.latte', ['selected' => 2, 'product' => $product] + $this->params, 'include')->renderToContentType('html') /* pos 12:5 */;
	}


	/** {block content} on line 15 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$periods = $guest->system_periods /* pos 16:5 */;
		$pricing = $product['pricing'] /* pos 17:5 */;
		$transfer_tlds = $guest->serviceDomain_tlds(['allow_transfer' => 1]) /* pos 18:5 */;
		$register_tlds = $guest->serviceDomain_tlds(['allow_register' => 1]) /* pos 19:5 */;
		echo '    <form method="post" class="api-form" data-api-url="guest/cart/add_item"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->link)('cart')) /* pos 20:98 */;
		echo '>
        <div class="wh-form-panel">
            <section>
                <div class="wh-card">
                    <div class="wh-card-body">
                        <div class="wh-domain-tabs">
                            <button class="btn btn-outline-primary active" type="button" data-domain-product-pane="register">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register domain')) /* pos 26:126 */;
		echo '</button>
';
		if (($this->filters->length)($transfer_tlds)) /* pos 27:29 */ {
			echo '                                <button class="btn btn-outline-primary" type="button" data-domain-product-pane="transfer">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Transfer domain')) /* pos 28:123 */;
			echo '</button>
';
		}
		echo '                        </div>
                        <div class="wh-domain-pane is-active" id="domain-product-pane-register">
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" name="register_sld"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->register_sld) /* pos 33:101 */;
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Enter new domain name to register')) /* pos 33:141 */;
		echo '>
';
		$this->renderBlock('selectboxtld', ['register_tld', $register_tlds, $request->register_tld, 0] + [], 'html') /* pos 34:33 */;
		echo '                                <button class="btn btn-primary" type="button" id="domain-product-check">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Check')) /* pos 35:105 */;
		echo '</button>
                            </div>
                            <div class="onAfterDomainCheck" style="display:none;">
                                <label class="form-label" for="registration-years">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Registration period')) /* pos 38:84 */;
		echo '</label>
                                <select class="form-select mb-3" name="register_years" id="registration-years"></select>
                                <div class="form-check mb-3">
                                    <input class="form-check-input" type="checkbox" id="toggle-nameservers" onclick="$(\'#domain-product-nameservers\').slideToggle();">
                                    <label class="form-check-label" for="toggle-nameservers">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('I want to use my own nameservers')) /* pos 42:94 */;
		echo '</label>
                                </div>
                                <div id="domain-product-nameservers" style="display:none;">
                                    <input class="form-control mb-2" type="text" name="ns1"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Nameserver 1')) /* pos 45:108 */;
		echo '>
                                    <input class="form-control mb-2" type="text" name="ns2"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Nameserver 2')) /* pos 46:108 */;
		echo '>
                                    <input class="form-control mb-2" type="text" name="ns3"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Nameserver 3')) /* pos 47:108 */;
		echo '>
                                    <input class="form-control" type="text" name="ns4"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Nameserver 4')) /* pos 48:103 */;
		echo '>
                                </div>
                            </div>
                        </div>
';
		if (($this->filters->length)($transfer_tlds)) /* pos 52:25 */ {
			echo '                        <div class="wh-domain-pane" id="domain-product-pane-transfer">
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" name="transfer_sld"';
			echo LR\HtmlHelpers::formatAttribute(' value', $request->transfer_sld) /* pos 55:101 */;
			echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Enter your domain name to transfer')) /* pos 55:141 */;
			echo '>
';
			$this->renderBlock('selectboxtld', ['transfer_tld', $transfer_tlds, $request->transfer_tld, 0] + [], 'html') /* pos 56:33 */;
			echo '                                <button class="btn btn-primary" type="button" id="domain-product-transfer-check">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Check')) /* pos 57:114 */;
			echo '</button>
                            </div>
                            <div id="domain-product-transfer-config" style="display:none;">
                                <p class="small text-secondary">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Transfer price')) /* pos 60:65 */;
			echo ': <strong id="domain-product-transfer-price"></strong></p>
                                <input type="text" class="form-control" name="transfer_code"';
			echo LR\HtmlHelpers::formatAttribute(' value', $request->transfer_code) /* pos 61:102 */;
			echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Enter domain transfer code')) /* pos 61:143 */;
			echo '>
                            </div>
                        </div>
';
		}
		echo '                        <input type="hidden" name="action" value="register" id="domain-product-action">
                        <input type="hidden" name="id"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['id']) /* pos 66:64 */;
		echo '>
                    </div>
                </div>
';
		$this->createTemplate('partial_configurable_options.latte', ['product' => $product, 'request' => $request] + $this->params, 'include')->renderToContentType('html') /* pos 69:17 */;
		$this->createTemplate('recommendations-modal.latte', ['product' => $product] + $this->params, 'include')->renderToContentType('html') /* pos 70:17 */;
		echo '            </section>
            <aside class="wh-summary-stack">
                <div class="wh-card">
                    <div class="wh-card-body">
                        <h2 class="wh-section-title">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Domain order summary')) /* pos 75:54 */;
		echo '</h2>
';
		$this->createTemplate('partial_currency.latte', $this->params, 'include')->renderToContentType('html') /* pos 76:25 */;
		echo '                        <hr>
';
		$this->createTemplate('partial_pricing.latte', ['product' => $product, 'pricing' => $pricing, 'periods' => $periods, 'request' => $request] + $this->params, 'include')->renderToContentType('html') /* pos 78:25 */;
		echo '                    </div>
                </div>
';
		$this->createTemplate('partial_addons.latte', ['product' => $product] + $this->params, 'include')->renderToContentType('html') /* pos 81:17 */;
		echo '            </aside>
        </div>
    </form>
';
	}


	/** {block js} on line 87 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$currency = $guest->cart_get_currency() /* pos 88:1 */;
		$currency_code = $currency['code'] /* pos 89:1 */;
		$year_label = ($this->filters->trans)(' Year/s @ ') /* pos 90:1 */;
		echo '<script>
    (function() {
        var buttons = document.querySelectorAll(\'[data-domain-product-pane]\');
        var actionField = document.getElementById(\'domain-product-action\');
        var yearLabel = ';
		echo LR\Helpers::escapeJs(json_encode($year_label)) /* pos 95:25 */;
		echo ';
        var currencyRate = ';
		echo LR\Helpers::escapeJs($currency['conversion_rate']) /* pos 96:28 */;
		echo ';
        var currencyCode = ';
		echo LR\Helpers::escapeJs(json_encode($currency_code)) /* pos 97:28 */;
		echo ';

        buttons.forEach(function(button) {
            button.addEventListener(\'click\', function() {
                buttons.forEach(function(item) {
                    item.classList.remove(\'active\');
                });
                document.querySelectorAll(\'[id^="domain-product-pane-"]\').forEach(function(pane) {
                    pane.classList.remove(\'is-active\');
                });
                button.classList.add(\'active\');
                document.getElementById(\'domain-product-pane-\' + button.getAttribute(\'data-domain-product-pane\')).classList.add(\'is-active\');
                if (actionField) {
                    actionField.value = button.getAttribute(\'data-domain-product-pane\');
                }
            });
        });

        $(\'#domain-product-check\').on(\'click\', function() {
            var sld = $(\'input[name="register_sld"]\').val();
            var tld = $(\'select[name="register_tld"]\').val();

            bb.post(\'guest/servicedomain/check\', { sld: sld, tld: tld }, function() {
                bb.post(\'guest/servicedomain/pricing\', { tld: tld }, function(result) {
                    var select = $(\'#registration-years\');
                    select.find(\'option\').remove();

                    for (var i = 1; i < 6; i++) {
                        select.append(new Option(i + yearLabel + bb.currency(result.price_registration, currencyRate, currencyCode, i), i));
                    }

                    $(\'.onAfterDomainCheck\').fadeIn(\'fast\');
                });
            });

            return false;
        });

        $(\'#domain-product-transfer-check\').on(\'click\', function() {
            var sld = $(\'input[name="transfer_sld"]\').val();
            var tld = $(\'select[name="transfer_tld"]\').val();

            bb.post(\'guest/servicedomain/can_be_transferred\', { sld: sld, tld: tld }, function() {
                bb.post(\'guest/servicedomain/pricing\', { tld: tld }, function(result) {
                    $(\'#domain-product-transfer-price\').text(bb.currency(result.price_transfer, currencyRate, currencyCode));
                    $(\'#domain-product-transfer-config\').fadeIn(\'fast\');
                });
            });

            return false;
        });

        if ($(".addons").length) {
            $(\'#order-button\').one(\'click\', function() {
                $(this).hide();
                $(\'.addons\').slideDown(\'fast\');

                return false;
            });
        }

        $(\'.addon-period-selector\').on(\'change\', function() {
            var rel = $(this).attr(\'rel\');
            $(\'#\' + rel + \' span\').hide();
            $(\'#\' + rel + \' span.\' + $(this).val()).fadeIn();
        }).trigger(\'change\');
    })();
</script>
';
	}
}
