<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default/sidebar-categories.latte */
final class Template_dfcc98ca4d extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="wh-catalog-sidebar wh-sidebar-block">
    <div class="wh-catalog-sidebar-shell">
        <div class="wh-catalog-sidebar-head">
            <span class="wh-sidebar-kicker">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Quick Browse')) /* pos 5:45 */;
		echo '</span>
            <div class="d-flex align-items-center justify-content-between gap-3">
                <h2 class="wh-section-title mb-0">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Categories')) /* pos 7:51 */;
		echo '</h2>
                <span class="wh-pill">';
		echo LR\HtmlHelpers::escapeText(($this->filters->length)($categories)) /* pos 8:39 */;
		echo '</span>
            </div>
            <p class="wh-sidebar-copy">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Jump between sections and open products directly from a cleaner storefront layout.')) /* pos 10:40 */;
		echo '</p>
        </div>

        <div class="wh-sidebar-summary">
            <div class="wh-sidebar-stat">
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->length)($categories)) /* pos 15:25 */;
		echo '</strong>
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Sections')) /* pos 16:23 */;
		echo '</span>
            </div>
            <div class="wh-sidebar-stat">
                <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Live')) /* pos 19:25 */;
		echo '</strong>
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Catalog')) /* pos 20:23 */;
		echo '</span>
            </div>
        </div>

        <div class="wh-catalog-sidebar-links">
';
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($categories, $ʟ_it ?? null) as $category) /* pos 25:13 */ {
			if (count($category['products'] ?? []) > 0) /* pos 26:17 */ {
				$isDefaultCategory = strtolower($category['title'] ?? '') === 'default' /* pos 27:21 */;
				echo '                    <a class="wh-sidebar-anchor" href="';
				echo LR\HtmlHelpers::escapeQuotes(json_encode('#category-' . $category['id'])) /* pos 28:56 */;
				echo '" onclick="window.location.hash=\'category-';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeJs($category['id'])) /* pos 28:153 */;
				echo '\'; return false;">
                        <span class="wh-sidebar-anchor-copy">
                            <strong>';
				if ($isDefaultCategory) /* pos 30:37 */ {
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Products')) /* pos 30:60 */;
				} else /* pos 30:79 */ {
					echo LR\HtmlHelpers::escapeText($category['title']) /* pos 30:85 */;
				}
				echo '</strong>
                            <small>
';
				if ($category['description']) /* pos 32:33 */ {
					echo '                                    ';
					echo LR\HtmlHelpers::escapeText(($this->filters->truncate)(($this->filters->stripHtml)($category['description']), 52)) /* pos 33:37 */;
					echo "\n";
				} else /* pos 34:33 */ {
					echo '                                    ';
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Browse this category')) /* pos 35:37 */;
					echo "\n";
				}
				echo '                            </small>
                        </span>
                        <span class="wh-sidebar-anchor-count">';
				echo LR\HtmlHelpers::escapeText(count($category['products'] ?? [])) /* pos 39:63 */;
				echo '</span>
                    </a>
';
			}
		}
		if ($iterator->isEmpty()) /* pos 42:13 */ {
			echo '                <div class="text-secondary small">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No categories available.')) /* pos 43:51 */;
			echo '</div>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '        </div>
    </div>
</div>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['category' => '25'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$categories = $categories ?? $guest->product_category_get_list(['per_page' => 100])['list'] ?? [] /* pos 1:1 */;
		return get_defined_vars();
	}
}
