<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default/recommendations-modal.latte */
final class Template_5231ab221a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if (($this->filters->length)($product['addons'] ?? [])) /* pos 1:1 */ {
			echo '<div class="wh-card mt-4">
    <div class="wh-card-body">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h2 class="wh-section-title mb-0">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Recommended extras')) /* pos 5:47 */;
			echo '</h2>
            <span class="wh-pill">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Addons')) /* pos 6:35 */;
			echo '</span>
        </div>
        <div class="row g-3">
';
			foreach ($product['addons'] as $addon) /* pos 9:13 */ {
				echo '                <div class="col-md-6">
                    <div class="border rounded-3 p-3 h-100">
';
				$addonPrice = 0 /* pos 12:25 */;
				if ($addon->pricing->type === 'recurrent') /* pos 13:25 */ {
					foreach ($addon->pricing->recurrent as $periodCode => $periodPrice) /* pos 14:29 */ {
						if ($periodPrice->enabled && $addonPrice == 0) /* pos 15:33 */ {
							$addonPrice = $periodPrice->price + $periodPrice->setup /* pos 16:37 */;
						}

					}

				} elseif ($addon->pricing->type === 'once') /* pos 19:25 */ {
					$addonPrice = $addon->pricing->once->price + $addon->pricing->once->setup /* pos 20:29 */;
				}

				echo '                        <h3 class="h6 fw-bold mb-1">';
				echo LR\HtmlHelpers::escapeText($addon->title) /* pos 22:53 */;
				echo '</h3>
                        <div class="small text-secondary mb-2">';
				echo LR\HtmlHelpers::escapeText(($this->filters->bbmd)($addon->description)) /* pos 23:64 */;
				echo '</div>
                        <div class="text-success fw-semibold">
';
				if ($addon->pricing->type === 'free') /* pos 25:29 */ {
					echo '                                ';
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Included')) /* pos 26:33 */;
					echo "\n";
				} else /* pos 27:29 */ {
					echo '                                ';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($addonPrice)) /* pos 28:33 */;
					echo "\n";
				}
				echo '                        </div>
                    </div>
                </div>
';

			}

			echo '        </div>
    </div>
</div>
';
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['addon' => '9', 'periodCode' => '14', 'periodPrice' => '14'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
