<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default\configureproduct.latte */
final class Template_031a9d41f3 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'head' => 'blockHead', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 4:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 5:1 */;
		echo "\n";
		$this->renderBlock('content_before', get_defined_vars()) /* pos 7:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 9:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 116:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['code' => '35, 88', 'period' => '35, 88'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_public.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 2:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 4 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText($product['title']) /* pos 4:19 */;
	}


	/** {block head} on line 5 */
	public function blockHead(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('shared/_styles.latte', $this->params, 'include')->renderToContentType('html') /* pos 5:13 */;
	}


	/** {block content_before} on line 7 */
	public function blockContent_before(array $ʟ_args): void
	{
	}


	/** {block content} on line 9 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="gm-order-page" style="padding: 4rem 0;">
    <div class="container container-md">
';
		$periods = $guest->system_periods /* pos 12:9 */;
		$pricing = $product['pricing'] /* pos 13:9 */;
		echo '        
        <h1 class="mb-3" style="font-weight: 800; font-size: 2.5rem; color: #fff;">';
		echo LR\HtmlHelpers::escapeText($product['title']) /* pos 15:84 */;
		echo '</h1>
        
        <div class="gm-breadcrumb">
            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('order'))) /* pos 18:24 */;
		echo ' class="text-decoration-none" style="color: inherit;">1. Select product</a> <span class="mx-2">/</span> 
            <span class="active">2. Configure - ';
		echo LR\HtmlHelpers::escapeText($product['title']) /* pos 19:49 */;
		echo '</span> <span class="mx-2">/</span> 
            3. Confirm <span class="mx-2">/</span> 
            4. Checkout
        </div>

        <form method="post" class="api-form" data-api-url="guest/cart/add_item"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->link)('cart')) /* pos 24:102 */;
		echo '>
            <div class="row gx-4">
                <div class="col-lg-8 mb-4">
                    <div class="gm-order-box h-100">
                        <div class="gm-order-title">Plan details</div>
                        
                        <!-- Billing Cycle -->
';
		if ($pricing['type'] == 'recurrent') /* pos 31:25 */ {
			echo '                        <div class="mb-4">
                            <label class="form-label text-white fw-bold mb-3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Billing Cycle')) /* pos 33:79 */;
			echo '</label>
                            <div class="d-flex flex-wrap gap-2" id="period-selector">
';
			foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($pricing['recurrent'], $ʟ_it ?? null) as $code => $period) /* pos 35:33 */ {
				if ($period->enabled) /* pos 36:33 */ {
					echo '                                <div class="gm-period-box ';
					if ($request->period == $code || !$request->period && $iterator->first) /* pos 37:59 */ {
						echo 'active';
					}
					echo '"';
					echo LR\HtmlHelpers::formatDataAttribute(' data-period', $code) /* pos 37:159 */;
					echo ' style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 1rem; cursor: pointer; flex: 1; min-width: 120px; text-align: center; transition: all 0.3s; background: rgba(0,0,0,0.2);">
                                    <div class="fw-bold mb-1 text-white period-title">';
					echo LR\HtmlHelpers::escapeText(($this->filters->period_title)($period)) /* pos 38:87 */;
					echo '</div>
                                    <div class="text-muted small period-price">';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($period->price)) /* pos 39:80 */;
					echo '</div>
                                    <input type="radio" name="period"';
					echo LR\HtmlHelpers::formatAttribute(' value', $code) /* pos 40:79 */;
					echo ' class="d-none" ';
					if ($request->period == $code || !$request->period && $iterator->first) /* pos 40:102 */ {
						echo 'checked="checked"';
					}
					echo '>
                                </div>
';
				}

			}
			$iterator = $ʟ_it = $ʟ_it->getParent();

			echo '                            </div>
                        </div>
';
		} elseif ($pricing['type'] == 'free') /* pos 46:25 */ {
			echo '                        <div class="mb-4">
                            <div class="alert alert-success" style="background: rgba(40, 167, 69, 0.1); border: 1px solid rgba(40, 167, 69, 0.2); color: #28a745; border-radius: 12px;">
                                <i class="fa fa-gift me-2"></i> This product is completely free!
                            </div>
                        </div>
';
		} elseif ($pricing['type'] == 'once') /* pos 52:25 */ {
			echo '                        <div class="mb-4">
                            <div class="gm-period-box active" style="border: 1px solid var(--gm-accent); border-radius: 12px; padding: 1rem; text-align: center; background: rgba(0,0,0,0.2);">
                                <div class="fw-bold mb-1 text-white">One-time payment</div>
                                <div class="text-muted small">';
			echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($pricing['once']['price'])) /* pos 56:63 */;
			echo '</div>
                            </div>
                        </div>
';
		}


		echo '
                        <!-- Configuration Options -->
                        <div class="mb-4">
';
		if ($product['type'] === 'pterodactyl' || $product['type'] === 'servicepterodactyl') /* pos 63:29 */ {
			$this->createTemplate('partial_pterodactyl_order.latte', ['product' => $product] + $this->params, 'include')->renderToContentType('html') /* pos 64:34 */;
		}
		$this->createTemplate('partial_configurable_options.latte', ['product' => $product, 'request' => $request] + $this->params, 'include')->renderToContentType('html') /* pos 66:29 */;
		echo '                        </div>

                        <!-- Advanced Addons -->
';
		if (($this->filters->length)($product['addons']) > 0) /* pos 70:25 */ {
			echo '                        <div class="mb-4">
                            <label class="form-label text-white fw-bold mb-3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Extra Add-Ons')) /* pos 72:79 */;
			echo '</label>
';
			$this->createTemplate('partial_addons.latte', ['product' => $product] + $this->params, 'include')->renderToContentType('html') /* pos 73:29 */;
			echo '                        </div>
';
		}
		echo '                    </div>
                </div>

                <div class="col-lg-4 mb-4">
                    <div class="gm-order-box position-sticky" style="top: 2rem;">
                        <div class="gm-order-title">Order summary</div>
                        
                        <div class="d-flex flex-column justify-content-between h-100">
                            <div>
                                <div class="gm-order-price-label">Total price:</div>
                                <div class="gm-order-price-value" id="summary-total-val">
';
		if ($pricing['type'] == 'recurrent') /* pos 87:37 */ {
			foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($pricing['recurrent'], $ʟ_it ?? null) as $code => $period) /* pos 88:41 */ {
				if ($period->enabled && ($request->period == $code || !$request->period && $iterator->first)) /* pos 89:45 */ {
					echo '                                                ';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($period->price)) /* pos 90:49 */;
					echo "\n";
				}

			}
			$iterator = $ʟ_it = $ʟ_it->getParent();

		} elseif ($pricing['type'] == 'once') /* pos 93:37 */ {
			echo '                                        ';
			echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($pricing['once']['price'])) /* pos 94:41 */;
			echo "\n";
		} elseif ($pricing['type'] == 'free') /* pos 95:37 */ {
			echo '                                        ';
			echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(0)) /* pos 96:41 */;
			echo "\n";
		}


		echo '                                </div>
                            </div>
                            
                            <div class="mt-4">
                                <button class="btn btn-gm-success w-100" type="submit" id="order-button">
                                    ORDER NOW
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" name="id"';
		echo LR\HtmlHelpers::formatAttribute(' value', $product['id']) /* pos 110:52 */;
		echo '>
        </form>
    </div>
</div>
';
	}


	/** {block js} on line 116 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$currency = $guest->cart_get_currency() /* pos 117:1 */;
		$currency_code = $currency['code'] /* pos 118:1 */;
		$year_label = ($this->filters->trans)(' Year/s @ ') /* pos 119:1 */;
		echo '<script>
    (function() {
        var domainButtons = document.querySelectorAll(\'[data-domain-pane]\');
        var actionField = document.getElementById(\'hosting-domain-action\');
        var yearLabel = ';
		echo LR\Helpers::escapeJs(json_encode($year_label)) /* pos 124:25 */;
		echo ';
        var currencyRate = ';
		echo LR\Helpers::escapeJs($currency['conversion_rate']) /* pos 125:28 */;
		echo ';
        var currencyCode = ';
		echo LR\Helpers::escapeJs(json_encode($currency_code)) /* pos 126:28 */;
		echo ';

        domainButtons.forEach(function(button) {
            button.addEventListener(\'click\', function() {
                domainButtons.forEach(function(item) {
                    item.classList.remove(\'active\');
                });
                document.querySelectorAll(\'.wh-domain-pane\').forEach(function(pane) {
                    pane.classList.remove(\'is-active\');
                });
                button.classList.add(\'active\');
                document.getElementById(\'domain-pane-\' + button.getAttribute(\'data-domain-pane\')).classList.add(\'is-active\');
                if (actionField) {
                    actionField.value = button.getAttribute(\'data-domain-pane\');
                }
            });
        });

        $(\'#hosting-domain-check\').on(\'click\', function() {
            var sld = $(\'input[name="domain[register_sld]"]\').val();
            var tld = $(\'select[name="domain[register_tld]"]\').val();

            bb.post(\'guest/servicedomain/check\', { sld: sld, tld: tld }, function() {
                bb.post(\'guest/servicedomain/pricing\', { tld: tld }, function(result) {
                    var select = $(\'#hosting-domain-years\');
                    select.find(\'option\').remove();

                    for (var i = 1; i < 6; i++) {
                        select.append(new Option(i + yearLabel + bb.currency(result.price_registration, currencyRate, currencyCode, i), i));
                    }

                    $(\'#hosting-domain-config\').fadeIn(\'fast\');
                });
            });

            return false;
        });

        $(\'#hosting-transfer-check\').on(\'click\', function() {
            var sld = $(\'input[name="domain[transfer_sld]"]\').val();
            var tld = $(\'select[name="domain[transfer_tld]"]\').val();

            bb.post(\'guest/servicedomain/can_be_transferred\', { sld: sld, tld: tld }, function() {
                bb.post(\'guest/servicedomain/pricing\', { tld: tld }, function(result) {
                    $(\'#hosting-transfer-price\').text(bb.currency(result.price_transfer, currencyRate, currencyCode));
                    $(\'#hosting-transfer-config\').fadeIn(\'fast\');
                });
            });

            return false;
        });

        if ($(".addons").length && $(".addons").is(\':hidden\')) {
            $(\'#order-button\').one(\'click\', function() {
                $(this).hide();
                $(\'.addons\').slideDown(\'fast\');

                return false;
            });
        }

        $(\'#period-selector\').on(\'change\', function() {
            $(\'.period\').hide();
            $(\'.period.\' + $(this).val()).show();
        }).trigger(\'change\');

        $(\'.addon-period-selector\').on(\'change\', function() {
            var rel = $(this).attr(\'rel\');
            $(\'#\' + rel + \' span\').hide();
            $(\'#\' + rel + \' span.\' + $(this).val()).fadeIn();
        }).trigger(\'change\');
    })();
</script>
';
	}
}
