<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\orderform\default\viewcart.latte */
final class Template_7608a3c312 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'head' => 'blockHead', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 4:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 5:1 */;
		$this->renderBlock('content_before', get_defined_vars()) /* pos 6:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 8:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 338:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['gtw' => '180', 'item' => '231', 'selection' => '248'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_public.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 2:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 4 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Shopping cart')) /* pos 4:19 */;
	}


	/** {block head} on line 5 */
	public function blockHead(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('shared/_styles.latte', $this->params, 'include')->renderToContentType('html') /* pos 5:13 */;
	}


	/** {block content_before} on line 6 */
	public function blockContent_before(array $ʟ_args): void
	{
	}


	/** {block content} on line 8 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="gm-order-page wh-checkout-shell">
    <div class="container container-md">
        <div class="wh-page-header wh-page-header--checkout text-center">
            <h1 class="wh-page-title">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Checkout')) /* pos 12:39 */;
		echo '</h1>
            <p class="wh-page-subtitle">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Confirm your selection, sign in or register inline, then complete payment without leaving this screen.')) /* pos 13:41 */;
		echo '</p>
        </div>

        <div class="wh-flow-steps mb-4">
            <a class="wh-flow-step is-done"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('order'))) /* pos 17:53 */;
		echo '>
                <span class="wh-flow-step-index">1</span>
                <span class="wh-flow-step-label">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Select product')) /* pos 19:50 */;
		echo '</span>
            </a>
            <div class="wh-flow-step is-done">
                <span class="wh-flow-step-index">2</span>
                <span class="wh-flow-step-label">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Configure')) /* pos 23:50 */;
		echo '</span>
            </div>
            <div class="wh-flow-step is-active">
                <span class="wh-flow-step-index">3</span>
                <span class="wh-flow-step-label">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Confirm')) /* pos 27:50 */;
		echo '</span>
            </div>
            <div class="wh-flow-step">
                <span class="wh-flow-step-index">4</span>
                <span class="wh-flow-step-label">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Checkout')) /* pos 31:50 */;
		echo '</span>
            </div>
        </div>

';
		$cart = $guest->cart_get() /* pos 35:9 */;
		$tax_amount = 0 /* pos 36:9 */;
		$required_fields = $guest->client_required() /* pos 37:9 */;
		if ($client && $client->client_is_taxable) /* pos 38:9 */ {
			$tax_rate = $client->invoice_get_tax_rate /* pos 39:13 */;
			$tax_amount = $cart->total * $tax_rate / 100 /* pos 40:13 */;
		}
		$enough_in_balance = $client && $client->client_balance_get_total >= $cart->total /* pos 42:9 */;
		$gateway_count = 0 /* pos 43:9 */;
		echo "\n";
		if (($this->filters->length)($cart->items) > 0) /* pos 45:9 */ {
			echo '            <div class="row gx-4">
                <div class="col-xl-8 mb-4">
';
			if (!$client) /* pos 48:21 */ {
				echo '                        <div class="wh-card mb-4" id="checkout-auth">
                            <div class="wh-card-body">
                                <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
                                    <h2 class="wh-section-title mb-0">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('You are not logged in')) /* pos 52:71 */;
				echo '</h2>
                                    <span class="wh-pill">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Secure checkout')) /* pos 53:59 */;
				echo '</span>
                                </div>
                                <p class="text-secondary mb-3">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Use login or create an account right here. After success, the page refreshes and you can finish checkout immediately.')) /* pos 55:64 */;
				echo '</p>

                                <div class="wh-auth-tabs mb-3">
                                    <button type="button" class="wh-auth-tab is-active" data-auth-target="login">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Login')) /* pos 58:114 */;
				echo '</button>
                                    <button type="button" class="wh-auth-tab" data-auth-target="register">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register')) /* pos 59:107 */;
				echo '</button>
                                </div>

                                <div class="wh-auth-panel is-active" data-auth-panel="login">
                                    <form method="post"';
				echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/guest/client/login'))) /* pos 63:67 */;
				echo ' class="api-form wh-auth-form"';
				echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->link)('/cart')) /* pos 63:150 */;
				echo '>
                                        <div class="row g-3">
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-login-email">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Email address')) /* pos 66:102 */;
				echo '</label>
                                                <input class="form-control" id="checkout-login-email" type="email" name="email"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->email) /* pos 67:137 */;
				echo ' required>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-login-password">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password')) /* pos 70:105 */;
				echo '</label>
                                                <input class="form-control" id="checkout-login-password" type="password" name="password" required>
                                            </div>
                                        </div>
                                        <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mt-3">
                                            <div class="form-check mb-0">
                                                <input class="form-check-input" id="checkout-login-remember" type="checkbox" name="remember" checked>
                                                <label class="form-check-label" for="checkout-login-remember">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Remember me')) /* pos 77:111 */;
				echo '</label>
                                            </div>
                                            <a class="small"';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('reset-password'))) /* pos 79:70 */;
				echo '>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reset password')) /* pos 79:92 */;
				echo '</a>
                                        </div>
                                        <button class="btn btn-gm-success mt-3 w-100" type="submit">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Login and continue')) /* pos 81:101 */;
				echo '</button>
                                    </form>
                                </div>

                                <div class="wh-auth-panel" data-auth-panel="register">
                                    <form method="post"';
				echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/guest/client/create'))) /* pos 86:67 */;
				echo ' class="api-form wh-auth-form"';
				echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->link)('/cart')) /* pos 86:151 */;
				echo '>
                                        <input type="hidden" name="auto_login" value="1">

                                        <div class="row g-3">
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-register-email">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Email address')) /* pos 91:105 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-email" type="email" name="email"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->email) /* pos 92:140 */;
				echo ' required>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-register-company">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Company')) /* pos 95:107 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-company" type="text" name="company"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->company) /* pos 96:143 */;
				echo '>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-register-first">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('First name')) /* pos 99:105 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-first" type="text" name="first_name"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->first_name) /* pos 100:144 */;
				echo ' required>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-register-last">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Last name')) /* pos 103:104 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-last" type="text" name="last_name"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->last_name) /* pos 104:142 */;
				echo ' ';
				if (in_array('last_name', $required_fields ?? [], true)) /* pos 104:164 */ {
					echo 'required';
				}
				echo '>
                                            </div>
                                            <div class="col-12">
                                                <label class="form-label" for="checkout-register-address1">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Address line 1')) /* pos 107:108 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-address1" type="text" name="address_1"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->address_1) /* pos 108:146 */;
				echo ' ';
				if (in_array('address_1', $required_fields ?? [], true)) /* pos 108:168 */ {
					echo 'required';
				}
				echo '>
                                            </div>
                                            <div class="col-12">
                                                <label class="form-label" for="checkout-register-address2">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Address line 2')) /* pos 111:108 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-address2" type="text" name="address_2"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->address_2) /* pos 112:146 */;
				echo '>
                                            </div>
                                            <div class="col-md-4">
                                                <label class="form-label" for="checkout-register-city">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('City')) /* pos 115:104 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-city" type="text" name="city"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->city) /* pos 116:137 */;
				echo ' ';
				if (in_array('city', $required_fields ?? [], true)) /* pos 116:154 */ {
					echo 'required';
				}
				echo '>
                                            </div>
                                            <div class="col-md-4">
                                                <label class="form-label" for="checkout-register-state">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('State')) /* pos 119:105 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-state" type="text" name="state"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->state) /* pos 120:139 */;
				echo ' ';
				if (in_array('state', $required_fields ?? [], true)) /* pos 120:157 */ {
					echo 'required';
				}
				echo '>
                                            </div>
                                            <div class="col-md-4">
                                                <label class="form-label" for="checkout-register-postcode">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Zip / Postal code')) /* pos 123:108 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-postcode" type="text" name="postcode"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->postcode) /* pos 124:145 */;
				echo ' ';
				if (in_array('postcode', $required_fields ?? [], true)) /* pos 124:166 */ {
					echo 'required';
				}
				echo '>
                                            </div>
                                            <div class="col-md-5">
                                                <label class="form-label" for="checkout-register-country">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Country')) /* pos 127:107 */;
				echo '</label>
';
				$this->renderBlock('selectbox', ['country', $guest->system_countries, $request->country, in_array('country', $required_fields ?? [], true), 'Select country', 'checkout-register-country'] + [], 'html') /* pos 128:49 */;
				echo '                                            </div>
                                            <div class="col-md-2">
                                                <label class="form-label" for="checkout-register-phone-cc">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Code')) /* pos 131:108 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-phone-cc" type="text" name="phone_cc"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->phone_cc) /* pos 132:145 */;
				echo ' placeholder="91">
                                            </div>
                                            <div class="col-md-5">
                                                <label class="form-label" for="checkout-register-phone">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Mobile number')) /* pos 135:105 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-phone" type="text" name="phone"';
				echo LR\HtmlHelpers::formatAttribute(' value', $request->phone) /* pos 136:139 */;
				echo ' ';
				if (in_array('phone', $required_fields ?? [], true)) /* pos 136:157 */ {
					echo 'required';
				}
				echo '>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-register-password">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password')) /* pos 139:108 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-password" type="password" name="password" required>
                                            </div>
                                            <div class="col-md-6">
                                                <label class="form-label" for="checkout-register-password-confirm">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password confirm')) /* pos 143:116 */;
				echo '</label>
                                                <input class="form-control" id="checkout-register-password-confirm" type="password" name="password_confirm" required>
                                            </div>
                                        </div>

                                        <div class="mt-3">
';
				$this->renderBlock('recaptcha', [], 'html') /* pos 149:45 */;
				echo '                                        </div>
                                        <button class="btn btn-gm-success mt-3 w-100" type="submit">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create account and continue')) /* pos 151:101 */;
				echo '</button>
                                    </form>
                                </div>
                            </div>
                        </div>
';
			} else /* pos 156:21 */ {
				echo '                        <div class="wh-card mb-4">
                            <div class="wh-card-body">
                                <div class="d-flex flex-wrap justify-content-between align-items-center gap-2">
                                    <div>
                                        <h2 class="wh-section-title mb-1">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Signed in and ready')) /* pos 161:75 */;
				echo '</h2>
                                        <p class="text-secondary mb-0">
                                            ';
				echo LR\HtmlHelpers::escapeText($client->email) /* pos 163:45 */;
				echo '
                                            ';
				if ($client->phone ?? false) /* pos 164:45 */ {
					echo ' | ';
					echo LR\HtmlHelpers::escapeText($client->phone_cc ?? '') /* pos 164:78 */;
					echo ' ';
					echo LR\HtmlHelpers::escapeText($client->phone) /* pos 164:104 */;
				}
				echo '
                                        </p>
                                    </div>
                                    <a class="btn btn-outline-primary"';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/logout'))) /* pos 167:80 */;
				echo '>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Use different account')) /* pos 167:97 */;
				echo '</a>
                                </div>
                            </div>
                        </div>
';
			}
			echo '
                    <form method="post"';
			echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/client/cart/checkout'))) /* pos 173:51 */;
			echo ' class="api-form" id="checkout-form" data-api-jsonp="onAfterCartCheckout">
                        <div class="wh-card mb-4">
                            <div class="wh-card-body">
                                <h2 class="wh-section-title mb-3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Payment details')) /* pos 176:67 */;
			echo '</h2>

';
			if ($cart->total && !$enough_in_balance) /* pos 178:33 */ {
				echo '                                    <div class="wh-gateway-list">
';
				foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($guest->invoice_gateways, $ʟ_it ?? null) as $gtw) /* pos 180:41 */ {
					if (in_array($cart->currency->code, $gtw->accepted_currencies, true)) /* pos 181:45 */ {
						$gateway_count = $gateway_count + 1 /* pos 182:49 */;
						echo '                                                <label class="wh-gateway-item">
                                                    <span class="wh-gateway-item-copy">
                                                        <strong>';
						echo LR\HtmlHelpers::escapeText($gtw->title) /* pos 185:65 */;
						echo '</strong>
                                                        <small>';
						echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pay securely via')) /* pos 186:64 */;
						echo ' ';
						echo LR\HtmlHelpers::escapeText($gtw->title) /* pos 186:92 */;
						echo '</small>
                                                    </span>
                                                    <span class="wh-gateway-item-radio">
                                                        <input type="radio" name="gateway_id"';
						echo LR\HtmlHelpers::formatAttribute(' value', $gtw->id) /* pos 189:103 */;
						echo ' ';
						echo LR\HtmlHelpers::escapeTag($iterator->first ? 'checked' : '') /* pos 189:114 */;
						echo '>
                                                    </span>
                                                </label>
';
					}

				}
				$iterator = $ʟ_it = $ʟ_it->getParent();

				echo '                                    </div>
';
				if ($gateway_count === 0) /* pos 195:37 */ {
					echo '                                        <p class="small text-danger mt-3 mb-0">';
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No enabled payment gateway currently accepts this cart currency.')) /* pos 196:80 */;
					echo '</p>
';
				}
			} else /* pos 198:33 */ {
				echo '                                    <div class="wh-balance-notice">
                                        <i class="fa fa-check-circle me-2"></i>
                                        ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Your account balance covers this order. No additional online gateway is required.')) /* pos 201:41 */;
				echo '
                                    </div>
';
			}
			echo '
                                <label class="wh-tos-check mt-4" for="checkout-tos">
                                    <input type="checkbox" id="checkout-tos" name="tos" value="1" required>
                                    <span class="wh-tos-copy">
                                        ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('I agree with the')) /* pos 208:41 */;
			echo '
                                        <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/tos'))) /* pos 209:52 */;
			echo ' target="_blank">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Terms of Service')) /* pos 209:82 */;
			echo '</a>
                                    </span>
                                </label>
                            </div>
                        </div>

                        <div class="wh-card mb-4">
                            <div class="wh-card-body">
                                <h2 class="wh-section-title mb-3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Additional notes')) /* pos 217:67 */;
			echo '</h2>
                                <textarea name="notes" class="form-control wh-notes-area" rows="3"';
			echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Tell us anything we should know about your order...')) /* pos 218:115 */;
			echo '></textarea>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-xl-4 mb-4">
                    <div class="wh-card position-sticky wh-summary-panel">
                        <div class="wh-card-body">
                            <h2 class="wh-section-title mb-3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Order summary')) /* pos 227:63 */;
			echo '</h2>

                            <div class="wh-summary-items mb-3">
';
			$total_discount = 0 /* pos 230:33 */;
			foreach ($cart->items as $item) /* pos 231:33 */ {
				$selected_config_options = $item->config_options_data ?? [] /* pos 232:37 */;
				echo '                                    <div class="wh-summary-item">
                                        <div class="d-flex justify-content-between gap-2 mb-1">
                                            <strong class="text-white">';
				echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($item->title, 28)) /* pos 235:72 */;
				echo '</strong>
                                            <strong class="text-white">
';
				if ($item->discount_price) /* pos 237:49 */ {
					echo '                                                    ';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($item->price - $item->discount_price)) /* pos 238:53 */;
					echo "\n";
				} else /* pos 239:49 */ {
					echo '                                                    ';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($item->price)) /* pos 240:53 */;
					echo "\n";
				}
				echo '                                            </strong>
                                        </div>
';
				if (($this->filters->period_title)($item->period) != '-') /* pos 244:41 */ {
					echo '                                            <div class="small text-secondary mb-1">';
					echo LR\HtmlHelpers::escapeText(($this->filters->period_title)($item->period)) /* pos 245:84 */;
					echo '</div>
';
				}
				if (($this->filters->length)($selected_config_options)) /* pos 247:41 */ {
					foreach ($selected_config_options as $selection) /* pos 248:45 */ {
						echo '                                                <div class="small text-secondary d-flex justify-content-between gap-2">
                                                    <span>';
						echo LR\HtmlHelpers::escapeText($selection->option_title) /* pos 250:59 */;
						echo '</span>
                                                    <span>';
						echo LR\HtmlHelpers::escapeText($selection->value_label) /* pos 251:59 */;
						if (($selection->type ?? '') === 'quantity') /* pos 251:84 */ {
							echo ' x';
							echo LR\HtmlHelpers::escapeText($selection->quantity) /* pos 251:132 */;
						}
						echo '</span>
                                                </div>
';

					}

				}
				if ($item->discount_price || $item->discount_setup) /* pos 255:41 */ {
					$total_discount = $total_discount + $item->discount_price + $item->discount_setup /* pos 256:45 */;
				}
				echo '                                    </div>
';

			}

			echo '                            </div>

                            <form';
			echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/guest/cart/apply_promo'))) /* pos 262:45 */;
			echo ' method="post" class="api-form wh-promo-form mb-4" data-api-reload="1">
                                <div class="wh-promo-row">
                                    <input
                                        type="text"
                                        name="promocode"
                                        class="form-control wh-promo-input"';
			echo LR\HtmlHelpers::formatAttribute('
                                        placeholder', ($this->filters->trans)('Promo code')) /* pos 268:56 */;
			echo LR\HtmlHelpers::formatAttribute('
                                        value', $request->promocode ?? $cart->promocode) /* pos 269:49 */;
			echo '
                                        ';
			if ($cart->promocode) /* pos 270:41 */ {
				echo 'readonly';
			}
			echo '
                                        required
                                    >
';
			if ($cart->promocode) /* pos 273:37 */ {
				echo '                                        <button class="btn wh-promo-btn wh-promo-btn-danger" type="button" onclick="bb.post(\'guest/cart/remove_promo\', {}, function(){ window.location.reload(); })">
                                            <i class="fa fa-times"></i>
                                        </button>
';
			} else /* pos 277:37 */ {
				echo '                                        <button class="btn wh-promo-btn" type="submit">
                                            <i class="fa fa-check"></i>
                                        </button>
';
			}
			echo '                                </div>
                            </form>

                            <div class="wh-summary-list mb-4">
                                <div class="wh-summary-row">
                                    <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Subtotal')) /* pos 287:43 */;
			echo '</span>
                                    <strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($cart->subtotal)) /* pos 288:45 */;
			echo '</strong>
                                </div>
';
			if ($total_discount > 0) /* pos 290:33 */ {
				echo '                                    <div class="wh-summary-row">
                                        <span>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Discount')) /* pos 292:47 */;
				echo '</span>
                                        <strong>-';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($total_discount)) /* pos 293:50 */;
				echo '</strong>
                                    </div>
';
			}
			if ($tax_amount > 0) /* pos 296:33 */ {
				echo '                                    <div class="wh-summary-row">
                                        <span>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('VAT')) /* pos 298:47 */;
				echo ' (';
				echo LR\HtmlHelpers::escapeText($tax_rate) /* pos 298:63 */;
				echo '%)</span>
                                        <strong>';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($tax_amount)) /* pos 299:49 */;
				echo '</strong>
                                    </div>
';
			}
			echo '                            </div>

                            <div class="gm-order-price-label mb-1">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Total price')) /* pos 304:68 */;
			echo '</div>
                            <div class="gm-order-price-value mb-3">';
			echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($cart->total + $tax_amount)) /* pos 305:68 */;
			echo '</div>

';
			if ($client) /* pos 307:29 */ {
				echo '                                <button
                                    class="btn btn-gm-success w-100 wh-order-submit"
                                    type="button"
                                    onclick="$(\'#checkout-form\').trigger(\'submit\');"
                                    ';
				if (!$enough_in_balance && $cart->total && $gateway_count === 0) /* pos 312:37 */ {
					echo 'disabled';
				}
				echo '
                                >
                                    ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Place order')) /* pos 314:37 */;
				echo '
                                </button>
';
			} else /* pos 316:29 */ {
				echo '                                <button class="btn btn-gm-success w-100 wh-order-submit" type="button" data-open-auth="login">
                                    ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Login to checkout')) /* pos 318:37 */;
				echo '
                                </button>
';
			}
			echo '                        </div>
                    </div>
                </div>
            </div>
';
		} else /* pos 325:9 */ {
			echo '            <div class="wh-card text-center py-5">
                <div class="wh-card-body">
                    <h2 class="text-white mb-3" style="font-weight: 800;">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Your cart is empty')) /* pos 328:75 */;
			echo '</h2>
                    <p class="text-muted mb-4">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('There are no items in your shopping cart.')) /* pos 329:48 */;
			echo '</p>
                    <a class="btn btn-gm-success px-5"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('order'))) /* pos 330:64 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Order new service')) /* pos 330:79 */;
			echo '</a>
                </div>
            </div>
';
		}
		echo '    </div>
</div>
';
	}


	/** {block js} on line 338 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script>
    function onAfterCartCheckout(result) {
        if (result.invoice_hash) {
            bb.redirect(';
		echo LR\HtmlHelpers::convertJSToRawText(($this->filters->link)('invoice') . '/') /* pos 342:25 */;
		echo ' + result.invoice_hash + \'&auto_redirect=1\');
        } else {
            bb.redirect(';
		echo LR\HtmlHelpers::convertJSToRawText(($this->filters->link)('order/service/manage') . '/') /* pos 344:25 */;
		echo ' + result.order_id);
        }
    }

    (function() {
        function setAuthPanel(mode) {
            document.querySelectorAll(\'[data-auth-target]\').forEach(function(button) {
                button.classList.toggle(\'is-active\', button.getAttribute(\'data-auth-target\') === mode);
            });
            document.querySelectorAll(\'[data-auth-panel]\').forEach(function(panel) {
                panel.classList.toggle(\'is-active\', panel.getAttribute(\'data-auth-panel\') === mode);
            });
        }

        document.querySelectorAll(\'[data-auth-target]\').forEach(function(button) {
            button.addEventListener(\'click\', function() {
                setAuthPanel(button.getAttribute(\'data-auth-target\'));
            });
        });

        document.querySelectorAll(\'[data-open-auth]\').forEach(function(button) {
            button.addEventListener(\'click\', function() {
                setAuthPanel(button.getAttribute(\'data-open-auth\') || \'login\');
                var authCard = document.getElementById(\'checkout-auth\');
                if (authCard) {
                    authCard.scrollIntoView({ behavior: \'smooth\', block: \'start\' });
                }
            });
        });

        if (window.location.hash === \'#register\') {
            setAuthPanel(\'register\');
        }
    })();
</script>
';
	}
}
