<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: partial_message.latte */
final class Template_fc7328bcaa extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		foreach ($flashes ?? [] as $label => $messages) /* pos 1:1 */ {
			foreach ($messages as $msg) /* pos 2:5 */ {
				$normalized = strtolower((string) $label) /* pos 3:9 */;
				if (in_array($normalized, ['error', 'danger'], true)) /* pos 4:9 */ {
					$alert_class = 'alert-danger' /* pos 5:13 */;
					$alert_icon = 'fa-times-circle' /* pos 6:13 */;
				} elseif (in_array($normalized, ['success', 'ok'], true)) /* pos 7:9 */ {
					$alert_class = 'alert-success' /* pos 8:13 */;
					$alert_icon = 'fa-check-circle' /* pos 9:13 */;
				} elseif (in_array($normalized, ['warning', 'warn'], true)) /* pos 10:9 */ {
					$alert_class = 'alert-warning' /* pos 11:13 */;
					$alert_icon = 'fa-exclamation-triangle' /* pos 12:13 */;
				} else /* pos 13:9 */ {
					$alert_class = 'alert-info' /* pos 14:13 */;
					$alert_icon = 'fa-info-circle' /* pos 15:13 */;
				}


				echo '
        <div class="alert ';
				echo LR\HtmlHelpers::escapeAttr($alert_class) /* pos 18:27 */;
				echo ' gm-system-alert d-flex align-items-start gap-3 mb-3" role="alert">
            <i class="fa ';
				echo LR\HtmlHelpers::escapeAttr($alert_icon) /* pos 19:26 */;
				echo ' mt-1"></i>
            <div class="flex-grow-1">
                <div class="gm-system-alert-title">';
				echo LR\HtmlHelpers::escapeText(($this->filters->capitalize)($label)) /* pos 21:52 */;
				echo '</div>
                <div>';
				echo LR\HtmlHelpers::escapeText($msg) /* pos 22:22 */;
				echo '</div>
            </div>
        </div>
';

			}


		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['label' => '1', 'messages' => '1', 'msg' => '2'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
