<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: partial_addons.latte */
final class Template_e1f41f768e extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if (($this->filters->length)($product['addons']) > 0) /* pos 1:1 */ {
			echo '<div class="d-flex flex-wrap gap-2 gm-option-grid">
';
			foreach ($product['addons'] as $addon) /* pos 3:1 */ {
				echo '    <div class="gm-period-box" style="border: 1px solid rgba(255,255,255,0.1); border-radius: 12px; padding: 1rem; cursor: pointer; flex: 1; min-width: 200px; transition: all 0.3s; background: rgba(0,0,0,0.2);">
        <label class="d-block m-0 cursor-pointer w-100">
            <input type="hidden" name="addons[';
				echo LR\HtmlHelpers::escapeAttr($addon->id) /* pos 6:47 */;
				echo ']" value="0">
            <input type="checkbox" name="addons[';
				echo LR\HtmlHelpers::escapeAttr($addon->id) /* pos 7:49 */;
				echo ']" value="1" class="d-none">
            
            <div class="d-flex justify-content-between align-items-center mb-1">
                <div class="fw-bold text-white">';
				echo LR\HtmlHelpers::escapeText($addon->title) /* pos 10:49 */;
				echo '</div>
                <div class="text-success small fw-bold">
';
				$addon_pricing = $addon->pricing /* pos 12:21 */;
				if ($addon_pricing->type === 'recurrent') /* pos 13:21 */ {
					$default_period = $request->period ?? null /* pos 14:25 */;
					if (!$default_period) /* pos 15:25 */ {
						foreach ($addon_pricing->recurrent as $code => $period_prices) /* pos 16:29 */ {
							if (!$default_period && $period_prices->enabled) /* pos 17:33 */ {
								$default_period = $code /* pos 18:37 */;
							}

						}

					}
					$addon_price = $addon_pricing->recurrent[$default_period]->price ?? 0 /* pos 22:25 */;
					if ($addon_price > 0) /* pos 23:25 */ {
						echo '                            + ';
						echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($addon_price)) /* pos 24:31 */;
						echo "\n";
					} else /* pos 25:25 */ {
						echo '                            ';
						echo LR\HtmlHelpers::escapeText(($this->filters->trans)('FREE')) /* pos 26:29 */;
						echo "\n";
					}
				} else /* pos 28:21 */ {
					$addon_price = $addon_pricing->once->price ?? 0 /* pos 29:25 */;
					if ($addon_price > 0) /* pos 30:25 */ {
						echo '                            + ';
						echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($addon_price)) /* pos 31:31 */;
						echo "\n";
					} else /* pos 32:25 */ {
						echo '                            ';
						echo LR\HtmlHelpers::escapeText(($this->filters->trans)('FREE')) /* pos 33:29 */;
						echo "\n";
					}
				}
				echo '                </div>
            </div>
            
';
				if ($addon->description) /* pos 39:13 */ {
					echo '                <div class="text-muted" style="font-size: 0.8rem; line-height: 1.3;">
                    ';
					echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($addon->description, 60)) /* pos 41:21 */;
					echo '
                </div>
';
				}
				echo '        </label>
    </div>
';

			}

			echo '</div>
';
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['addon' => '3', 'code' => '16', 'period_prices' => '16'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
