<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: partial_pricing.latte */
final class Template_875bc772c3 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		if (isset($only_price) && $only_price) /* pos 6:1 */ {
			if ($pricing_type == 'free') /* pos 7:5 */ {
				echo '        ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(0)) /* pos 8:9 */;
				echo "\n";
			} elseif ($pricing_type == 'once') /* pos 9:5 */ {
				$once_price = is_array($pricing_once) ? $pricing_once['price'] ?? 0 : $pricing_once->price ?? 0 /* pos 10:9 */;
				echo '        ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($once_price)) /* pos 11:9 */;
				echo "\n";
			} elseif ($pricing_type == 'recurrent') /* pos 12:5 */ {
				$first_period = null /* pos 13:9 */;
				foreach ($pricing_recurrent ?? [] as $code => $prices) /* pos 14:9 */ {
					if (!$first_period && (is_array($prices) ? $prices['enabled'] ?? false : $prices->enabled ?? false)) /* pos 15:13 */ {
						$first_period = $prices /* pos 16:17 */;
					}

				}

				if ($first_period) /* pos 19:9 */ {
					echo '            ';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(is_array($first_period) ? $first_period['price'] ?? 0 : $first_period->price ?? 0)) /* pos 20:13 */;
					echo "\n";
				}
			}


		} elseif (isset($only_billing) && $only_billing) /* pos 23:1 */ {
			if ($pricing_type == 'recurrent') /* pos 24:5 */ {
				echo '        <select name="period" id="period-selector" class="form-select">
';
				foreach ($pricing_recurrent ?? [] as $code => $prices) /* pos 26:13 */ {
					$price_enabled = is_array($prices) ? $prices['enabled'] ?? false : $prices->enabled ?? false /* pos 27:17 */;
					$price_value = is_array($prices) ? $prices['price'] ?? 0 : $prices->price ?? 0 /* pos 28:17 */;
					$price_setup = is_array($prices) ? $prices['setup'] ?? 0 : $prices->setup ?? 0 /* pos 29:17 */;
					if ($price_enabled) /* pos 30:17 */ {
						echo '                    <option';
						echo LR\HtmlHelpers::formatAttribute(' value', $code) /* pos 31:37 */;
						if ($request->period == $code) /* pos 31:44 */ {
							echo ' selected="selected"';
						}
						echo '>
                        ';
						echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($price_value + $price_setup)) /* pos 32:25 */;
						echo ' ';
						echo LR\HtmlHelpers::escapeText($periods[$code]) /* pos 32:69 */;
						echo '
                    </option>
';
					}

				}

				echo '        </select>
';
			} else /* pos 37:5 */ {
				echo '        <div class="text-white p-2">';
				echo LR\HtmlHelpers::escapeText(($this->filters->capitalize)($pricing_type)) /* pos 38:37 */;
				echo '</div>
';
			}
		} elseif (isset($only_summary) && $only_summary) /* pos 40:1 */ {
			echo '    <div class="lemon-summary-details text-muted mt-2">
        <div class="lemon-summary-item">
            <span>';
			echo LR\HtmlHelpers::escapeText($product['title']) /* pos 43:19 */;
			echo '</span>
            <span>
';
			if ($pricing_type == 'free') /* pos 45:17 */ {
				echo '                    ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(0)) /* pos 46:21 */;
				echo "\n";
			} elseif ($pricing_type == 'once') /* pos 47:17 */ {
				$once_price = is_array($pricing_once) ? $pricing_once['price'] ?? 0 : $pricing_once->price ?? 0 /* pos 48:21 */;
				echo '                    ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($once_price)) /* pos 49:21 */;
				echo "\n";
			} elseif ($pricing_type == 'recurrent') /* pos 50:17 */ {
				$sel_period = $request->period /* pos 51:21 */;
				if (!$sel_period) /* pos 52:21 */ {
					foreach ($pricing_recurrent ?? [] as $code => $prices) /* pos 53:25 */ {
						if (!$sel_period && (is_array($prices) ? $prices['enabled'] ?? false : $prices->enabled ?? false)) /* pos 54:29 */ {
							$sel_period = $code /* pos 55:33 */;
						}

					}

				}
				if ($sel_period && isset($pricing_recurrent[$sel_period])) /* pos 59:21 */ {
					$p = $pricing_recurrent[$sel_period] /* pos 60:25 */;
					echo '                        ';
					echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(is_array($p) ? $p['price'] ?? 0 : $p->price ?? 0)) /* pos 61:25 */;
					echo "\n";
				}
			}


			echo '            </span>
        </div>
        
';
			$total_setup = 0 /* pos 67:9 */;
			if ($pricing_type == 'once') /* pos 68:9 */ {
				$total_setup = is_array($pricing_once) ? $pricing_once['setup'] ?? 0 : $pricing_once->setup ?? 0 /* pos 69:13 */;
			} elseif ($pricing_type == 'recurrent' && $sel_period && isset($pricing_recurrent[$sel_period])) /* pos 70:9 */ {
				$p = $pricing_recurrent[$sel_period] /* pos 71:14 */;
				$total_setup = is_array($p) ? $p['setup'] ?? 0 : $p->setup ?? 0 /* pos 72:14 */;
			}

			echo '        
        <div class="lemon-summary-item">
            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Setup Fees')) /* pos 76:19 */;
			echo ':</span>
            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($total_setup)) /* pos 77:19 */;
			echo '</span>
        </div>
        
        <div class="lemon-summary-total text-white mt-3">
            <span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Total Due Today')) /* pos 81:19 */;
			echo '</span>
            <span class="text-lemon">
';
			if ($pricing_type == 'free') /* pos 83:18 */ {
				echo '                    ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(0)) /* pos 84:21 */;
				echo "\n";
			} elseif ($pricing_type == 'once') /* pos 85:17 */ {
				echo '                    ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($once_price + $total_setup)) /* pos 86:21 */;
				echo "\n";
			} elseif ($pricing_type == 'recurrent' && $sel_period && isset($pricing_recurrent[$sel_period])) /* pos 87:17 */ {
				$p = $pricing_recurrent[$sel_period] /* pos 88:22 */;
				echo '                     ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)((is_array($p) ? $p['price'] ?? 0 : $p->price ?? 0) + $total_setup)) /* pos 89:22 */;
				echo "\n";
			}


			echo '            </span>
        </div>
    </div>
';
		} else /* pos 94:1 */ {
			echo '<div class="total">
';
			if ($pricing && $pricing_type == 'free') /* pos 96:5 */ {
				if ($product['allow_quantity_select']) /* pos 97:9 */ {
					echo '            <h4>';
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Quantity')) /* pos 98:17 */;
					echo ':</h4>
            <input type="text" name="quantity" value="1" class="form-control">
            <hr>
';
				}
				echo '        
        <h2><strong>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Total price')) /* pos 103:21 */;
				echo ':</strong><br>';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)(0)) /* pos 103:57 */;
				echo '</h2>
';
			}
			echo "\n";
			if ($pricing && $pricing_type == 'once') /* pos 106:5 */ {
				if ($product['allow_quantity_select']) /* pos 107:9 */ {
					echo '            <h4>';
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Quantity')) /* pos 108:17 */;
					echo ':</h4>
            <input type="text" name="quantity" value="1" class="form-control">
            <hr>
';
				}
				echo "\n";
				$once_price = is_array($pricing_once) ? $pricing_once['price'] ?? 0 : $pricing_once->price ?? 0 /* pos 113:9 */;
				$once_setup = is_array($pricing_once) ? $pricing_once['setup'] ?? 0 : $pricing_once->setup ?? 0 /* pos 114:9 */;
				echo '        <h2><strong>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Total price')) /* pos 115:21 */;
				echo ':</strong><br> ';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($once_price + $once_setup)) /* pos 115:58 */;
				echo '</h2>
';
			}
			echo "\n";
			if ($pricing && $pricing_type == 'recurrent') /* pos 118:5 */ {
				if ($product['allow_quantity_select']) /* pos 119:9 */ {
					echo '            <h4>';
					echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Quantity:')) /* pos 120:17 */;
					echo ':</h4>
            <input type="text" name="quantity" value="1" class="form-control">
            <hr>
';
				}
				echo '            
        <select name="period" id="period-selector" class="form-select">
';
				foreach ($pricing_recurrent ?? [] as $code => $prices) /* pos 126:13 */ {
					$price_enabled = is_array($prices) ? $prices['enabled'] ?? false : $prices->enabled ?? false /* pos 127:17 */;
					$price_value = is_array($prices) ? $prices['price'] ?? 0 : $prices->price ?? 0 /* pos 128:17 */;
					$price_setup = is_array($prices) ? $prices['setup'] ?? 0 : $prices->setup ?? 0 /* pos 129:17 */;
					if ($price_enabled) /* pos 130:17 */ {
						echo '                    <option';
						echo LR\HtmlHelpers::formatAttribute(' value', $code) /* pos 131:37 */;
						if ($request->period == $code) /* pos 131:44 */ {
							echo ' selected="selected"';
						}
						echo '>';
						echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($price_value + $price_setup)) /* pos 131:102 */;
						echo ' ';
						echo LR\HtmlHelpers::escapeText($periods[$code]) /* pos 131:146 */;
						echo '</option>
';
					}

				}

				echo '        </select>
        <hr>

';
				foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($pricing_recurrent ?? [], $ʟ_it ?? null) as $code => $prices) /* pos 137:9 */ {
					$price_enabled = is_array($prices) ? $prices['enabled'] ?? false : $prices->enabled ?? false /* pos 138:13 */;
					$price_value = is_array($prices) ? $prices['price'] ?? 0 : $prices->price ?? 0 /* pos 139:13 */;
					$price_setup = is_array($prices) ? $prices['setup'] ?? 0 : $prices->setup ?? 0 /* pos 140:13 */;
					if ($price_enabled && $price_setup > 0) /* pos 141:13 */ {
						echo '                <div class="period ';
						echo LR\HtmlHelpers::escapeAttr($code) /* pos 142:36 */;
						echo '" style="';
						if (!$iterator->first) /* pos 142:52 */ {
							echo 'display: none;';
						}
						echo '">
                    <table class="table">
                        <tr>
                            <td>';
						echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Price')) /* pos 145:33 */;
						echo '</td>
                            <td>';
						echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($price_value)) /* pos 146:33 */;
						echo '</td>
                        </tr>
                        <tr>
                            <td>';
						echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Setup Price')) /* pos 149:33 */;
						echo '</td>
                            <td>';
						echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($price_setup)) /* pos 150:33 */;
						echo '</td>
                        </tr>
                    </table>
                </div>
';
					}

				}
				$iterator = $ʟ_it = $ʟ_it->getParent();

			}
			echo '</div>

<div class="d-grid">
';
			if (($this->filters->length)($product['addons']) > 0) /* pos 160:5 */ {
				echo '        <button class="btn btn-success btn-lg" type="submit" id="order-button">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Continue')) /* pos 161:80 */;
				echo '</button>
';
			} else /* pos 162:5 */ {
				echo '        <button class="btn btn-success btn-lg" type="submit" id="order-button">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Order now')) /* pos 163:80 */;
				echo '</button>
';
			}
			echo '</div>
';
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['code' => '14, 26, 53, 126, 137', 'prices' => '14, 26, 53, 126, 137'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$pricing = $pricing ?? $product['pricing'] ?? null /* pos 1:1 */;
		$pricing_type = is_array($pricing) ? $pricing['type'] ?? null : $pricing->type ?? null /* pos 2:1 */;
		$pricing_once = is_array($pricing) ? $pricing['once'] ?? null : $pricing->once ?? null /* pos 3:1 */;
		$pricing_recurrent = is_array($pricing) ? $pricing['recurrent'] ?? null : $pricing->recurrent ?? null /* pos 4:1 */;
		return get_defined_vars();
	}
}
