<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: partial_styles.latte */
final class Template_f4bc95349f extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin" />
<link href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700&family=Rajdhani:wght@600;700&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 26:30 */;
		echo 'css/min.css?v=';
		echo LR\HtmlHelpers::escapeAttr($version) /* pos 26:57 */;
		echo '" type="text/css" media="screen" />
<link rel="stylesheet" href="';
		echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 27:30 */;
		echo 'css/admin-panel.css?v=';
		echo LR\HtmlHelpers::escapeAttr($version) /* pos 27:65 */;
		echo '&ui=20260307-10" type="text/css" media="screen" />
';
	}


	public function prepare(): array
	{
		extract($this->params);

		$version = $guest->system_version() /* pos 22:1 */;
		return get_defined_vars();
	}
}
