<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: partial_menu_top.latte */
final class Template_ab80729c38 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '                        <ul class="menu_body" hidden data-admin-dropdown-menu>
';
		if ($admin->system_is_allowed(['mod' => 'order'])) /* pos 23:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('order#tab-new'))) /* pos 24:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Order')) /* pos 24:77 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($admin->system_is_allowed(['mod' => 'invoice'])) /* pos 27:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('invoice#tab-new'))) /* pos 28:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Invoice')) /* pos 28:79 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($admin->system_is_allowed(['mod' => 'client'])) /* pos 31:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('client#tab-new'))) /* pos 32:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Client')) /* pos 32:78 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($admin->system_is_allowed(['mod' => 'product'])) /* pos 35:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('product#tab-new'))) /* pos 36:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Product')) /* pos 36:79 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($admin->system_is_allowed(['mod' => 'support'])) /* pos 39:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('support#tab-new'))) /* pos 40:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Support ticket')) /* pos 40:79 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($admin->system_is_allowed(['mod' => 'staff'])) /* pos 43:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('extension/settings/staff#tab-new'))) /* pos 44:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Staff member')) /* pos 44:96 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($guest->extension_is_on(['mod' => 'news']) && $admin->system_is_allowed(['mod' => 'news'])) /* pos 47:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('news#tab-new'))) /* pos 48:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Announcement')) /* pos 48:76 */;
			echo '</a></li>
';
		}
		echo '                            
';
		if ($guest->extension_is_on(['mod' => 'forum']) && $admin->system_is_allowed(['mod' => 'forum'])) /* pos 51:29 */ {
			echo '                            <li><a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('forum#tab-new'))) /* pos 52:44 */;
			echo ' title="">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Forum topic')) /* pos 52:77 */;
			echo '</a></li>
';
		}
		echo '                        </ul>
';
	}
}
