<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: partial_currency.latte */
final class Template_5c51c613c2 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		if (($this->filters->length)($currencies) > 1) /* pos 3:1 */ {
			echo '    <h4>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Select currency')) /* pos 4:9 */;
			echo '</h2>
    <div class="form-group">
        <select name="currency" class="currency_selector form-control">
';
			$selected = $guest->cart_get_currency()->code /* pos 7:9 */;
			echo '        
';
			foreach ($currencies as $code => $title) /* pos 9:9 */ {
				echo '            <option';
				echo LR\HtmlHelpers::formatAttribute(' value', $code) /* pos 10:29 */;
				echo ' class="currency_';
				echo LR\HtmlHelpers::escapeAttr($code) /* pos 10:53 */;
				echo '"';
				if ($code == $selected) /* pos 10:61 */ {
					echo ' selected="selected"';
				}
				echo '>';
				echo LR\HtmlHelpers::escapeText($code) /* pos 10:112 */;
				echo ' - ';
				echo LR\HtmlHelpers::escapeText($title) /* pos 10:122 */;
				echo '</option>
';

			}

			echo '        </select>
    </div>
';
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['code' => '9', 'title' => '9'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$currencies = $guest->currency_get_pairs() ?? [] /* pos 1:1 */;
		return get_defined_vars();
	}
}
