<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_support_tickets.latte */
final class Template_d4813126f5 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'modals' => 'blockModals'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 8:1 */;
		echo '

';
		$this->renderBlock('content_before', get_defined_vars()) /* pos 10:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 35:1 */;
		echo "\n";
		$this->renderBlock('modals', get_defined_vars()) /* pos 82:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['i' => '38, 67, 70', 'ticket' => '38', 'category' => '67', 'article' => '70'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 3:1 */;
		$tickets = $client->support_ticket_get_list(['per_page' => 10, 'page' => $request->page]) /* pos 5:1 */;
		$has_tickets = ($this->filters->length)($tickets['list'] ?? []) > 0 /* pos 6:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 8 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Help & Support')) /* pos 8:19 */;
	}


	/** {block content_before} on line 10 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="gm-page-heading">
        <h1>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Help & Support')) /* pos 12:13 */;
		echo '</h1>
    </div>
    <div class="gm-client-tabs">
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('kb'))) /* pos 15:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('General')) /* pos 15:30 */;
		echo '</a>
        <a class="active"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('support'))) /* pos 16:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Support Tickets')) /* pos 16:50 */;
		echo '</a>
    </div>

';
		if (!($has_tickets ?? false)) /* pos 19:9 */ {
			echo '            <p class="gm-support-empty">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('You have no active support tickets')) /* pos 20:41 */;
			echo '</p>
';
		}
		echo '        <div class="gm-support-actions">
            <a class="gm-support-card" data-bs-toggle="modal" data-bs-target="#ticket-order">
                <i class="fa fa-desktop"></i>
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Open Ticket')) /* pos 25:23 */;
		echo '</span>
            </a>
            <a class="gm-support-card"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('kb'))) /* pos 27:48 */;
		echo '>
                <i class="fa fa-book"></i>
                <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Browse Help')) /* pos 29:23 */;
		echo '</span>
            </a>
        </div>
    </div>
';
	}


	/** {block content} on line 35 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if ($has_tickets ?? false) /* pos 36:5 */ {
			echo '        <div class="list-group mb-3">
';
			foreach ($tickets['list'] ?? [] as $i => $ticket) /* pos 38:13 */ {
				echo '                <a href="';
				echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('support/ticket')) /* pos 39:26 */;
				echo '/';
				echo LR\HtmlHelpers::escapeAttr($ticket['id']) /* pos 39:51 */;
				echo '" class="list-group-item ';
				if ($ticket['status'] == 'closed') /* pos 39:91 */ {
					echo 'list-group-item-success';
				} elseif ($ticket['status'] == 'on_hold') /* pos 39:150 */ {
					echo 'list-group-item-warning';
				} elseif ($ticket['status'] == 'open') /* pos 39:214 */ {
					echo 'list-group-item-danger';
				}


				echo '">
                    <span class="float-end badge ';
				if ($ticket['status'] == 'open') /* pos 40:50 */ {
					echo 'bg-danger';
				} elseif ($ticket['status'] == 'on_hold') /* pos 40:93 */ {
					echo 'bg-warning';
				} elseif ($ticket['status'] == 'closed') /* pos 40:144 */ {
					echo 'bg-success';
				} else /* pos 40:194 */ {
					echo 'bg-default';
				}


				echo '">';
				$this->renderBlock('status_name', [$ticket['status']] + [], 'html') /* pos 40:217 */;
				echo '</span>
                    <p class="mb-0">
                        <span class="label label-default">';
				echo LR\HtmlHelpers::escapeText($ticket['helpdesk']['name']) /* pos 42:59 */;
				echo '</span> - ';
				echo LR\HtmlHelpers::escapeText($ticket['subject']) /* pos 42:98 */;
				echo '<br>
                        <span class="small text-secondary">';
				echo LR\HtmlHelpers::escapeText(($this->filters->date)($ticket['created_at'], 'Y-m-d h:i')) /* pos 43:60 */;
				echo ' - ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Last post')) /* pos 43:103 */;
				echo ' ';
				echo LR\HtmlHelpers::escapeText(($this->filters->timeago)($ticket['updated_at'])) /* pos 43:124 */;
				echo ' ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('ago')) /* pos 43:156 */;
				echo '</span>
                    </p>
                </a>
';

			}

			echo '        </div>

        <div class="text-center">
';
			$this->createTemplate('_pagination.latte', ['list' => $tickets] + $this->params, 'include')->renderToContentType('html') /* pos 50:13 */;
			echo "\n";
			if ($guest->extension_is_on(['mod' => 'kb'])) /* pos 52:13 */ {
				echo '                <a class="btn btn-info" data-bs-toggle="collapse" data-bs-target="#kb" aria-expanded="false" aria-controls="kb">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Knowledge base')) /* pos 53:129 */;
				echo '</a>
';
			}
			echo '            <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#ticket-order">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Submit new ticket')) /* pos 55:93 */;
			echo '</a>
        </div>

';
			if ($guest->extension_is_on(['mod' => 'kb'])) /* pos 58:9 */ {
				echo '        <div class="collapse" id="kb">
            <h4>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Knowledge base')) /* pos 60:17 */;
				echo '</h4>
            <div class="input-group my-3">
                <input type="text" class="form-control">
                <button class="btn btn-primary"><i class="fa fa-search"></i></button>
            </div>
            <hr>
            <div class="list-group panel" id="kb">
';
				foreach ($guest->kb_category_get_list()['list'] ?? [] as $i => $category) /* pos 67:13 */ {
					echo '                <a href="#category-';
					echo LR\HtmlHelpers::escapeAttr($category['id']) /* pos 68:36 */;
					echo '" class="list-group-item text-center" data-bs-toggle="collapse" data-bs-parent="#kb"><strong>';
					echo LR\HtmlHelpers::escapeText($category['title']) /* pos 68:146 */;
					echo '</strong></a>
                <div class="collapse" id="category-';
					echo LR\HtmlHelpers::escapeAttr($category['id']) /* pos 69:52 */;
					echo '">
';
					foreach ($category['articles'] as $i => $article) /* pos 70:17 */ {
						echo '                    <a href="';
						echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('/kb')) /* pos 71:30 */;
						echo '/';
						echo LR\HtmlHelpers::escapeAttr($article['category']['slug']) /* pos 71:44 */;
						echo '/';
						echo LR\HtmlHelpers::escapeAttr($article['slug']) /* pos 71:75 */;
						echo '" class="list-group-item">';
						echo LR\HtmlHelpers::escapeText($article['title']) /* pos 71:119 */;
						echo '</a>
';

					}

					echo '                </div>
';

				}

				echo '            </div>
        </div>
';
			}
		}
		echo "\n";
	}


	/** {block modals} on line 82 */
	public function blockModals(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('Modal/_add-ticket.latte', ['id' => 'ticket-order'] + $this->params, 'include')->renderToContentType('html') /* pos 83:5 */;
	}
}
