<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_page_7-days-to-die.latte */
final class Template_1ba57446ea extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_banner' => 'blockContent_banner', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 5:1 */;
		echo '

';
		$side_menu = 'hidden' /* pos 7:1 */;
		echo "\n";
		$this->renderBlock('content_banner', get_defined_vars()) /* pos 9:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 37:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['cat' => '50', 'product' => '57'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 3:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 5 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('7 Days to Die Server Hosting')) /* pos 5:19 */;
	}


	/** {block content_banner} on line 9 */
	public function blockContent_banner(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <section class="game-hero">
        <div class="game-hero-bg" style="background-image: url(\'https://images3.alphacoders.com/607/thumb-1920-607324.jpg\');"></div>
        <div class="container-md position-relative">
            <div class="row align-items-center">
                <div class="col-lg-7 my-5 py-5 text-lg-start text-center">
                    <div class="game-badge">
                        <img src="';
		$img_7d2d = 'images/games/7-days-to-die.png' /* pos 17:35 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_7d2d)) /* pos 17:85 */;
		echo '" alt="7-days-to-die" class="me-2">
                        <span>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Ready in 60 seconds')) /* pos 18:31 */;
		echo '</span>
                    </div>
                    <h1 class="game-hero-title text-white fw-bold mb-4" style="font-size: 3.5rem;">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('7 Days to Die Server Hosting')) /* pos 20:100 */;
		echo '</h1>
                    <p class="game-hero-desc text-white-50 fs-5 mb-5">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Survival nights with stable performance and backups.')) /* pos 21:71 */;
		echo '</p>
                    <div class="game-hero-actions d-flex flex-wrap gap-3 justify-content-lg-start justify-content-center">
                        <a href="#pricing" class="btn btn-primary btn-lg fw-bold px-4 py-3 rounded-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create Server')) /* pos 23:103 */;
		echo '</a>
                        <a href="#features" class="btn btn-outline-light btn-lg fw-bold px-4 py-3 rounded-3 text-white">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('View Features')) /* pos 24:121 */;
		echo '</a>
                    </div>
                </div>

                <div class="col-lg-5 d-none d-lg-flex justify-content-center align-items-center">
                    <img src="';
		$img_7d2d = 'images/games/7-days-to-die.png' /* pos 30:31 */;
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_7d2d)) /* pos 30:81 */;
		echo '" alt="7-days-to-die" class="img-fluid hero-featured-logo animated-float" style="max-height: 320px; filter: drop-shadow(0 0 30px rgba(255,255,255,0.1));">
                </div>
            </div>
        </div>
    </section>
';
	}


	/** {block content} on line 37 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$game_category_id = 1 /* pos 39:5 */;
		echo '
    <section id="pricing" class="game-pricing py-5 mt-5">
        <div class="text-center mb-5">
            <h2 class="fw-bold text-white fs-1">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Choose Your 7 Days to Die Plan')) /* pos 44:49 */;
		echo '</h2>
            <p class="text-secondary fs-5">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Instant setup, DDoS protection, and premium hardware.')) /* pos 45:44 */;
		echo '</p>
        </div>

        <div class="row g-4 justify-content-center">
';
		$products = [] /* pos 49:13 */;
		foreach ($guest->product_category_get_list(['per_page' => 100])['list'] ?? [] as $cat) /* pos 50:13 */ {
			if ($cat['id'] == $game_category_id) /* pos 51:17 */ {
				$products = $cat['products'] /* pos 52:21 */;
			}

		}

		echo "\n";
		if (count($products) > 0) /* pos 56:13 */ {
			foreach ($products as $product) /* pos 57:17 */ {
				echo '                    <div class="col-md-6 col-lg-3">
                        <div class="card bg-dark border-secondary h-100 rounded-4 shadow-sm" style="transition: transform 0.3s; cursor: pointer;" onmouseover="this.style.transform=\'translateY(-10px)\'" onmouseout="this.style.transform=\'translateY(0)\'">
                            <div class="card-body p-4 d-flex flex-column">
                                <div class="d-flex align-items-center mb-4">
                                    <img src="';
				$img_7d2d = 'images/games/7-days-to-die.png' /* pos 62:47 */;
				echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)($img_7d2d)) /* pos 62:97 */;
				echo '" alt="7-days-to-die" width="100" class="me-3">
                                    <h3 class="card-title text-white fw-bold m-0 fs-4">';
				echo LR\HtmlHelpers::escapeText($product['title']) /* pos 63:88 */;
				echo '</h3>
                                </div>
                                <div class="mb-4 pb-4 border-bottom border-secondary">
                                    <span class="fs-1 fw-bold text-primary">';
				echo LR\HtmlHelpers::escapeText(($this->filters->money_convert)($product['price_starting_from'])) /* pos 66:77 */;
				echo '</span>
                                    <span class="text-secondary">/';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('mo')) /* pos 67:67 */;
				echo '</span>
                                </div>
                                
                                <ul class="list-unstyled mb-4 flex-grow-1">
';
				if ($product['description']) /* pos 71:37 */ {
					echo '                                        <li class="mb-3 text-secondary">
                                            <i class="fa fa-info-circle text-info me-2"></i>
                                            ';
					echo LR\HtmlHelpers::escapeText(($this->filters->truncate)(($this->filters->stripHtml)($product['description']), 80)) /* pos 74:45 */;
					echo '
                                        </li>
';
				}
				echo '                                    <li class="mb-3 text-white-50"><i class="fa fa-fighter-jet text-success me-2"></i> ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('High-Freq CPU')) /* pos 77:120 */;
				echo '</li>
                                    <li class="mb-3 text-white-50"><i class="fa fa-shield text-success me-2"></i> ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Advanced DDoS Defense')) /* pos 78:115 */;
				echo '</li>
                                    <li class="mb-3 text-white-50"><i class="fa fa-hdd-o text-success me-2"></i> ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('NVMe Storage')) /* pos 79:114 */;
				echo '</li>
                                    <li class="mb-3 text-white-50"><i class="fa fa-plug text-success me-2"></i> ';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Mod Support')) /* pos 80:113 */;
				echo '</li>
                                </ul>
                                
                                <a href="';
				echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('/order')) /* pos 83:42 */;
				echo '/';
				echo LR\HtmlHelpers::escapeAttr($product['slug']) /* pos 83:59 */;
				echo '" class="btn btn-outline-primary btn-lg w-100 fw-bold rounded-3 mt-auto">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Order Now')) /* pos 83:150 */;
				echo '</a>
                            </div>
                        </div>
                    </div>
';

			}

		} else /* pos 88:13 */ {
			echo '                <div class="col-12 text-center py-5">
                    <div class="alert alert-dark border-secondary d-inline-block p-4 rounded-4 shadow">
                        <i class="fa fa-exclamation-triangle text-warning fa-3x mb-3"></i>
                        <h4 class="text-white">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No Products Configured')) /* pos 92:48 */;
			echo '</h4>
                        <p class="text-white-50 mb-0">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Please update the $game_category_id variable at the top of mod_page_7-days-to-die.latte.')) /* pos 93:55 */;
			echo '</p>
                    </div>
                </div>
';
		}
		echo '        </div>
    </section>

    <section id="features" class="game-features py-5 my-5">
        <div class="text-center mb-5">
            <h2 class="fw-bold text-white fs-1">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Why Host With Us?')) /* pos 103:49 */;
		echo '</h2>
            <p class="text-secondary fs-5">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Premium features included with every game server.')) /* pos 104:44 */;
		echo '</p>
        </div>
        
        <div class="row g-4">
            <div class="col-md-4">
                <div class="card bg-dark bg-opacity-50 border-0 h-100 rounded-4 text-center p-4">
                    <div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-25 rounded-circle mb-4 mx-auto" style="width: 80px; height: 80px;">
                        <i class="fa fa-rocket fa-2x text-primary"></i>
                    </div>
                    <h4 class="text-white fw-bold mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Ultra Fast NVMe')) /* pos 113:57 */;
		echo '</h4>
                    <p class="text-white-50">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('High-performance storage for rapid loading and backups.')) /* pos 114:46 */;
		echo '</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-dark bg-opacity-50 border-0 h-100 rounded-4 text-center p-4">
                    <div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-25 rounded-circle mb-4 mx-auto" style="width: 80px; height: 80px;">
                        <i class="fa fa-microchip fa-2x text-primary"></i>
                    </div>
                    <h4 class="text-white fw-bold mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Game-Tuned Hardware')) /* pos 122:57 */;
		echo '</h4>
                    <p class="text-white-50">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('High-frequency CPUs and optimized network routing.')) /* pos 123:46 */;
		echo '</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card bg-dark bg-opacity-50 border-0 h-100 rounded-4 text-center p-4">
                    <div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-25 rounded-circle mb-4 mx-auto" style="width: 80px; height: 80px;">
                        <i class="fa fa-shield fa-2x text-primary"></i>
                    </div>
                    <h4 class="text-white fw-bold mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('DDoS Shield')) /* pos 131:57 */;
		echo '</h4>
                    <p class="text-white-50">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Game-specific filtering keeps your community online.')) /* pos 132:46 */;
		echo '</p>
                </div>
            </div>
        </div>
    </section>
';
	}
}
