<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_kb_index.latte */
final class Template_f8ea257c3b extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_before' => 'blockContent_before', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		if ($request->q) /* pos 5:1 */ {
			$kbcategories = $guest->kb_category_get_list(['q' => $request->q]) /* pos 6:5 */;
		} else /* pos 7:1 */ {
			$kbcategories = $guest->kb_category_get_list() /* pos 8:5 */;
		}
		echo "\n";
		$this->renderBlock('content_before', get_defined_vars()) /* pos 11:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 35:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['i' => '38', 'category' => '38'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		return get_defined_vars();
	}


	/** {block meta_title} on line 3 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Knowledge base')) /* pos 3:19 */;
	}


	/** {block content_before} on line 11 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="gm-page-heading">
        <h1>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Knowledgebase')) /* pos 13:13 */;
		echo '</h1>
    </div>
';
		if ($client) /* pos 15:5 */ {
			echo '        <div class="gm-client-tabs">
            <a class="active"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('kb'))) /* pos 17:39 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('General')) /* pos 17:49 */;
			echo '</a>
            <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('support'))) /* pos 18:24 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Support Tickets')) /* pos 18:39 */;
			echo '</a>
        </div>
';
		}
		echo '
    <div class="gm-landing">
        <section class="gm-hero">
            <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('How can we help you?')) /* pos 24:17 */;
		echo '</h3>
            <form method="get"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('kb'))) /* pos 25:42 */;
		echo '>
                <div class="input-group gm-kb-search">
                    <input name="q" type="text" class="form-control"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->q) /* pos 27:78 */;
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Search articles')) /* pos 27:107 */;
		echo '>
                    <button class="btn btn-primary" type="submit">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Search')) /* pos 28:67 */;
		echo '</button>
                </div>
            </form>
        </section>
    </div>
';
	}


	/** {block content} on line 35 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if (($this->filters->length)($kbcategories['list'] ?? []) > 0) /* pos 36:5 */ {
			echo '        <div class="gm-feature-grid gm-kb-grid">
';
			foreach ($kbcategories['list'] ?? [] as $i => $category) /* pos 38:13 */ {
				echo '                <a class="gm-feature-card" href="';
				echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('kb')) /* pos 39:50 */;
				echo '/';
				echo LR\HtmlHelpers::escapeAttr($category['slug']) /* pos 39:61 */;
				echo '">
                    <i class="fa fa-book"></i>
                    <h4>';
				echo LR\HtmlHelpers::escapeText($category['title']) /* pos 41:25 */;
				echo '</h4>
                    <p>';
				echo LR\HtmlHelpers::escapeText($category['description'] ?? ($this->filters->trans)('Browse articles in this category.')) /* pos 42:24 */;
				echo '</p>
                </a>
';

			}

			echo '        </div>
';
		} else /* pos 46:5 */ {
			echo '        <div class="gm-glass-panel text-center p-4">
            <h4 class="mb-2">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No results')) /* pos 48:30 */;
			echo '</h4>
            <p class="text-secondary mb-0">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Try using another keyword.')) /* pos 49:44 */;
			echo '</p>
        </div>
';
		}
	}
}
