<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/_footer.latte */
final class Template_1af410253c extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<footer class="footer mt-auto py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-4">
                <h5 class="mb-3 text-primary">';
		echo LR\HtmlHelpers::escapeText($settings->company_name) /* pos 5:47 */;
		echo '</h5>
                <p class="text-secondary mb-3">';
		echo LR\HtmlHelpers::escapeText($settings->company_note ?? 'Premium Web Hosting & Domain Services') /* pos 6:48 */;
		echo '</p>
                <div class="social-links">
                    <a href="#" class="btn btn-outline-primary btn-sm rounded-circle me-2"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="btn btn-outline-primary btn-sm rounded-circle me-2"><i class="fab fa-twitter"></i></a>
                    <a href="#" class="btn btn-outline-primary btn-sm rounded-circle me-2"><i class="fab fa-github"></i></a>
                </div>
            </div>
            
            <div class="col-md-2 mb-4">
                <h6 class="text-uppercase fw-bold mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Company')) /* pos 15:57 */;
		echo '</h6>
                <ul class="list-unstyled footer-links">
                    <li class="mb-2"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/about-us'))) /* pos 17:49 */;
		echo ' class="text-secondary text-decoration-none">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('About Us')) /* pos 17:112 */;
		echo '</a></li>
                    <li class="mb-2"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/news'))) /* pos 18:49 */;
		echo ' class="text-secondary text-decoration-none">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Blog')) /* pos 18:108 */;
		echo '</a></li>
                    <li class="mb-2"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/support/contact-us'))) /* pos 19:49 */;
		echo ' class="text-secondary text-decoration-none">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Contact Us')) /* pos 19:122 */;
		echo '</a></li>
                </ul>
            </div>

            <div class="col-md-2 mb-4">
                <h6 class="text-uppercase fw-bold mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Support')) /* pos 24:57 */;
		echo '</h6>
                <ul class="list-unstyled footer-links">
                    <li class="mb-2"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('kb'))) /* pos 26:49 */;
		echo ' class="text-secondary text-decoration-none">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Knowledge Base')) /* pos 26:103 */;
		echo '</a></li>
                    <li class="mb-2"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('support'))) /* pos 27:49 */;
		echo ' class="text-secondary text-decoration-none">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Support Tickets')) /* pos 27:108 */;
		echo '</a></li>
                    <li class="mb-2"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/tos'))) /* pos 28:49 */;
		echo ' class="text-secondary text-decoration-none">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Terms of Service')) /* pos 28:107 */;
		echo '</a></li>
                </ul>
            </div>

            <div class="col-md-4 mb-4">
                <h6 class="text-uppercase fw-bold mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Newsletter')) /* pos 33:57 */;
		echo '</h6>
                <p class="small text-secondary mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Subscribe to get latest updates and offers.')) /* pos 34:54 */;
		echo '</p>
                <form class="api-form mb-3" data-api-url="guest/newsletter/subscribe"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('Successfully subscribed')) /* pos 35:103 */;
		echo '>
                    <div class="input-group">
                        <input type="email" class="form-control" name="email"';
		echo LR\HtmlHelpers::formatAttribute(' placeholder', ($this->filters->trans)('Email address')) /* pos 37:94 */;
		echo ' required>
                        <button class="btn btn-primary" type="submit">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Join')) /* pos 38:71 */;
		echo '</button>
                    </div>
                </form>
            </div>
        </div>

        <hr class="my-4 text-secondary opacity-25">

        <div class="row align-items-center">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                <p class="small text-secondary mb-0">&copy; ';
		echo LR\HtmlHelpers::escapeText(($this->filters->date)($now, 'Y')) /* pos 48:61 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($settings->company_name) /* pos 48:75 */;
		echo '. ';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('All rights reserved.')) /* pos 48:102 */;
		echo '</p>
            </div>
            <div class="col-md-6 text-center text-md-end">
';
		if ($guest->extension_is_on(['mod' => 'branding']) || ($settings->footer_branding_enabled ?? false)) /* pos 51:17 */ {
			echo '                    <p class="small text-secondary mb-0">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Powered by')) /* pos 52:58 */;
			echo ' <a href="https://priyxstudio.in/getohms" title="Billing and Support Automation" target="_blank" class="text-decoration-none">OHMS</a></p>
';
		}
		echo '            </div>
        </div>
    </div>
</footer>
';
	}
}
