<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_support_contact_us.latte */
final class Template_f2c6b74288 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 5:1 */;
		echo '

';
		$company = $guest->system_company() /* pos 7:1 */;
		echo "\n";
		$this->renderBlock('content_before', get_defined_vars()) /* pos 9:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 23:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 79:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 3:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 5 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Contact us')) /* pos 5:19 */;
	}


	/** {block content_before} on line 9 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <nav class="row">
        <div class="col">
            <h1 class="page-header">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Contact us')) /* pos 12:37 */;
		echo '</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)(''))) /* pos 15:32 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 15:42 */;
		echo '</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Contact us')) /* pos 17:72 */;
		echo '</li>
            </ol>
        </div>
    </nav>
';
	}


	/** {block content} on line 23 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="row">
        <div class="col-lg-8 mb-lg-3">
            <form method="post" class="api-form" data-api-url="guest/support/ticket_create"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-tocreated', ($this->filters->link)('support/contact-us/conversation')) /* pos 26:115 */;
		echo '>
                <div class="mb-3">
                    <label class="form-label" for="inputContactName">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('First name')) /* pos 28:70 */;
		echo ':</label>
                    <input type="text" class="form-control" id="inputContactName" name="name" value="';
		if ($client) /* pos 29:102 */ {
			echo LR\HtmlHelpers::escapeAttr($profile['first_name'] . ' ' . $profile['last_name']) /* pos 29:114 */;
		} else /* pos 29:171 */ {
			echo LR\HtmlHelpers::escapeAttr($request->name) /* pos 29:177 */;
		}
		echo '" required>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="inputContactEmail">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Email address')) /* pos 32:71 */;
		echo ':</label>
                    <input type="email" class="form-control" id="inputContactEmail" name="email" value="';
		if ($client) /* pos 33:105 */ {
			echo LR\HtmlHelpers::escapeAttr($profile['email']) /* pos 33:117 */;
		} else /* pos 33:136 */ {
			echo LR\HtmlHelpers::escapeAttr($request->name) /* pos 33:142 */;
		}
		echo '" required>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="inputContactSubject">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Subject')) /* pos 36:73 */;
		echo ':</label>
                    <input type="text" class="form-control" id="inputContactSubject" name="subject"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->subject) /* pos 37:109 */;
		echo ' required>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="textareaContactMessage">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Message')) /* pos 40:76 */;
		echo ':</label>
                    <textarea class="form-control p-3" id="textareaContactMessage" name="message" rows="10" maxlength="999" style="resize: none;" required data-provide="markdown" data-iconlibrary="fa">';
		echo LR\HtmlHelpers::escapeText($request->message) /* pos 41:202 */;
		echo '</textarea>
                </div>

                <div class="mb-3">
';
		$this->renderBlock('recaptcha', [], 'html') /* pos 45:21 */;
		echo '                    <input type="hidden" class="form-control" name="anti-spam" value="1" id="anti-spam" required>
                </div>

                <div class="d-grid">
                    <div id="success"></div>
                    <!-- For success/fail messages -->
                    <input class="btn btn-primary" type="submit"';
		echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Send')) /* pos 52:75 */;
		echo '>
                </div>
            </form>
        </div>

        <div class="col-lg-4">
            <div class="card shadow-sm">
                <div class="card-header">
                    <h4 class="mb-0">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Contact details')) /* pos 60:38 */;
		echo '</h4>
                </div>
                <div class="card-body">
                    <p class="lead">';
		echo LR\HtmlHelpers::escapeText($company['name']) /* pos 63:37 */;
		echo '</p>
                    <p>';
		echo LR\HtmlHelpers::escapeText($company['address_1']) /* pos 64:24 */;
		echo '<br>
                        ';
		echo LR\HtmlHelpers::escapeText($company['address_2']) /* pos 65:25 */;
		echo '<br>
                        ';
		echo LR\HtmlHelpers::escapeText($company['address_3']) /* pos 66:25 */;
		echo '
                    </p>
                    <p>
                        <i class="fa fa-phone-alt me-2"></i>Phone: ';
		echo LR\HtmlHelpers::escapeText($company['tel']) /* pos 69:68 */;
		echo '<br>
                        <i class="fa fa-envelope me-2"></i>E-mail: <a href="mailto:';
		echo LR\HtmlHelpers::escapeAttr($company['email']) /* pos 70:84 */;
		echo '">';
		echo LR\HtmlHelpers::escapeText($company['email']) /* pos 70:105 */;
		echo '</a><br>
                        <i class="fa fa-globe me-2"></i>Web: <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($company['www'])) /* pos 71:72 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText($company['www']) /* pos 71:90 */;
		echo '</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
';
	}


	/** {block js} on line 79 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script>
    document.addEventListener(\'DOMContentLoaded\', function() {
        $(\'#anti-spam\').remove();

        $(\'#public-ticket-create\').bind(\'submit\', event => {
            bb.post(\'guest/support/ticket_create\', $(event.target).serialize(), function(result) {
                    bb.redirect(';
		echo LR\Helpers::escapeJs(json_encode(($this->filters->link)('support/contact-us/conversation') . '/')) /* pos 86:33 */;
		echo ' + result);
            });

            return false;
        });
    });
</script>
';
	}
}
