<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_page_register.latte */
final class Template_19cbadb009 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'head' => 'blockHead', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 5:1 */;
		echo "\n";
		$redirect_to = $request->return_to ?? '/client' /* pos 6:1 */;
		if (!str_starts_with($redirect_to, '/')) /* pos 7:1 */ {
			$redirect_to = '/client' /* pos 8:5 */;
		}
		$required_fields = $guest->client_required() /* pos 10:1 */;
		$custom_fields = $guest->client_custom_fields ?? [] /* pos 11:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 13:1 */;
		echo "\n";
		$this->renderBlock('content_before', get_defined_vars()) /* pos 96:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 103:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 253:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['field_name' => '211', 'field' => '211'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_public.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 3:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 5 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register')) /* pos 5:19 */;
	}


	/** {block head} on line 13 */
	public function blockHead(array $ʟ_args): void
	{
		echo '<style>
    .gm-register-shell {
        max-width: 1120px;
        margin: 0 auto;
    }

    .gm-register-panel {
        background: rgba(11, 14, 26, 0.88);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 14px;
        box-shadow: 0 12px 40px rgba(0, 0, 0, 0.35);
        backdrop-filter: blur(14px);
    }

    .gm-register-panel .card-body {
        padding: 1.5rem;
    }

    .gm-register-panel h3,
    .gm-register-panel h4 {
        color: #fff;
        font-weight: 700;
    }

    .gm-register-subtext {
        color: rgba(255, 255, 255, 0.72);
    }

    .gm-register-section-title {
        font-size: 1.4rem;
        margin-bottom: 1.2rem;
    }

    .gm-register-panel .form-label {
        color: rgba(255, 255, 255, 0.86);
        font-weight: 600;
        font-size: 0.9rem;
        margin-bottom: 0.45rem;
    }

    .gm-register-panel .form-control,
    .gm-register-panel .form-select,
    .gm-register-panel .input-group-text {
        background: rgba(16, 20, 35, 0.92);
        border: 1px solid rgba(255, 255, 255, 0.16);
        color: #fff;
    }

    .gm-register-panel .form-control::placeholder {
        color: rgba(255, 255, 255, 0.45);
    }

    .gm-register-panel .form-control:focus,
    .gm-register-panel .form-select:focus {
        border-color: rgba(139, 124, 247, 0.8);
        box-shadow: 0 0 0 0.2rem rgba(139, 124, 247, 0.22);
    }

    .gm-register-panel hr {
        border-color: rgba(255, 255, 255, 0.1);
        margin: 1.25rem 0 0;
    }

    .gm-register-mailing {
        background: rgba(139, 124, 247, 0.1);
        border: 1px solid rgba(139, 124, 247, 0.3);
        border-radius: 12px;
        padding: 1rem 1.1rem;
    }

    .gm-register-actions .btn {
        min-height: 48px;
    }

    @media (max-width: 1199px) {
        .gm-register-panel .card-body {
            padding: 1.25rem;
        }
    }
</style>
';
	}


	/** {block content_before} on line 96 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="gm-register-shell mb-4">
        <h1 class="mb-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register')) /* pos 98:26 */;
		echo '</h1>
        <p class="gm-register-subtext mb-0">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create your account to manage services, invoices, and support from one dashboard.')) /* pos 99:45 */;
		echo '</p>
    </div>
';
	}


	/** {block content} on line 103 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="gm-register-shell">
        <div class="row g-4 align-items-start">
            <div class="col-xl-3">
                <div class="card gm-register-panel border-0">
                    <div class="card-body">
                        <h3 class="h5 mb-3">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Already registered?')) /* pos 109:45 */;
		echo '</h3>
                        <p class="gm-register-subtext mb-4">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Already registered with us? Login to manage your services, billing, and support.')) /* pos 110:61 */;
		echo '</p>
                        <div class="d-grid gap-2">
                            <a class="btn btn-outline-light" href="';
		echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('/login')) /* pos 112:68 */;
		if ($request->return_to) /* pos 112:84 */ {
			echo '?return_to=';
			echo LR\HtmlHelpers::escapeAttr($request->return_to) /* pos 112:119 */;
		}
		echo '">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Login')) /* pos 112:147 */;
		echo '</a>
                            <a class="btn btn-link p-0 text-start text-decoration-none"';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('reset-password'))) /* pos 113:97 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Lost Password Reset')) /* pos 113:121 */;
		echo '</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-9">
                <form id="client-register-form" method="post" class="api-form"';
		echo LR\HtmlHelpers::formatAttribute(' action', ($this->filters->checkUrl)(($this->filters->link)('api/guest/client/create'))) /* pos 120:90 */;
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', $redirect_to) /* pos 120:143 */;
		echo '>
                    <input type="hidden" name="auto_login" value="1">

                    <section class="card gm-register-panel border-0 mb-4">
                        <div class="card-body">
                            <h4 class="gm-register-section-title">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Personal Information')) /* pos 125:67 */;
		echo '</h4>
                            <div class="row g-3">
                                <div class="col-md-6">
                                    <label class="form-label" for="register-first-name">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('First name')) /* pos 128:89 */;
		echo '</label>
                                    <input class="form-control" id="register-first-name" type="text" name="first_name"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->first_name) /* pos 129:128 */;
		echo ' required>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="register-last-name">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Last name')) /* pos 132:88 */;
		echo '</label>
                                    <input class="form-control" id="register-last-name" type="text" name="last_name"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->last_name) /* pos 133:126 */;
		echo ' ';
		if (in_array('last_name', $required_fields ?? [], true)) /* pos 133:148 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="register-email">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Email address')) /* pos 136:84 */;
		echo '</label>
                                    <input class="form-control" id="register-email" type="email" name="email"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->email) /* pos 137:119 */;
		echo ' required>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="register-company">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Company')) /* pos 140:86 */;
		echo '</label>
                                    <input class="form-control" id="register-company" type="text" name="company"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->company) /* pos 141:122 */;
		echo ' ';
		if (in_array('company', $required_fields ?? [], true)) /* pos 141:142 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-md-3">
                                    <label class="form-label" for="register-phone-cc">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Phone code')) /* pos 144:87 */;
		echo '</label>
                                    <div class="input-group">
                                        <span class="input-group-text">+</span>
                                        <input class="form-control" id="register-phone-cc" type="text" name="phone_cc"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->phone_cc) /* pos 147:128 */;
		echo ' ';
		if (in_array('phone', $required_fields ?? [], true)) /* pos 147:149 */ {
			echo 'required';
		}
		echo '>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <label class="form-label" for="register-phone">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Phone number')) /* pos 151:84 */;
		echo '</label>
                                    <input class="form-control" id="register-phone" type="text" name="phone"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->phone) /* pos 152:118 */;
		echo ' ';
		if (in_array('phone', $required_fields ?? [], true)) /* pos 152:136 */ {
			echo 'required';
		}
		echo '>
                                </div>
                            </div>
                        </div>
                    </section>

                    <section class="card gm-register-panel border-0 mb-4">
                        <div class="card-body">
                            <h4 class="gm-register-section-title">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Billing Address')) /* pos 160:67 */;
		echo '</h4>
                            <div class="row g-3">
                                <div class="col-12">
                                    <label class="form-label" for="register-address-1">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Street Address')) /* pos 163:88 */;
		echo '</label>
                                    <input class="form-control" id="register-address-1" type="text" name="address_1"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->address_1) /* pos 164:126 */;
		echo ' ';
		if (in_array('address_1', $required_fields ?? [], true)) /* pos 164:148 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-12">
                                    <label class="form-label" for="register-address-2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Address line 2')) /* pos 167:88 */;
		echo '</label>
                                    <input class="form-control" id="register-address-2" type="text" name="address_2"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->address_2) /* pos 168:126 */;
		echo ' ';
		if (in_array('address_2', $required_fields ?? [], true)) /* pos 168:148 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-md-4">
                                    <label class="form-label" for="register-city">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('City')) /* pos 171:83 */;
		echo '</label>
                                    <input class="form-control" id="register-city" type="text" name="city"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->city) /* pos 172:116 */;
		echo ' ';
		if (in_array('city', $required_fields ?? [], true)) /* pos 172:133 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-md-4">
                                    <label class="form-label" for="register-state">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('State')) /* pos 175:84 */;
		echo '</label>
                                    <input class="form-control" id="register-state" type="text" name="state"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->state) /* pos 176:118 */;
		echo ' ';
		if (in_array('state', $required_fields ?? [], true)) /* pos 176:136 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-md-4">
                                    <label class="form-label" for="register-postcode">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Zip/Postal Code')) /* pos 179:87 */;
		echo '</label>
                                    <input class="form-control" id="register-postcode" type="text" name="postcode"';
		echo LR\HtmlHelpers::formatAttribute(' value', $request->postcode) /* pos 180:124 */;
		echo ' ';
		if (in_array('postcode', $required_fields ?? [], true)) /* pos 180:145 */ {
			echo 'required';
		}
		echo '>
                                </div>
                                <div class="col-12">
                                    <label class="form-label" for="register-country">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Country')) /* pos 183:86 */;
		echo '</label>
';
		$this->renderBlock('selectbox', ['country', $guest->system_countries, $request->country, in_array('country', $required_fields ?? [], true), 'Select country', 'register-country'] + [], 'html') /* pos 184:37 */;
		echo '                                </div>
                            </div>
                        </div>
                    </section>

                    <section class="card gm-register-panel border-0 mb-4">
                        <div class="card-body">
                            <h4 class="gm-register-section-title">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Account Security')) /* pos 192:67 */;
		echo '</h4>
                            <div class="row g-3">
                                <div class="col-md-6">
                                    <label class="form-label" for="register-password">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password')) /* pos 195:87 */;
		echo '</label>
                                    <input class="form-control" id="register-password" type="password" name="password" required>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="register-password-confirm">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password confirm')) /* pos 199:95 */;
		echo '</label>
                                    <input class="form-control" id="register-password-confirm" type="password" name="password_confirm" required>
                                </div>
                            </div>
                        </div>
                    </section>

';
		if ($custom_fields) /* pos 206:21 */ {
			echo '                    <section class="card gm-register-panel border-0 mb-4">
                        <div class="card-body">
                            <h4 class="gm-register-section-title">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Additional Information')) /* pos 209:67 */;
			echo '</h4>
                            <div class="row g-3">
';
			foreach ($custom_fields as $field_name => $field) /* pos 211:33 */ {
				if ($field->active) /* pos 212:37 */ {
					echo '                                    <div class="col-md-6">
                                        <label class="form-label" for="field-';
					echo LR\HtmlHelpers::escapeAttr($field_name) /* pos 214:78 */;
					echo '">';
					if (!empty($field->title)) /* pos 214:93 */ {
						echo LR\HtmlHelpers::escapeText($field->title) /* pos 214:119 */;
					} else /* pos 214:134 */ {
						echo LR\HtmlHelpers::escapeText(($this->filters->capitalize)($field_name)) /* pos 214:140 */;
					}
					echo '</label>
                                        <input class="form-control" id="field-';
					echo LR\HtmlHelpers::escapeAttr($field_name) /* pos 215:79 */;
					echo '" type="text"';
					echo LR\HtmlHelpers::formatAttribute(' name', $field_name) /* pos 215:113 */;
					echo LR\HtmlHelpers::formatAttribute(' value', $request->{$field_name}) /* pos 215:135 */;
					echo ' ';
					if ($field->required) /* pos 215:161 */ {
						echo 'required';
					}
					echo '>
                                    </div>
';
				}

			}

			echo '                            </div>
                        </div>
                    </section>
';
		}
		echo '
                    <section class="card gm-register-panel border-0 mb-4">
                        <div class="card-body">
                            <div class="gm-register-mailing">
                                <div class="form-check m-0">
                                    <input type="hidden" name="marketing_opt_in" value="0">
                                    <input class="form-check-input" id="register-marketing-opt-in" type="checkbox" name="marketing_opt_in" value="1" ';
		if ($request->marketing_opt_in ?? null) /* pos 229:150 */ {
			echo 'checked';
		}
		echo '>
                                    <label class="form-check-label" for="register-marketing-opt-in">
                                        <strong>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Join our mailing list')) /* pos 231:49 */;
		echo '</strong><br>
                                        <span class="gm-register-subtext">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Receive occasional product news, announcements, and special offers by email.')) /* pos 232:75 */;
		echo '</span>
                                    </label>
                                </div>
                            </div>

                            <div class="mt-4">
';
		$this->renderBlock('recaptcha', [], 'html') /* pos 238:33 */;
		echo '                            </div>

                            <div class="d-grid gap-2 mt-4 gm-register-actions">
                                <button class="btn btn-success btn-lg" type="submit">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register')) /* pos 242:86 */;
		echo '</button>
                                <a class="btn btn-link" href="';
		echo LR\HtmlHelpers::escapeAttr(($this->filters->link)('/login')) /* pos 243:63 */;
		if ($request->return_to) /* pos 243:79 */ {
			echo '?return_to=';
			echo LR\HtmlHelpers::escapeAttr($request->return_to) /* pos 243:114 */;
		}
		echo '">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Login')) /* pos 243:142 */;
		echo '</a>
                            </div>
                        </div>
                    </section>
                </form>
            </div>
        </div>
    </div>
';
	}


	/** {block js} on line 253 */
	public function blockJs(array $ʟ_args): void
	{
	}
}
