<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/layout_public.latte */
final class Template_1bf4a01abc extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
	}


	public function prepare(): array
	{
		extract($this->params);

		$shell_layout = 'public' /* pos 1:1 */;
		$this->parentName = 'layout_default.latte';
		return get_defined_vars();
	}
}
