<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_page_reset-password.latte */
final class Template_7bf71b6ad4 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_before' => 'blockContent_before', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content_before', get_defined_vars()) /* pos 5:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 19:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_public.latte';
		return get_defined_vars();
	}


	/** {block meta_title} on line 3 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reset password')) /* pos 3:19 */;
	}


	/** {block content_before} on line 5 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="row">
        <div class="col">
            <h1>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reset password')) /* pos 8:17 */;
		echo '</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)(''))) /* pos 11:32 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 11:42 */;
		echo '</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reset password')) /* pos 13:72 */;
		echo '</li>
            </ol>
        </div>
    </div>
';
	}


	/** {block content} on line 19 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if (!$client) /* pos 20:5 */ {
			echo '        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="card shadow-sm border-0">
                    <div class="card-body p-4 p-lg-5">
                        <form method="post" class="api-form" data-api-url="guest/client/reset_password"';
			echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('Password reset confirmation email was sent')) /* pos 25:121 */;
			echo '>
                            <p class="text-secondary mb-4">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Enter your email to reset password. You will receive new password after reset link is confirmed.')) /* pos 26:60 */;
			echo '</p>
                            <div class="mb-3">
                                <label class="form-label" for="inputEmail">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Email address')) /* pos 28:76 */;
			echo '</label>
                                <input class="form-control" type="email" id="inputEmail" name="email"';
			echo LR\HtmlHelpers::formatAttribute(' value', $request->email) /* pos 29:111 */;
			echo ' required>
                            </div>
                            <div class="d-grid gap-2">
                                <button class="btn btn-primary" type="submit">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reset password')) /* pos 32:79 */;
			echo '</button>
                                <a class="btn btn-link"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/login'))) /* pos 33:65 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('I remembered password')) /* pos 33:81 */;
			echo '</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
';
		} else /* pos 40:5 */ {
			echo '        <script>
            window.location.replace(';
			echo LR\Helpers::escapeJs(json_encode(($this->filters->link)('/client'))) /* pos 42:37 */;
			echo ');
        </script>
';
		}
	}
}
