<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_dashboard_index.latte */
final class Template_9e832a2a9c extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->createTemplate('client/mod_dashboard_index.latte', $this->params, 'include')->renderToContentType('html') /* pos 1:1 */;
	}
}
