<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/_navbar.latte */
final class Template_7b02c1c5fa extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="gm-navbar-anchor">
    <nav class="gm-floating-navbar container-md">
        <div class="gm-nav-section gm-nav-logo">
            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/'))) /* pos 5:24 */;
		echo ' class="gm-nav-brand">
';
		$final_logo = $company['logo_url'] ?? $settings->logo_url /* pos 6:17 */;
		if ($final_logo) /* pos 7:17 */ {
			$logo_src = str_starts_with($final_logo, 'http') || str_starts_with($final_logo, '/') ? $final_logo : '/' . $final_logo /* pos 8:21 */;
			echo '                    <img';
			echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)($logo_src)) /* pos 9:32 */;
			echo LR\HtmlHelpers::formatAttribute(' alt', isset($company) ? $company['name'] : 'Logo') /* pos 9:51 */;
			echo ' style="max-height: 40px;">
';
		} else /* pos 10:17 */ {
			echo '                    <span class="gm-site-name">';
			echo LR\HtmlHelpers::escapeText(isset($company) ? $company['name'] : 'Site Name') /* pos 11:48 */;
			echo '</span>
';
		}
		echo '            </a>
        </div>

        <div class="gm-nav-section gm-nav-mid">
            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/'))) /* pos 18:24 */;
		echo ' class="gm-nav-item"><i class="fa fa-home me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 18:86 */;
		echo '</a>
            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/order'))) /* pos 19:24 */;
		echo ' class="gm-nav-item"><i class="fa fa-shopping-cart me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Store')) /* pos 19:100 */;
		echo '</a>
            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/contact-us'))) /* pos 20:24 */;
		echo ' class="gm-nav-item"><i class="fa fa-envelope me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Contact Us')) /* pos 20:100 */;
		echo '</a>

        </div>

        <div class="gm-nav-section gm-nav-user d-flex align-items-center gap-3">
';
		$cart = $guest->cart_get() /* pos 27:13 */;
		$cart_count = count($cart['items'] ?? []) /* pos 28:13 */;
		echo '            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/cart'))) /* pos 29:24 */;
		echo ' class="gm-nav-item position-relative p-2"';
		echo LR\HtmlHelpers::formatAttribute(' title', ($this->filters->trans)('Shopping Cart')) /* pos 29:90 */;
		echo '>
                <i class="fa fa-shopping-basket fs-5"></i>
';
		if ($cart_count > 0) /* pos 31:17 */ {
			echo '                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" style="font-size: 0.65rem; padding: 0.25em 0.5em;">
                        ';
			echo LR\HtmlHelpers::escapeText($cart_count) /* pos 33:25 */;
			echo '
                    </span>
';
		}
		echo '            </a>

';
		if (count($profile) > 0) /* pos 38:13 */ {
			echo '                <div class="dropdown">
                    <button class="gm-nav-item dropdown-toggle d-flex align-items-center gap-2 border-0 bg-transparent" type="button" id="userMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="gm-nav-avatar bg-primary text-white rounded-circle d-flex align-items-center justify-content-center fw-bold" style="width: 32px; height: 32px; font-size: 0.85rem;">
                            ';
			echo LR\HtmlHelpers::escapeText(($this->filters->upper)(($this->filters->first)($profile['first_name'] ?? 'U'))) /* pos 42:29 */;
			echo LR\HtmlHelpers::escapeText(($this->filters->upper)(($this->filters->first)($profile['last_name'] ?? ''))) /* pos 42:74 */;
			echo '
                        </div>
                        <span class="d-none d-md-inline text-white-50">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Account')) /* pos 44:72 */;
			echo '</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end shadow border-secondary mt-2" aria-labelledby="userMenuButton">
                        <li><a class="dropdown-item py-2"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/client'))) /* pos 47:67 */;
			echo '><i class="fa fa-dashboard me-2 text-primary"></i>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Client Area')) /* pos 47:133 */;
			echo '</a></li>
                        <li><a class="dropdown-item py-2"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/client/profile'))) /* pos 48:67 */;
			echo '><i class="fa fa-user me-2 text-info"></i>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Profile Settings')) /* pos 48:133 */;
			echo '</a></li>
                        <li><hr class="dropdown-divider border-secondary"></li>
                        <li><a class="dropdown-item py-2 text-danger"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/client/logout'))) /* pos 50:79 */;
			echo '><i class="fa fa-sign-out me-2"></i>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Logout')) /* pos 50:138 */;
			echo '</a></li>
                    </ul>
                </div>
';
		} else /* pos 53:13 */ {
			echo '                <div class="d-flex gap-2">
                    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/login'))) /* pos 55:32 */;
			echo ' class="gm-nav-item gm-nav-btn">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Login')) /* pos 55:79 */;
			echo '</a>
                    <a';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('/login#register'))) /* pos 56:32 */;
			echo ' class="gm-nav-item gm-nav-btn gm-btn-register d-none d-sm-inline-block">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Register')) /* pos 56:129 */;
			echo '</a>
                </div>
';
		}
		echo '        </div>
    </nav>
</div>
';
	}
}
