<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\404.latte */
final class Template_77442babd0 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_before' => 'blockContent_before', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content_before', get_defined_vars()) /* pos 5:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 14:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout_default.latte';
		return get_defined_vars();
	}


	/** {block meta_title} on line 3 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Error')) /* pos 3:19 */;
	}


	/** {block content_before} on line 5 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)(''))) /* pos 8:24 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 8:34 */;
		echo '</a>
        </li>
        <li class="breadcrumb-item active">404</li>
    </ol>
';
	}


	/** {block content} on line 14 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="text-center">
    <h1 class="display-4">404</h1>
    <div class="text-secondary">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Looks like we have a misunderstanding here')) /* pos 17:33 */;
		echo '</div>
	<div class="text-danger">';
		echo LR\HtmlHelpers::escapeText($exception->getMessage()) /* pos 18:27 */;
		echo '</div>
</div>
';
	}
}
