<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html/layout_default.latte */
final class Template_768a1f03c1 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'meta_description' => ['blockMeta_description', 'html/attr'], 'meta_keywords' => ['blockMeta_keywords', 'html/attr'], 'opengraph' => 'blockOpengraph', 'head' => 'blockHead', 'main_content' => 'blockMain_content', 'content_before' => 'blockContent_before', 'content' => 'blockContent', 'content_after' => 'blockContent_after', 'content_banner' => 'blockContent_banner', 'js' => 'blockJs', 'modals' => 'blockModals'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!-- DEBUG: request_path=\'';
		echo LR\HtmlHelpers::escapeComment($request_path) /* pos 19:27 */;
		echo '\', request_uri=\'';
		echo LR\HtmlHelpers::escapeComment($request_uri) /* pos 19:58 */;
		echo '\', shell_layout=\'';
		echo LR\HtmlHelpers::escapeComment($shell_layout) /* pos 19:89 */;
		echo '\' -->
<!DOCTYPE html>
<html';
		echo LR\HtmlHelpers::formatAttribute(' lang', $lang) /* pos 21:14 */;
		echo '>
<head>
    <title>';
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 23:12 */;
		echo ' | ';
		echo LR\HtmlHelpers::escapeText($settings->meta_title) /* pos 23:41 */;
		echo '</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="bb:url"';
		echo LR\HtmlHelpers::formatAttribute(' content', constant('PS_URL')) /* pos 27:39 */;
		echo '>
    <meta property="bb:client_area"';
		echo LR\HtmlHelpers::formatAttribute(' content', ($this->filters->link)('/')) /* pos 28:48 */;
		echo '>

    <meta name="description" content="';
		$this->renderBlock('meta_description', get_defined_vars(), function ($s, $type) {
			$ʟ_fi = new LR\FilterInfo($type);
			return LR\Helpers::convertTo($ʟ_fi, 'html/attr', $s);
		}) /* pos 30:39 */;
		echo '">
    <meta name="keywords" content="';
		$this->renderBlock('meta_keywords', get_defined_vars(), function ($s, $type) {
			$ʟ_fi = new LR\FilterInfo($type);
			return LR\Helpers::convertTo($ʟ_fi, 'html/attr', $s);
		}) /* pos 31:36 */;
		echo '">
    <meta name="robots"';
		echo LR\HtmlHelpers::formatAttribute(' content', $settings->meta_robots ?: 'index, follow') /* pos 32:35 */;
		echo '>
    <meta name="author"';
		echo LR\HtmlHelpers::formatAttribute(' content', $settings->meta_author) /* pos 33:35 */;
		echo '>

';
		if ($settings->favicon ?? null) /* pos 35:5 */ {
			echo '        <link rel="icon"';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)($settings->favicon)) /* pos 36:33 */;
			echo '>
';
		}
		echo '
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Bootstrap Core CSS -->
';
		if (($settings->theme ?? 'default') != 'default') /* pos 43:5 */ {
			echo '        <link href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)('css/themes/theme-')) /* pos 44:21 */;
			echo LR\HtmlHelpers::escapeAttr($settings->theme) /* pos 44:53 */;
			echo '.min.css" rel="stylesheet">
';
		} else /* pos 45:5 */ {
			echo '        <link';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->asset_url)('css/bootstrap.min.css'))) /* pos 46:23 */;
			echo ' rel="stylesheet">
';
		}
		echo "\n";
		if ($shell_layout != 'client') /* pos 49:5 */ {
			echo '        <!-- Base OHMS layout helpers -->
        <style>
            :root {
                --bs-primary: #4361ee;
                --bs-primary-rgb: 67, 97, 238;
            }
            body {
                font-family: \'Inter\', sans-serif;
                background-color: #f8f9fa;
            }
            .main-content-wrapper {
                padding-top: 2rem;
                padding-bottom: 4rem;
            }
            .card {
                border-radius: 12px;
                overflow: hidden;
                transition: transform 0.2s, box-shadow 0.2s;
            }
            .shadow-sm {
                box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075) !important;
            }
            .navbar {
                backdrop-filter: blur(10px);
                -webkit-backdrop-filter: blur(10px);
                background-color: rgba(67, 97, 238, 0.95) !important;
            }
            .btn-primary {
                background-color: var(--bs-primary);
                border-color: var(--bs-primary);
                font-weight: 500;
                padding: 0.5rem 1.25rem;
                border-radius: 8px;
            }
            .list-group-item.active {
                background-color: rgba(var(--bs-primary-rgb), 0.1);
                color: var(--bs-primary);
                border-color: transparent;
                font-weight: 600;
            }
            .list-group-item {
                border-left: 3px solid transparent;
                transition: all 0.2s;
            }
            .list-group-item:hover:not(.active) {
                background-color: #fcfcfc;
                border-left-color: #dee2e6;
            }
            .list-group-item.active {
                border-left-color: var(--bs-primary);
            }
        </style>
';
		}
		echo '
    <!-- Priyxo Theme CSS -->
    <link';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->asset_url)('css/application.min.css'))) /* pos 105:19 */;
		echo ' rel="stylesheet">
    <link';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->asset_url)('css/theme.css'))) /* pos 106:19 */;
		echo ' rel="stylesheet">
    <link href="';
		echo LR\HtmlHelpers::escapeAttr(($this->filters->asset_url)('css/custom.css')) /* pos 107:17 */;
		echo '?v=';
		echo LR\HtmlHelpers::escapeAttr(($this->filters->date)($now, 'U')) /* pos 107:49 */;
		echo '" rel="stylesheet">

    <!-- Font Awesome (local, from Priyxo assets) -->
    <link';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->asset_url)('css/font-awesome.min.css'))) /* pos 110:19 */;
		echo ' rel="stylesheet">
    <link';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->asset_url)('css/font-awesome-shims.min.css'))) /* pos 111:19 */;
		echo ' rel="stylesheet">

';
		if ($settings->inject_css ?? '') /* pos 113:5 */ {
			echo '        <style>';
			echo LR\HtmlHelpers::convertJSToRawText($settings->inject_css) /* pos 114:16 */;
			echo '</style>
';
		}
		echo '
    <style>
';
		if ($shell_layout == 'client') /* pos 118:9 */ {
			echo '            body.shell-client {
';
			if ($settings->client_background ?? null) /* pos 120:17 */ {
				echo '                    background-image: linear-gradient(rgba(8, 10, 16, 0.45), rgba(8, 10, 16, 0.45)), url(\'';
				echo LR\HtmlHelpers::convertJSToRawText($settings->client_background) /* pos 121:107 */;
				echo '\') !important;
';
			} else /* pos 122:17 */ {
				echo '                    background-image: linear-gradient(rgba(8, 10, 16, 0.45), rgba(8, 10, 16, 0.45)), url("https://i.pinimg.com/736x/da/55/b7/da55b707b452c4a2fc798364f0f930ff.jpg") !important;
';
			}
			echo '                background-size: cover;
                background-position: center;
                background-attachment: fixed;
            }
';
		} else /* pos 129:9 */ {
			echo '            body.shell-public {
';
			if ($settings->site_background ?? null) /* pos 131:17 */ {
				echo '                    background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(\'';
				echo LR\HtmlHelpers::convertJSToRawText($settings->site_background) /* pos 132:95 */;
				echo '\') !important;
';
			} else /* pos 133:17 */ {
				echo '                    background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url("https://i.pinimg.com/736x/da/55/b7/da55b707b452c4a2fc798364f0f930ff.jpg") !important;
';
			}
			echo '                background-size: cover;
                background-position: center;
                background-attachment: fixed;
            }
';
		}
		echo '    </style>

';
		if ($shell_layout == 'client') /* pos 143:5 */ {
			echo '        <link';
			echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->asset_url)('css/client_theme.css'))) /* pos 144:23 */;
			echo ' rel="stylesheet">
';
		}
		echo "\n";
		$this->renderBlock('opengraph', get_defined_vars()) /* pos 147:5 */;
		$this->renderBlock('head', get_defined_vars()) /* pos 148:5 */;
		echo '</head>

<body class="d-flex flex-column min-vh-100 shell-';
		echo LR\HtmlHelpers::escapeAttr($shell_layout) /* pos 151:50 */;
		echo '">


';
		if ($shell_layout == 'client') /* pos 159:1 */ {
			echo '    <!-- Neo-Cyberpunk Client Layout -->
';
			$this->createTemplate('client/_sidebar_client.latte', ['settings' => $settings, 'client' => $client, 'profile' => $profile, 'request' => $request, 'guest' => $guest] + $this->params, 'include')->renderToContentType('html') /* pos 161:5 */;
			echo '    
    <div class="client-main-wrapper">
';
			$this->createTemplate('client/_topbar_client.latte', ['settings' => $settings, 'client' => $client, 'profile' => $profile, 'request' => $request] + $this->params, 'include')->renderToContentType('html') /* pos 164:9 */;
			echo '        
        <div class="client-content">
';
			$this->createTemplate('partial_message.latte', $this->params, 'include')->renderToContentType('html') /* pos 167:13 */;
			echo '            
';
			$this->renderBlock('main_content', get_defined_vars(), 'html') /* pos 169:13 */;
			echo '        </div>
    </div>
';
		} else /* pos 172:1 */ {
			$this->createTemplate('_navbar.latte', ['settings' => $settings, 'client' => $client, 'profile' => $profile, 'request' => $request, 'shell_layout' => $shell_layout] + $this->params, 'include')->renderToContentType('html') /* pos 173:5 */;
			echo "\n";
			$this->renderBlock('content_banner', get_defined_vars()) /* pos 175:5 */;
			echo '
    <main class="container main-content-wrapper flex-grow-1">
        <div class="row">
            <div class="col-12">
';
			$this->createTemplate('partial_message.latte', $this->params, 'include')->renderToContentType('html') /* pos 180:17 */;
			echo '
                <div class="content-body">
';
			$this->renderBlock('main_content', get_defined_vars(), 'html') /* pos 183:21 */;
			echo '                </div>
            </div>
        </div>
    </main>

';
			$this->createTemplate('_footer.latte', ['settings' => $settings, 'company' => $company, 'guest' => $guest, 'now' => $now] + $this->params, 'include')->renderToContentType('html') /* pos 189:5 */;
		}
		echo '
    <!-- Scripts -->
    <script';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)(($this->filters->asset_url)('js/jquery.js'))) /* pos 193:20 */;
		echo '></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script';
		echo LR\HtmlHelpers::formatAttribute(' src', ($this->filters->checkUrl)(($this->filters->asset_url)('js/ohms.js'))) /* pos 195:20 */;
		echo '></script>
    
    <script>
        $(function() {
            // Global UI enhancements
            $(\'.api-form\').on(\'success\', function() {
                // Potential global success handler
            });
        });
    </script>

';
		if ($settings->inject_javascript ?? '') /* pos 206:5 */ {
			echo '        <script>';
			echo LR\HtmlHelpers::convertJSToRawText($settings->inject_javascript) /* pos 207:17 */;
			echo '</script>
';
		}
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 210:5 */;
		echo "\n";
		$this->renderBlock('modals', get_defined_vars()) /* pos 212:5 */;
		echo '    <noscript><div class="alert alert-warning text-center m-0 border-0 rounded-0">Many features on OHMS require Javascript and cookies. Please enable them in your browser.</div></noscript>
</body>
</html>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		$company = $guest->system_company() /* pos 1:1 */;
		$profile = $client ? $client->client_get() : [] /* pos 2:1 */;
		$req_url = $request->_url ?? '' /* pos 3:1 */;
		$request_path = ltrim($req_url, '/') /* pos 4:1 */;
		$srv_uri = $request->getServer('REQUEST_URI') ?? '' /* pos 5:1 */;
		$request_uri = ltrim($srv_uri, '/') /* pos 6:1 */;
		$shell_layout = $shell_layout ?? 'public' /* pos 7:1 */;
		if (str_contains($request_uri, 'client') || str_contains($request_path, 'client') || str_contains($request_uri, 'support') || str_contains($request_path, 'support') || str_contains($request_uri, 'invoice') || str_contains($request_path, 'invoice') || str_contains($request_uri, 'order/service') || str_contains($request_path, 'order/service') || $client && (str_contains($request_path, 'kb') || str_contains($request_uri, 'kb'))) /* pos 8:1 */ {
			$shell_layout = 'client' /* pos 17:5 */;
		}
		return get_defined_vars();
	}


	/** {block meta_title} on line 23 */
	public function blockMeta_title(array $ʟ_args): void
	{
	}


	/** {block meta_description} on line 30 */
	public function blockMeta_description(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeAttr($settings->meta_description) /* pos 30:63 */;
	}


	/** {block meta_keywords} on line 31 */
	public function blockMeta_keywords(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeAttr($settings->meta_keywords) /* pos 31:57 */;
	}


	/** {block opengraph} on line 147 */
	public function blockOpengraph(array $ʟ_args): void
	{
	}


	/** {block head} on line 148 */
	public function blockHead(array $ʟ_args): void
	{
	}


	/** {define main_content} on line 153 */
	public function blockMain_content(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content_before', get_defined_vars()) /* pos 154:5 */;
		$this->renderBlock('content', get_defined_vars()) /* pos 155:5 */;
		$this->renderBlock('content_after', get_defined_vars()) /* pos 156:5 */;
	}


	/** {block content_before} on line 154 */
	public function blockContent_before(array $ʟ_args): void
	{
	}


	/** {block content} on line 155 */
	public function blockContent(array $ʟ_args): void
	{
	}


	/** {block content_after} on line 156 */
	public function blockContent_after(array $ʟ_args): void
	{
	}


	/** {block content_banner} on line 175 */
	public function blockContent_banner(array $ʟ_args): void
	{
	}


	/** {block js} on line 210 */
	public function blockJs(array $ʟ_args): void
	{
	}


	/** {block modals} on line 212 */
	public function blockModals(array $ʟ_args): void
	{
	}
}
