<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/themes\priyxo\html\mod_client_profile.latte */
final class Template_dcebb188d2 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content_before' => 'blockContent_before', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 5:1 */;
		echo '

';
		$profile = $client->client_get() /* pos 7:1 */;
		$initials = substr($profile['first_name'], 0, 1) . substr($profile['last_name'], 0, 1) /* pos 8:1 */;
		echo "\n";
		$this->renderBlock('content_before', get_defined_vars()) /* pos 10:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 17:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$this->createTemplate('macro_functions.latte', $this->params, "import")->render() /* pos 3:1 */;
		return get_defined_vars();
	}


	/** {block meta_title} on line 5 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Profile details')) /* pos 5:19 */;
	}


	/** {block content_before} on line 10 */
	public function blockContent_before(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <div class="client-profile-header">
        <h1 class="text-white fw-bold mb-1">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Profile details')) /* pos 12:45 */;
		echo '</h1>
        <p class="text-white-50 mb-0">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Manage your account settings and security')) /* pos 13:39 */;
		echo '</p>
    </div>
';
	}


	/** {block content} on line 17 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <section class="row g-4">
        <div class="col-lg-4">
            <div class="glass-card text-center h-100 py-5">
                <div class="profile-avatar-initials">';
		echo LR\HtmlHelpers::escapeText(($this->filters->upper)($initials)) /* pos 21:54 */;
		echo '</div>
                <h3 class="text-white fw-bold">';
		echo LR\HtmlHelpers::escapeText($profile['first_name']) /* pos 22:48 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($profile['last_name']) /* pos 22:73 */;
		echo '</h3>
                <p class="text-neon-blue mb-4">';
		echo LR\HtmlHelpers::escapeText($profile['email']) /* pos 23:48 */;
		echo '</p>
                
                <div class="d-flex justify-content-center gap-3">
                    <div class="text-center px-3 border-end border-secondary border-opacity-25">
                        <div class="text-white fw-bold small text-uppercase">Currency</div>
                        <div class="text-neon-blue">';
		echo LR\HtmlHelpers::escapeText($profile['currency'] ?? 'USD') /* pos 28:53 */;
		echo '</div>
                    </div>
                     <div class="text-center px-3">
                        <div class="text-white fw-bold small text-uppercase">Status</div>
                        <div class="text-success small">Active</div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-lg-8">
            <div class="client-tabs">
                <ul id="tabProfile" class="nav nav-tabs border-0" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#details">
                            <i class="fa fa-user me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Details')) /* pos 43:60 */;
		echo '</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#password">
                            <i class="fa fa-key me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password')) /* pos 47:59 */;
		echo '</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#currency">
                            <i class="fa fa-coins me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Currency')) /* pos 51:61 */;
		echo '</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" data-bs-toggle="tab" data-bs-target="#api">
                            <i class="fa fa-plug me-2"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('API')) /* pos 55:60 */;
		echo '</button>
                    </li>
                </ul>
            </div>

            <div id="myTabContent" class="tab-content mt-4">
                <!-- Tab: Details -->
                <div class="tab-pane fade show active" id="details">
                    <div class="glass-card">
                        <h4 class="text-white mb-4"><i class="fa fa-id-card me-2 text-primary"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Update profile')) /* pos 64:100 */;
		echo '</h4>
                        <form class="api-form" method="post" data-api-url="client/client/update"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('Profile updated')) /* pos 65:114 */;
		echo '>
                            <div class="row g-3">
                                <div class="col-md-12">
                                    <label class="form-label" for="inputEmail">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Email Address')) /* pos 68:80 */;
		echo '</label>
                                    <input type="email" class="form-control" id="inputEmail" name="email"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['email']) /* pos 69:115 */;
		echo ' required>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="inputFirstName">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('First name')) /* pos 72:84 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputFirstName" name="first_name"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['first_name']) /* pos 73:123 */;
		echo ' required>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="inputLastName">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Last name')) /* pos 76:83 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputLastName" name="last_name"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['last_name']) /* pos 77:121 */;
		echo ' required>
                                </div>
                                <div class="col-md-12">
                                    <label class="form-label" for="inputCompany">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Company name')) /* pos 80:82 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputCompany" name="company"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['company']) /* pos 81:118 */;
		echo '>
                                </div>
                                <div class="col-md-12">
                                    <label class="form-label" for="inputPhone">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Phone')) /* pos 84:80 */;
		echo '</label>
                                    <div class="input-group">
                                        <span class="input-group-text bg-dark border-secondary text-white">+</span>
                                        <input type="text" class="form-control" style="max-width: 80px;" name="phone_cc"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['phone_cc']) /* pos 87:130 */;
		echo ' placeholder="CC" required>
                                        <input type="text" class="form-control" id="inputPhone" name="phone"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['phone']) /* pos 88:118 */;
		echo ' placeholder="Number" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="inputAddress1">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Address')) /* pos 92:83 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputAddress1" name="address_1"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['address_1']) /* pos 93:121 */;
		echo ' required>
                                </div>
                                <div class="col-md-6">
                                    <label class="form-label" for="inputAddress2">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Address 2')) /* pos 96:83 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputAddress2" name="address_2"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['address_2']) /* pos 97:121 */;
		echo '>
                                </div>
                                <div class="col-md-4">
                                    <label class="form-label" for="inputCity">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('City')) /* pos 100:79 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputCity" name="city"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['city']) /* pos 101:112 */;
		echo ' required>
                                </div>
                                <div class="col-md-4">
                                    <label class="form-label" for="inputState">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('State')) /* pos 104:80 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputState" name="state"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['state']) /* pos 105:114 */;
		echo '>
                                </div>
                                <div class="col-md-4">
                                    <label class="form-label" for="inputZip">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Zip')) /* pos 108:78 */;
		echo '</label>
                                    <input type="text" class="form-control" id="inputZip" name="postcode"';
		echo LR\HtmlHelpers::formatAttribute(' value', $profile['postcode']) /* pos 109:115 */;
		echo ' required>
                                </div>
                                <div class="col-md-12">
                                    <label class="form-label" for="selectCountry">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Country')) /* pos 112:83 */;
		echo '</label>
                                    <div class="cyber-select-wrapper">
';
		$this->renderBlock('selectbox', ['country', $guest->system_countries, $profile['country'], 1, 'Select country', 'selectCountry'] + [], 'html') /* pos 114:41 */;
		echo '                                    </div>
                                </div>
                                <div class="col-12 mt-4">
                                    <button class="btn btn-primary w-100 py-3 fw-bold text-uppercase" type="submit">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Update')) /* pos 118:117 */;
		echo '</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- Tab: Password -->
                <div class="tab-pane fade" id="password">
                    <div class="glass-card">
                        <h4 class="text-white mb-4"><i class="fa fa-shield-alt me-2 text-primary"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Change password')) /* pos 128:103 */;
		echo '</h4>
                        <form method="post" class="api-form mx-auto" style="max-width: 450px;" data-api-url="client/client/change_password"';
		echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('Password changed')) /* pos 129:157 */;
		echo '>
                            <div class="mb-3">
                                <label class="form-label" for="inputPassword">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password')) /* pos 131:79 */;
		echo '</label>
                                <input type="password" class="form-control" id="inputPassword" name="password" required>
                            </div>
                            <div class="mb-4">
                                <label class="form-label" for="inputPasswordRepeat">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Password confirm')) /* pos 135:85 */;
		echo '</label>
                                <input type="password" class="form-control" id="inputPasswordRepeat" name="password_confirm" required>
                            </div>
                            <button class="btn btn-primary w-100 py-3 fw-bold text-uppercase" type="submit">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Change password')) /* pos 138:109 */;
		echo '</button>
                        </form>
                    </div>
                </div>

                <!-- Tab: Currency -->
                <div class="tab-pane fade" id="currency">
                    <div class="glass-card">
                        <h4 class="text-white mb-4"><i class="fa fa-coins me-2 text-primary"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Currency')) /* pos 146:98 */;
		echo '</h4>
                        <div class="p-4 border border-secondary border-opacity-10 rounded-3 bg-dark bg-opacity-25">
';
		if ($profile['currency']) /* pos 148:29 */ {
			echo '                                <h5 class="text-white mb-2">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Current Currency')) /* pos 149:61 */;
			echo ': <span class="text-neon-blue">';
			echo LR\HtmlHelpers::escapeText($profile['currency']) /* pos 149:119 */;
			echo '</span></h5>
                                <p class="text-white-50 small mb-0">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create new client profile if you want to manage your money in other currency.')) /* pos 150:69 */;
			echo '</p>
';
		} else /* pos 151:29 */ {
			echo '                                <p class="text-white-50 mb-0">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Your profile currency will be defined after your first order.')) /* pos 152:63 */;
			echo '</p>
';
		}
		echo '                        </div>
                    </div>
                </div>

                <!-- Tab: API -->
                <div class="tab-pane fade" id="api">
                    <div class="glass-card">
                        <h4 class="text-white mb-4"><i class="fa fa-plug me-2 text-primary"></i>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('API key')) /* pos 161:97 */;
		echo '</h4>
                        <p class="text-white-50 small mb-4">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('API key allows integration with external applications. Resetting the key will break existing applications using it.')) /* pos 162:61 */;
		echo '</p>
                        
';
		$key = $client->client_api_key_get() /* pos 164:25 */;
		if ($key) /* pos 165:25 */ {
			echo '                            <div class="alert alert-info border-0 bg-primary bg-opacity-10 text-center mb-4 p-4">
                                <label class="text-white-50 small text-uppercase fw-bold d-block mb-2">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Your Secure API Key')) /* pos 167:104 */;
			echo '</label>
                                <code class="fs-5 d-block py-2 text-neon-blue">';
			echo LR\HtmlHelpers::escapeText($key) /* pos 168:80 */;
			echo '</code>
                            </div>
                            <form method="post" class="api-form text-center" data-api-url="client/client/api_key_reset"';
			echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('API key was changed. Please refresh the page.')) /* pos 170:137 */;
			echo '>
                                <button class="btn btn-outline-danger px-5" type="submit"><i class="fa fa-undo-alt me-2"></i>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Reset key')) /* pos 171:126 */;
			echo '</button>
                            </form>
';
		} else /* pos 173:25 */ {
			echo '                            <div class="text-center p-5 border border-dashed border-secondary border-opacity-25 rounded-3 mb-4">
                                <i class="fa fa-key fa-3x text-white-50 mb-3 opacity-25"></i>
                                <h5 class="text-white-50">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('No API key generated yet')) /* pos 176:59 */;
			echo '</h5>
                            </div>
                            <form method="post" class="api-form text-center" data-api-url="client/client/api_key_reset"';
			echo LR\HtmlHelpers::formatDataAttribute(' data-api-msg', ($this->filters->trans)('API key was changed. Please refresh the page.')) /* pos 178:137 */;
			echo '>
                                <button class="btn btn-primary px-5" type="submit">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Create')) /* pos 179:84 */;
			echo ' ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('API Key')) /* pos 179:100 */;
			echo '</button>
                            </form>
';
		}
		echo '                    </div>
                </div>
            </div>
        </div>
    </section>
';
	}
}
