<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/modules\Servicepterodactyl\html_admin\mod_servicepterodactyl_index.latte */
final class Template_0c79c8009b extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 24:1 */;
		echo '

';
		$active_menu = 'extension' /* pos 26:1 */;
		echo "\n";
		$params = $admin->extension_config_get(['ext' => 'mod_servicepterodactyl']) /* pos 28:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 30:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		return get_defined_vars();
	}


	/** {block meta_title} on line 24 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Module')) /* pos 24:19 */;
	}


	/** {block content} on line 30 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '
<div class="widget first">
    <div class="head">
        <h5>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Module')) /* pos 34:13 */;
		echo '</h5>
    </div>

    <div class="help">
        <h3>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Pterodactyl Panel Module')) /* pos 38:13 */;
		echo '</h3>
    </div>
    <div class="body">
        <a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('extension/settings/servicepterodactyl'))) /* pos 41:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Module Settings')) /* pos 41:68 */;
		echo '</a> <br/>
    </div>
</div>
';
	}
}
