<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/modules\Theme\html_admin\mod_theme_settings.latte */
final class Template_80ebe2e591 extends Latte\Runtime\Template
{
	public const Blocks = [
		['meta_title' => 'blockMeta_title', 'breadcrumbs' => 'blockBreadcrumbs', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 24:1 */;
		echo '

';
		$active_menu = 'system' /* pos 26:1 */;
		echo "\n";
		$this->renderBlock('breadcrumbs', get_defined_vars()) /* pos 28:1 */;
		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 36:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['i' => '50, 90', 'theme_item' => '50, 90'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		return get_defined_vars();
	}


	/** {block meta_title} on line 24 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Themes')) /* pos 24:19 */;
	}


	/** {block breadcrumbs} on line 28 */
	public function blockBreadcrumbs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<ul>
    <li class="firstB"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('/'))) /* pos 30:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 30:47 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('system'))) /* pos 31:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 31:35 */;
		echo '</a></li>
    <li class="lastB">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Themes')) /* pos 32:23 */;
		echo '</li>
</ul>
';
	}


	/** {block content} on line 36 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="widget">
    <div class="head">
        <h5 class="iPaintBrush">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Client area themes')) /* pos 39:33 */;
		echo '</h5>
    </div>
    <table class="tableStatic wide">
        <thead>
            <tr>
                <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Name')) /* pos 44:21 */;
		echo '</td>
                <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Actions')) /* pos 45:21 */;
		echo '</td>
            </tr>
        </thead>
        <tbody>
';
		$themes = $admin->theme_get_list(['per_page' => 100]) /* pos 49:13 */;
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($themes->list, $ʟ_it ?? null) as $i => $theme_item) /* pos 50:13 */ {
			echo '            <tr>
                <td>';
			if ($guest->extension_theme(true)->code == $theme_item->code) /* pos 52:21 */ {
				echo '<strong>';
				echo LR\HtmlHelpers::escapeText($theme_item->code) /* pos 52:92 */;
				echo '</strong>';
			} else /* pos 52:120 */ {
				echo LR\HtmlHelpers::escapeText($theme_item->code) /* pos 52:126 */;
			}
			echo '</td>
                <td class="actions">
                    <a class="btnIconLeft mr10" href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('theme')) /* pos 54:55 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($theme_item->code) /* pos 54:70 */;
			echo '">
                        <img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 55:35 */;
			echo 'images/icons/dark/cog.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 55:101 */;
			echo '</span>
                    </a>
';
			if ($guest->extension_theme(true)->code != $theme_item->code) /* pos 57:21 */ {
				echo '                    <a class="btnIconLeft mr10 api-link"';
				echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->alink)('extension/settings/theme')) /* pos 58:79 */;
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/theme/select', ['code' => $theme_item->code]))) /* pos 58:122 */;
				echo '>
                        <img src="';
				echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 59:35 */;
				echo 'images/icons/dark/star.png" alt="" class="icon"><span>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Set as default')) /* pos 59:102 */;
				echo '</span>
                    </a>
';
			}
			echo '                </td>
            </tr>
        </tbody>
';
		}
		if ($iterator->isEmpty()) /* pos 65:9 */ {
			echo '        <tbody>
            <tr>
                <td colspan="5">
                    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('The list is empty')) /* pos 69:21 */;
			echo '
                </td>
            </tr>
        </tbody>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '    </table>
</div>

<div class="widget">
    <div class="head">
        <h5 class="iPaintBrush">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Admin area themes')) /* pos 79:33 */;
		echo '</h5>
    </div>
    <table class="tableStatic wide">
        <thead>
            <tr>
                <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Name')) /* pos 84:21 */;
		echo '</td>
                <td>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Actions')) /* pos 85:21 */;
		echo '</td>
            </tr>
        </thead>
        <tbody>
';
		$themes = $admin->theme_get_admin_list(['per_page' => 100]) /* pos 89:13 */;
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($themes->list, $ʟ_it ?? null) as $i => $theme_item) /* pos 90:13 */ {
			echo '            <tr>
                <td>';
			if ($guest->extension_theme(false)->code == $theme_item->code) /* pos 92:21 */ {
				echo '<strong>';
				echo LR\HtmlHelpers::escapeText(($this->filters->replace)($theme_item->code, ['admin_' => ''])) /* pos 92:93 */;
				echo '</strong>';
			} else /* pos 92:144 */ {
				echo LR\HtmlHelpers::escapeText(($this->filters->replace)($theme_item->code, ['admin_' => ''])) /* pos 92:150 */;
			}
			echo '</td>
                <td class="actions">
                    <a class="btnIconLeft mr10" href="';
			echo LR\HtmlHelpers::escapeAttr(($this->filters->alink)('theme')) /* pos 94:55 */;
			echo '/';
			echo LR\HtmlHelpers::escapeAttr($theme_item->code) /* pos 94:70 */;
			echo '"><img src="';
			echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 94:101 */;
			echo 'images/icons/dark/cog.png" alt="" class="icon"><span>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 94:167 */;
			echo '</span></a>
';
			if ($guest->extension_theme(false)->code != $theme_item->code) /* pos 95:21 */ {
				echo '                    <a class="btnIconLeft mr10 api-link"';
				echo LR\HtmlHelpers::formatDataAttribute(' data-api-redirect', ($this->filters->alink)('extension/settings/theme')) /* pos 96:79 */;
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/theme/select', ['code' => $theme_item->code]))) /* pos 96:122 */;
				echo '>
                        <img src="';
				echo LR\HtmlHelpers::escapeAttr($theme->url) /* pos 97:35 */;
				echo 'images/icons/dark/star.png" alt="" class="icon"><span>';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Set as default')) /* pos 97:102 */;
				echo '</span>
                    </a>
';
			}
			echo '                </td>
            </tr>
        </tbody>
';
		}
		if ($iterator->isEmpty()) /* pos 103:9 */ {
			echo '        <tbody>
            <tr>
                <td colspan="5">
                    ';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('The list is empty')) /* pos 107:21 */;
			echo '
                </td>
            </tr>
        </tbody>
';

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo '    </table>
</div>
';
	}
}
