<?php

/** Generated by Latte 3.1.2 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: C:\Users\User\Desktop\OHMS/modules\Theme\html_admin\mod_theme_preset.latte */
final class Template_1f9d3e882d extends Latte\Runtime\Template
{
	public const Blocks = [
		['breadcrumbs' => 'blockBreadcrumbs', 'meta_title' => 'blockMeta_title', 'content' => 'blockContent', 'head' => 'blockHead', 'js' => 'blockJs'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('breadcrumbs', get_defined_vars()) /* pos 26:1 */;
		echo "\n";
		$this->renderBlock('meta_title', get_defined_vars()) /* pos 35:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 37:1 */;
		echo "\n";
		$this->renderBlock('head', get_defined_vars()) /* pos 81:1 */;
		echo "\n";
		$this->renderBlock('js', get_defined_vars()) /* pos 86:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['preset' => '55'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = $request->ajax ? 'layout_blank.latte' : 'layout_default.latte';
		$active_menu = 'system' /* pos 24:1 */;
		return get_defined_vars();
	}


	/** {block breadcrumbs} on line 26 */
	public function blockBreadcrumbs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<ul>
    <li class="firstB"><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('/'))) /* pos 28:35 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Home')) /* pos 28:47 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('system'))) /* pos 29:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings')) /* pos 29:37 */;
		echo '</a></li>
    <li><a';
		echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->alink)('extension/settings/theme'))) /* pos 30:20 */;
		echo '>';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Themes')) /* pos 30:55 */;
		echo '</a></li>
    <li class="lastB">';
		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings for')) /* pos 31:23 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($theme_code) /* pos 31:47 */;
		echo '</li>
</ul>
';
	}


	/** {block meta_title} on line 35 */
	public function blockMeta_title(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Settings for')) /* pos 35:19 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($theme_code) /* pos 35:43 */;
	}


	/** {block content} on line 37 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		if ($error) /* pos 38:5 */ {
			echo '        <div class="nNote nFailure hideit first">
            <p><strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('IMPORTANT')) /* pos 40:24 */;
			echo ': </strong>';
			echo LR\HtmlHelpers::escapeText($error) /* pos 40:55 */;
			echo '</p>
        </div>
';
		}
		echo "\n";
		if ($info) /* pos 44:5 */ {
			echo '        <div class="nNote nInformation hideit first">
            <p><strong>';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('INFORMATION')) /* pos 46:24 */;
			echo ': </strong>';
			echo LR\HtmlHelpers::escapeText($info) /* pos 46:57 */;
			echo '</p>
        </div>
';
		}
		echo "\n";
		if ($settings_html) /* pos 50:5 */ {
			echo '        <div class="widget">
            <div class="head"';
			echo LR\HtmlHelpers::formatAttribute(' title', ($this->filters->trans)('Switch to a predefined set of theme settings from the dropdown. Adjust each section and apply the changes once you\'re done.')) /* pos 52:40 */;
			echo '>
                <h5 class="iMoney">Your current preset: </h5>
                <select name="preset" id="theme-preset-select"';
			echo LR\HtmlHelpers::formatDataAttribute(' data-theme-code', $theme_code) /* pos 54:82 */;
			echo ' style="margin-top: 10px;">
';
			foreach ($presets as $preset) /* pos 55:21 */ {
				echo '                        <option';
				echo LR\HtmlHelpers::formatAttribute(' value', $preset) /* pos 56:41 */;
				echo ' ';
				if ($preset == $current_preset) /* pos 56:51 */ {
					echo 'selected="selected"';
				}
				echo '>';
				echo LR\HtmlHelpers::escapeText($preset) /* pos 56:109 */;
				echo '</option>
';

			}

			echo '                </select>
';
			if (($this->filters->length)($presets) > 1) /* pos 59:17 */ {
				echo '                    <a';
				echo LR\HtmlHelpers::formatAttribute(' href', ($this->filters->checkUrl)(($this->filters->link)('api/admin/theme/preset_delete', ['code' => $theme_code, 'preset' => $current_preset]))) /* pos 60:32 */;
				echo ' class="api-link" data-api-confirm="Are you sure?" data-api-reload="1">';
				echo LR\HtmlHelpers::escapeText(($this->filters->trans)('delete this preset')) /* pos 60:194 */;
				echo '</a>
';
			}
			echo '            </div>

            <div id="theme-settings">
                <form method="post" action="" enctype="multipart/form-data">
                    ';
			echo $settings_html /* pos 66:21 */;
			echo '
                    <div class="actions">
                        <input type="checkbox" name="save-current-setting" value="1" id="save-current-setting">
                        <label for="save-current-setting">';
			echo LR\HtmlHelpers::escapeText(($this->filters->trans)('Save current settings as a new preset called')) /* pos 69:59 */;
			echo '</label>
                        <input type="text" name="save-current-setting-preset" placeholder=""/>
                        <br/>
                        <br/>
                        <input type="submit"';
			echo LR\HtmlHelpers::formatAttribute(' value', ($this->filters->trans)('Apply changes')) /* pos 73:55 */;
			echo ' class="greyishBtn"/>
                    </div>
                </form>
            </div>
        </div>
';
		}
	}


	/** {block head} on line 81 */
	public function blockHead(array $ʟ_args): void
	{
		echo '    <script src="js/jquery.spectrum.js"></script>
    <link rel="stylesheet" href="css/spectrum.css" />
';
	}


	/** {block js} on line 86 */
	public function blockJs(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script>
window.themePresetData = {
    pagePairs: ';
		echo LR\Helpers::escapeJs(json_encode($admin->page_get_pairs)) /* pos 89:16 */;
		echo ',
    snippets: ';
		echo LR\Helpers::escapeJs(json_encode($snippets)) /* pos 90:15 */;
		echo ',
    productPairs: ';
		echo LR\Helpers::escapeJs(json_encode($admin->product_get_pairs)) /* pos 91:19 */;
		echo ',
    orderformPairs: ';
		echo LR\Helpers::escapeJs(json_encode($orderform_pairs)) /* pos 92:21 */;
		echo ',
    settings: ';
		echo LR\Helpers::escapeJs(json_encode($settings)) /* pos 93:15 */;
		echo ',
    uploaded: ';
		echo LR\Helpers::escapeJs(json_encode($uploaded)) /* pos 94:15 */;
		echo '
};
</script>
<script src="/modules/Theme/assets/theme_preset.js"></script>
';
	}
}
